// Command json2cpp converts the Vego JSON form into a C++ header
// and source pair. The output includes the hand-written runtime
// vg.hpp, which supplies the Slice and Str value types, the Arena
// allocator, and the Go conversion and comparison helpers. Every
// function that allocates receives an Arena reference as its first
// parameter, "mem"; the output holds no global state.
//
// Usage:
//
//	json2cpp [-hpp engine.hpp] [-cpp engine.cpp] input.json
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"revera1/vegoc"
)

func fatal(args ...any) {
	fmt.Fprintln(os.Stderr, args...)
	os.Exit(1)
}

func main() {
	hpp := flag.String("hpp", "", "output header (default stdout)")
	cpp := flag.String("cpp", "", "output source (default stdout)")
	flag.Parse()
	if flag.NArg() != 1 {
		fatal("usage: json2cpp [-hpp engine.hpp] [-cpp engine.cpp] input.json")
	}
	p, err := vegoc.LoadFile(flag.Arg(0))
	if err != nil {
		fatal(err)
	}
	g := &gen{p: p, hppName: "engine.hpp"}
	if *hpp != "" {
		g.hppName = filepath.Base(*hpp)
	}
	header, source := g.files()
	write := func(path, text string) {
		if path == "" {
			os.Stdout.WriteString(text)
			return
		}
		if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
			fatal(err)
		}
	}
	write(*hpp, header)
	write(*cpp, source)
}

type gen struct {
	p       *vegoc.Program
	b       strings.Builder
	fn      *vegoc.FuncDecl
	tmp     int
	hppName string
}

// cppReserved holds C++ keywords and libc macro names that a Vego
// identifier must not collide with.
var cppReserved = map[string]bool{
	"alignas": true, "alignof": true, "and": true, "and_eq": true,
	"asm": true, "auto": true, "bitand": true, "bitor": true,
	"bool": true, "break": true, "case": true, "catch": true,
	"char": true, "class": true, "compl": true, "concept": true,
	"const": true, "consteval": true, "constexpr": true,
	"constinit": true, "continue": true, "co_await": true,
	"co_return": true, "co_yield": true, "decltype": true,
	"default": true, "delete": true, "do": true, "double": true,
	"dynamic_cast": true, "else": true, "enum": true, "explicit": true,
	"export": true, "extern": true, "false": true, "float": true,
	"for": true, "friend": true, "goto": true, "if": true,
	"inline": true, "int": true, "long": true, "mutable": true,
	"namespace": true, "new": true, "noexcept": true, "not": true,
	"not_eq": true, "nullptr": true, "operator": true, "or": true,
	"or_eq": true, "private": true, "protected": true, "public": true,
	"register": true, "reinterpret_cast": true, "requires": true,
	"return": true, "short": true, "signed": true, "sizeof": true,
	"static": true, "static_assert": true, "static_cast": true,
	"struct": true, "switch": true, "template": true, "this": true,
	"thread_local": true, "throw": true, "true": true, "try": true,
	"typedef": true, "typeid": true, "typename": true, "union": true,
	"unsigned": true, "using": true, "virtual": true, "void": true,
	"volatile": true, "wchar_t": true, "while": true, "xor": true,
	"xor_eq": true, "NULL": true, "EOF": true, "errno": true,
	"stdin": true, "stdout": true, "stderr": true, "minor": true,
	"major": true, "index": true,
}

func ident(name string) string {
	if cppReserved[name] {
		return name + "_"
	}
	return name
}

func (g *gen) files() (string, string) {
	tups := map[string][2]*vegoc.Type{}
	for _, f := range g.p.Funcs {
		if len(f.Results) == 2 {
			pair := [2]*vegoc.Type{f.Results[0], f.Results[1]}
			tups[vegoc.TupName(pair)] = pair
		}
	}

	var h strings.Builder
	h.WriteString("// Code generated by json2cpp from the Vego JSON form. DO NOT EDIT.\n\n")
	fmt.Fprintf(&h, "#pragma once\n\n#include \"vg.hpp\"\n\nnamespace %s {\n\n", g.p.Package)
	for _, d := range g.constOrder() {
		fmt.Fprintf(&h, "inline constexpr %s %s = %s;\n", g.typ(d.Inferred), ident(d.Name), g.expr(d.Value))
	}
	h.WriteString("\n")
	for _, s := range g.p.Types {
		fmt.Fprintf(&h, "struct %s;\n", ident(s.Name))
	}
	h.WriteString("\n")
	for _, s := range g.structOrder() {
		fmt.Fprintf(&h, "struct %s {\n", ident(s.Name))
		for _, f := range s.Fields {
			fmt.Fprintf(&h, "    %s %s = {};\n", g.typ(f.Type), ident(f.Name))
		}
		if g.comparable(&vegoc.Type{K: vegoc.KStruct, Name: s.Name}) {
			fmt.Fprintf(&h, "    bool operator==(const %s&) const = default;\n", ident(s.Name))
		}
		h.WriteString("};\n\n")
	}
	var names []string
	for n := range tups {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		pair := tups[n]
		fmt.Fprintf(&h, "struct %s { %s r0; %s r1; };\n", n, g.typ(pair[0]), g.typ(pair[1]))
	}
	h.WriteString("\n")
	for _, d := range g.p.Vars {
		fmt.Fprintf(&h, "inline constexpr %s %s = %s;\n", g.typ(d.Inferred), ident(d.Name), g.expr(d.Value))
	}
	h.WriteString("\n")
	for _, f := range g.p.Funcs {
		fmt.Fprintf(&h, "%s;\n", g.signature(f))
	}
	fmt.Fprintf(&h, "\n} // namespace %s\n", g.p.Package)

	g.b.Reset()
	g.wf("// Code generated by json2cpp from the Vego JSON form. DO NOT EDIT.\n\n")
	g.wf("#include \"%s\"\n\nnamespace %s {\n\n", g.hppName, g.p.Package)
	for _, f := range g.p.Funcs {
		g.emitFunc(f)
	}
	g.wf("} // namespace %s\n", g.p.Package)
	return h.String(), g.b.String()
}

// constOrder sorts constant declarations so every constant appears
// after the constants its value mentions. Go accepts any order;
// C++ does not.
func (g *gen) constOrder() []*vegoc.ValueDecl {
	var out []*vegoc.ValueDecl
	state := map[string]int{}
	var visit func(d *vegoc.ValueDecl)
	visit = func(d *vegoc.ValueDecl) {
		switch state[d.Name] {
		case 2:
			return
		case 1:
			fatal("constant dependency cycle at", d.Name)
		}
		state[d.Name] = 1
		vegoc.WalkExpr(d.Value, func(e *vegoc.Expr) {
			if e.K == "ident" {
				if dep, ok := g.p.ConstMap[e.Name]; ok {
					visit(dep)
				}
			}
		})
		state[d.Name] = 2
		out = append(out, d)
	}
	for _, d := range g.p.Consts {
		visit(d)
	}
	return out
}

func (g *gen) wf(format string, args ...any) {
	fmt.Fprintf(&g.b, format, args...)
}

// comparable reports whether Go allows == on the type: scalars,
// strings, comparable structs, and arrays of comparable elements.
// Slices are not comparable. vg::Str carries a content-comparing
// operator==, so a defaulted struct operator== stays correct.
func (g *gen) comparable(t *vegoc.Type) bool {
	switch t.K {
	case vegoc.KSlice, vegoc.KPtr:
		return false
	case vegoc.KArray:
		return g.comparable(t.Elem)
	case vegoc.KStruct:
		for _, f := range g.p.StructMap[t.Name].Fields {
			if !g.comparable(f.Type) {
				return false
			}
		}
		return true
	}
	return true
}

// structOrder sorts struct declarations so a struct appears after
// every struct it embeds by value (directly or through an array).
// Go accepts any order; C++ does not.
func (g *gen) structOrder() []*vegoc.StructDecl {
	var out []*vegoc.StructDecl
	state := map[string]int{}
	var visit func(s *vegoc.StructDecl)
	var visitType func(t *vegoc.Type)
	visitType = func(t *vegoc.Type) {
		switch t.K {
		case vegoc.KStruct:
			visit(g.p.StructMap[t.Name])
		case vegoc.KArray:
			visitType(t.Elem)
		}
	}
	visit = func(s *vegoc.StructDecl) {
		switch state[s.Name] {
		case 2:
			return
		case 1:
			fatal("struct value cycle at", s.Name)
		}
		state[s.Name] = 1
		for _, f := range s.Fields {
			visitType(f.Type)
		}
		state[s.Name] = 2
		out = append(out, s)
	}
	for _, s := range g.p.Types {
		visit(s)
	}
	return out
}

func (g *gen) typ(t *vegoc.Type) string {
	switch t.K {
	case vegoc.KBool:
		return "bool"
	case vegoc.KU8:
		return "uint8_t"
	case vegoc.KU16:
		return "uint16_t"
	case vegoc.KU32:
		return "uint32_t"
	case vegoc.KU64:
		return "uint64_t"
	case vegoc.KI32:
		return "int32_t"
	case vegoc.KI64, vegoc.KInt:
		return "int64_t"
	case vegoc.KStr:
		return "vg::Str"
	case vegoc.KSlice:
		return "vg::Slice<" + g.typ(t.Elem) + ">"
	case vegoc.KArray:
		return "std::array<" + g.typ(t.Elem) + ", " + g.expr(t.ALen) + ">"
	case vegoc.KStruct:
		return ident(t.Name)
	case vegoc.KPtr:
		return ident(t.Name) + "&"
	}
	fatal("cannot map type", t)
	return ""
}

func (g *gen) signature(f *vegoc.FuncDecl) string {
	var params []string
	if f.Allocates {
		params = append(params, "vg::Arena& mem")
	}
	for _, pa := range f.Params {
		params = append(params, g.typ(pa.Type)+" "+ident(pa.Name))
	}
	ret := "void"
	switch len(f.Results) {
	case 1:
		ret = g.typ(f.Results[0])
	case 2:
		ret = vegoc.TupName([2]*vegoc.Type{f.Results[0], f.Results[1]})
	}
	return fmt.Sprintf("%s %s(%s)", ret, ident(f.Name), strings.Join(params, ", "))
}

func (g *gen) emitFunc(f *vegoc.FuncDecl) {
	g.fn = f
	g.tmp = 0
	g.wf("%s {\n", g.signature(f))
	for _, pa := range f.Params {
		if info := f.Info[pa.Name]; info != nil && !info.Used {
			g.wf("    (void)%s;\n", ident(pa.Name))
		}
	}
	g.body(f.Body, 1)
	g.wf("}\n\n")
	g.fn = nil
}

func (g *gen) indent(depth int) {
	for range depth {
		g.b.WriteString("    ")
	}
}

func (g *gen) body(body []*vegoc.Stmt, depth int) {
	for _, s := range body {
		g.stmt(s, depth)
	}
}

func (g *gen) newTmp() string {
	g.tmp++
	return fmt.Sprintf("_t%d", g.tmp)
}

func (g *gen) stmt(s *vegoc.Stmt, depth int) {
	switch s.K {
	case "var_decl", "define", "assign", "op_assign":
		g.indent(depth)
		g.simpleStmt(s, depth)
	case "if":
		g.indent(depth)
		g.wf("if (%s) {\n", g.expr(s.Cond))
		g.body(s.Then, depth+1)
		g.indent(depth)
		if s.HasElse {
			g.wf("} else {\n")
			g.body(s.Else, depth+1)
			g.indent(depth)
		}
		g.wf("}\n")
	case "for":
		g.indent(depth)
		switch {
		case s.Init == nil && s.Post == nil && s.Cond == nil:
			g.wf("for (;;) {\n")
		case s.Init == nil && s.Post == nil:
			g.wf("while (%s) {\n", g.expr(s.Cond))
		default:
			init, cond, post := "", "", ""
			if s.Init != nil {
				init = g.inlineStmt(s.Init)
			}
			if s.Cond != nil {
				cond = g.expr(s.Cond)
			}
			if s.Post != nil {
				post = g.inlineStmt(s.Post)
			}
			g.wf("for (%s; %s; %s) {\n", init, cond, post)
		}
		g.body(s.Body, depth+1)
		g.indent(depth)
		g.wf("}\n")
	case "range":
		g.emitRange(s, depth)
	case "switch":
		g.indent(depth)
		g.wf("switch (%s) {\n", g.expr(s.Tag))
		for _, cs := range s.Cases {
			g.indent(depth)
			for i, v := range cs.Values {
				if i > 0 {
					g.wf(" ")
				}
				g.wf("case %s:", g.expr(v))
			}
			g.wf(" {\n")
			g.body(cs.Body, depth+1)
			g.indent(depth)
			g.wf("} break;\n")
		}
		g.indent(depth)
		if s.HasDef {
			g.wf("default: {\n")
			g.body(s.Default, depth+1)
			g.indent(depth)
			g.wf("} break;\n")
		} else {
			g.wf("default: break;\n")
		}
		g.indent(depth)
		g.wf("}\n")
	case "break":
		g.indent(depth)
		g.wf("break;\n")
	case "continue":
		g.indent(depth)
		g.wf("continue;\n")
	case "return":
		g.indent(depth)
		switch len(s.Values) {
		case 0:
			g.wf("return;\n")
		case 1:
			g.wf("return %s;\n", g.expr(s.Values[0]))
		default:
			ret := vegoc.TupName([2]*vegoc.Type{g.fn.Results[0], g.fn.Results[1]})
			g.wf("return %s{%s, %s};\n", ret, g.expr(s.Values[0]), g.expr(s.Values[1]))
		}
	case "expr_stmt":
		g.indent(depth)
		if s.Value.Typ != nil {
			g.wf("(void)(%s);\n", g.expr(s.Value))
		} else {
			g.wf("%s;\n", g.expr(s.Value))
		}
	case "block":
		g.indent(depth)
		g.wf("{\n")
		g.body(s.Body, depth+1)
		g.indent(depth)
		g.wf("}\n")
	default:
		fatal("unknown statement kind", s.K)
	}
}

// simpleStmt emits a declaration or assignment, indented, with its
// own newline. Two-value forms expand to a temporary block.
func (g *gen) simpleStmt(s *vegoc.Stmt, depth int) {
	switch s.K {
	case "var_decl":
		if s.Value != nil {
			g.wf("%s %s = %s;\n", g.typ(s.TypeRef), ident(s.Name), g.expr(s.Value))
		} else {
			g.wf("%s %s{};\n", g.typ(s.TypeRef), ident(s.Name))
		}
	case "define":
		if len(s.Names) == 1 {
			g.wf("%s %s = %s;\n", g.typ(s.DeclaredTypes[0]), ident(s.Names[0]), g.expr(s.Value))
			return
		}
		tmp := g.newTmp()
		g.wf("auto %s = %s;\n", tmp, g.expr(s.Value))
		for i, n := range s.Names {
			if n == "_" {
				continue
			}
			g.indent(depth)
			g.wf("%s %s = %s.r%d;\n", g.typ(s.DeclaredTypes[i]), ident(n), tmp, i)
		}
	case "assign":
		if len(s.Lhs) == 2 {
			tmp := g.newTmp()
			g.wf("{\n")
			g.indent(depth + 1)
			g.wf("auto %s = %s;\n", tmp, g.expr(s.Value))
			for i, l := range s.Lhs {
				if l.K == "ident" && l.Name == "_" {
					continue
				}
				g.indent(depth + 1)
				g.wf("%s = %s.r%d;\n", g.expr(l), tmp, i)
			}
			g.indent(depth)
			g.wf("}\n")
			return
		}
		l := s.Lhs[0]
		if l.K == "ident" && l.Name == "_" {
			g.wf("(void)(%s);\n", g.expr(s.Value))
			return
		}
		if vegoc.Impure(l) {
			// Go evaluates the target place before the value; since
			// C++17 a plain assignment sequences the value first.
			g.wf("{ auto&& _p = %s; _p = %s; }\n", g.expr(l), g.expr(s.Value))
			return
		}
		g.wf("%s = %s;\n", g.expr(l), g.expr(s.Value))
	case "op_assign":
		if vegoc.Impure(s.Lhs[0]) {
			g.wf("{ auto&& _p = %s; %s; }\n", g.expr(s.Lhs[0]), g.opAssign(s, "_p"))
			return
		}
		g.wf("%s;\n", g.opAssign(s, g.expr(s.Lhs[0])))
	default:
		fatal("not a simple statement", s.K)
	}
}

// opAssign renders a compound assignment against an already
// rendered place. C++ has no &^=, and signed division overflow is
// undefined even under -fwrapv, so those forms rewrite.
func (g *gen) opAssign(s *vegoc.Stmt, place string) string {
	val := g.expr(s.Value)
	t := s.Lhs[0].Typ
	switch s.Op {
	case "&^=":
		return fmt.Sprintf("%s &= ~(%s)", place, val)
	case "/=":
		if t.Signed() {
			return fmt.Sprintf("%s = vg::sdiv<%s>(%s, %s)", place, g.typ(t), place, val)
		}
	case "%=":
		if t.Signed() {
			return fmt.Sprintf("%s = vg::srem<%s>(%s, %s)", place, g.typ(t), place, val)
		}
	}
	return fmt.Sprintf("%s %s %s", place, s.Op, val)
}

// inlineStmt renders a loop init or post statement with no
// indentation and no terminator.
func (g *gen) inlineStmt(s *vegoc.Stmt) string {
	switch s.K {
	case "var_decl":
		if s.Value != nil {
			return fmt.Sprintf("%s %s = %s", g.typ(s.TypeRef), ident(s.Name), g.expr(s.Value))
		}
		return fmt.Sprintf("%s %s{}", g.typ(s.TypeRef), ident(s.Name))
	case "define":
		if len(s.Names) != 1 {
			fatal("two-value define in loop header")
		}
		return fmt.Sprintf("%s %s = %s", g.typ(s.DeclaredTypes[0]), ident(s.Names[0]), g.expr(s.Value))
	case "assign":
		if len(s.Lhs) != 1 {
			fatal("two-value assign in loop header")
		}
		return fmt.Sprintf("%s = %s", g.expr(s.Lhs[0]), g.expr(s.Value))
	case "op_assign":
		return g.opAssign(s, g.expr(s.Lhs[0]))
	}
	fatal("unsupported loop header statement", s.K)
	return ""
}

// emitRange lowers a range statement to an index loop. The Vego
// engine has none, but the form stays supported for completeness.
// The operand evaluates once into a copy, and a hidden counter
// drives the loop, so body writes to the user variables cannot
// change the iteration.
func (g *gen) emitRange(s *vegoc.Stmt, depth int) {
	over := g.newTmp()
	counter := g.newTmp()
	g.indent(depth)
	g.wf("{\n")
	g.indent(depth + 1)
	g.wf("auto %s = %s;\n", over, g.expr(s.Value))
	limit := over
	switch s.Value.Typ.K {
	case vegoc.KSlice:
		limit = over + ".len"
	case vegoc.KArray:
		limit = g.expr(s.Value.Typ.ALen)
	}
	g.indent(depth + 1)
	g.wf("for (int64_t %s = 0; %s < %s; %s++) {\n", counter, counter, limit, counter)
	if s.IdxName != "" && s.IdxName != "_" {
		g.indent(depth + 2)
		g.wf("int64_t %s = %s;\n", ident(s.IdxName), counter)
	}
	if s.ValName != "" && s.ValName != "_" {
		elem := s.Value.Typ.Elem
		iexpr := &vegoc.Expr{K: "index",
			X:     &vegoc.Expr{K: "ident", Name: over, Typ: s.Value.Typ},
			Index: &vegoc.Expr{K: "ident", Name: counter, Typ: vegoc.TInt}, Typ: elem}
		g.indent(depth + 2)
		g.wf("%s %s = %s;\n", g.typ(elem), ident(s.ValName), g.expr(iexpr))
	}
	g.body(s.Body, depth+2)
	g.indent(depth + 1)
	g.wf("}\n")
	g.indent(depth)
	g.wf("}\n")
}

// narrow reports whether a type needs a cast back after arithmetic
// to defeat C++ integer promotion.
func narrow(t *vegoc.Type) bool {
	switch t.K {
	case vegoc.KU8, vegoc.KU16, vegoc.KU32, vegoc.KI32:
		return true
	}
	return false
}

func (g *gen) expr(e *vegoc.Expr) string {
	switch e.K {
	case "int", "char":
		return g.intLiteral(e)
	case "str":
		return "vg::lit(\"" + cppEscape(e.Value) + "\")"
	case "bool":
		if e.BoolVal {
			return "true"
		}
		return "false"
	case "ident":
		if e.Name == "nil" {
			return g.typ(e.Typ) + "{}"
		}
		return ident(e.Name)
	case "field":
		return g.expr(e.X) + "." + ident(e.Name)
	case "index":
		// The base and the index are unsequenced in C++; pin them
		// in Go's order when a side effect can be observed. For an
		// addressable base, the lambda returns decltype(auto) so
		// an element place stays assignable. For an array-typed
		// temporary the element reference would dangle past the
		// lambda, so the element returns by value.
		if (vegoc.Impure(e.X) && !constish(e.Index)) || (vegoc.Impure(e.Index) && !constish(e.X)) {
			spec := " -> decltype(auto)"
			if e.X.Typ.K == vegoc.KArray && !addressable(e.X) {
				spec = ""
			}
			hx, hi := g.newTmp(), g.newTmp()
			inner := &vegoc.Expr{K: "index", Typ: e.Typ,
				X:     &vegoc.Expr{K: "ident", Name: hx, Typ: e.X.Typ},
				Index: &vegoc.Expr{K: "ident", Name: hi, Typ: e.Index.Typ}}
			return fmt.Sprintf("([&]()%s { auto&& %s = %s; auto %s = %s; return %s; }())",
				spec, hx, g.expr(e.X), hi, g.expr(e.Index), g.expr(inner))
		}
		switch e.X.Typ.K {
		case vegoc.KSlice, vegoc.KStr:
			return g.expr(e.X) + "[" + g.expr(e.Index) + "]"
		case vegoc.KArray:
			return g.expr(e.X) + "[size_t(" + g.expr(e.Index) + ")]"
		}
		fatal("index of", e.X.Typ)
	case "slice_expr":
		if vegoc.Impure(e.X) || vegoc.Impure(e.Lo) || vegoc.Impure(e.Hi) {
			hx := g.newTmp()
			inner := &vegoc.Expr{K: "slice_expr", Typ: e.Typ,
				X: &vegoc.Expr{K: "ident", Name: hx, Typ: e.X.Typ}}
			inits := fmt.Sprintf("auto&& %s = %s;", hx, g.expr(e.X))
			for _, b := range []struct {
				src *vegoc.Expr
				dst **vegoc.Expr
			}{{e.Lo, &inner.Lo}, {e.Hi, &inner.Hi}} {
				if b.src == nil {
					continue
				}
				hb := g.newTmp()
				inits += fmt.Sprintf(" auto %s = %s;", hb, g.expr(b.src))
				*b.dst = &vegoc.Expr{K: "ident", Name: hb, Typ: b.src.Typ}
			}
			return fmt.Sprintf("([&]{ %s return %s; }())", inits, g.expr(inner))
		}
		x := g.expr(e.X)
		switch e.X.Typ.K {
		case vegoc.KSlice, vegoc.KStr:
			switch {
			case e.Lo == nil && e.Hi == nil:
				return x
			case e.Lo == nil:
				return x + ".head(" + g.expr(e.Hi) + ")"
			case e.Hi == nil:
				return x + ".tail(" + g.expr(e.Lo) + ")"
			default:
				return x + ".sub(" + g.expr(e.Lo) + ", " + g.expr(e.Hi) + ")"
			}
		case vegoc.KArray:
			lo := "0"
			if e.Lo != nil {
				lo = g.expr(e.Lo)
			}
			hi := g.expr(e.X.Typ.ALen)
			if e.Hi != nil {
				hi = g.expr(e.Hi)
			}
			return fmt.Sprintf("vg::arr_slice(%s, %s, %s)", x, lo, hi)
		}
		fatal("slice of", e.X.Typ)
	case "call":
		if h, ok := g.hoistArgs(e); ok {
			return h
		}
		return ident(e.Name) + "(" + strings.Join(g.callArgs(e.Name, e.Args), ", ") + ")"
	case "builtin":
		if h, ok := g.hoistArgs(e); ok {
			return h
		}
		return g.builtin(e)
	case "conv":
		if e.TypeRef.K == vegoc.KStr {
			return "vg::str_from_bytes(mem, " + g.expr(e.X) + ")"
		}
		if e.TypeRef.K == vegoc.KSlice {
			return "vg::bytes_from_str(mem, " + g.expr(e.X) + ")"
		}
		return g.typ(e.TypeRef) + "(" + g.expr(e.X) + ")"
	case "unary":
		switch e.Op {
		case "-":
			// Unsigned arithmetic keeps negation defined in every
			// context, constexpr included, and wraps like Go even
			// for the minimum value.
			if e.Typ.IsInteger() {
				return fmt.Sprintf("%s(0ULL - uint64_t(%s))", g.typ(e.Typ), g.expr(e.X))
			}
			return "(-" + g.expr(e.X) + ")"
		case "^":
			if narrow(e.Typ) {
				return g.typ(e.Typ) + "(~" + g.expr(e.X) + ")"
			}
			return "(~" + g.expr(e.X) + ")"
		case "!":
			return "(!" + g.expr(e.X) + ")"
		case "&":
			fatal("& outside a call argument")
		}
		fatal("unknown unary", e.Op)
	case "binary":
		return g.binary(e)
	case "composite":
		return g.composite(e)
	}
	fatal("unknown expression kind", e.K)
	return ""
}

// intLiteral renders an integer literal. A literal the checker
// typed as 64-bit always carries a suffix, so constant arithmetic
// runs at 64 bits instead of overflowing int. Narrow literals stay
// plain; the cast-backs around narrow arithmetic absorb promotion.
func (g *gen) intLiteral(e *vegoc.Expr) string {
	v, err := strconv.ParseUint(e.Value, 10, 64)
	if err != nil {
		fatal("bad integer literal", e.Value)
	}
	if e.Typ != nil {
		switch e.Typ.K {
		case vegoc.KU64:
			return e.Value + "ULL"
		case vegoc.KI64, vegoc.KInt:
			// The magnitude of MinInt64 under unary minus has no
			// signed spelling; convert from unsigned, which C++20
			// defines as modular.
			if v > 1<<63-1 {
				return "int64_t(" + e.Value + "ULL)"
			}
			return e.Value + "LL"
		case vegoc.KI32:
			if v > 1<<31-1 {
				return "int32_t(" + e.Value + "U)"
			}
		}
	}
	return e.Value
}

func (g *gen) builtin(e *vegoc.Expr) string {
	switch e.Name {
	case "len":
		return "vg::len(" + g.expr(e.Args[0]) + ")"
	case "cap":
		return g.expr(e.Args[0]) + ".cap"
	case "make":
		elem := g.typ(e.TypeRef.Elem)
		if len(e.Args) == 2 {
			return fmt.Sprintf("vg::make_cap<%s>(mem, %s, %s)", elem, g.expr(e.Args[0]), g.expr(e.Args[1]))
		}
		return fmt.Sprintf("vg::make<%s>(mem, %s)", elem, g.expr(e.Args[0]))
	case "append":
		if e.Spread {
			if e.Args[1].Typ.K == vegoc.KStr {
				return fmt.Sprintf("vg::append_str(mem, %s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
			}
			return fmt.Sprintf("vg::append_slice(mem, %s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
		}
		out := g.expr(e.Args[0])
		for _, a := range e.Args[1:] {
			out = fmt.Sprintf("vg::append(mem, %s, %s)", out, g.expr(a))
		}
		return out
	case "copy":
		if e.Args[1].Typ.K == vegoc.KStr {
			return fmt.Sprintf("vg::vcopy_str(%s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
		}
		return fmt.Sprintf("vg::vcopy(%s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
	case "min":
		return fmt.Sprintf("std::min<%s>(%s, %s)", g.typ(e.Typ), g.expr(e.Args[0]), g.expr(e.Args[1]))
	case "max":
		return fmt.Sprintf("std::max<%s>(%s, %s)", g.typ(e.Typ), g.expr(e.Args[0]), g.expr(e.Args[1]))
	}
	fatal("unknown builtin", e.Name)
	return ""
}

func isNil(e *vegoc.Expr) bool {
	return e.K == "ident" && e.Name == "nil"
}

// callArgs renders call arguments, with the memory context first
// when the callee allocates. A unary & argument binds the callee's
// reference parameter directly.
func (g *gen) callArgs(callee string, args []*vegoc.Expr) []string {
	var out []string
	if g.p.CalleeAllocates(callee) {
		out = append(out, "mem")
	}
	for _, a := range args {
		if a.K == "unary" && a.Op == "&" {
			out = append(out, g.expr(a.X))
			continue
		}
		out = append(out, g.expr(a))
	}
	return out
}

// hoistArgs pins call and builtin arguments into temporaries, in
// Go's left-to-right order, when C++'s unspecified argument order
// could be observed: one argument has a side effect and another
// non-constant argument exists. Borrow arguments (&x) bind the
// same place whenever they evaluate, so they stay inline.
func (g *gen) hoistArgs(e *vegoc.Expr) (string, bool) {
	// A pointer-typed argument lowers to a C++ reference. Copying
	// it into a temporary would copy the referent, so it must stay
	// inline; evaluating it has no side effects anyway.
	inlineArg := func(a *vegoc.Expr) bool {
		return (a.Typ != nil && a.Typ.K == vegoc.KPtr) || constish(a)
	}
	impure, others := 0, 0
	for _, a := range e.Args {
		if inlineArg(a) {
			continue
		}
		if vegoc.Impure(a) {
			impure++
		} else {
			others++
		}
	}
	if impure == 0 || impure+others < 2 {
		return "", false
	}
	clone := *e
	clone.Args = make([]*vegoc.Expr, len(e.Args))
	var inits []string
	for i, a := range e.Args {
		if inlineArg(a) {
			clone.Args[i] = a
			continue
		}
		h := g.newTmp()
		inits = append(inits, fmt.Sprintf("auto %s = %s;", h, g.expr(a)))
		clone.Args[i] = &vegoc.Expr{K: "ident", Name: h, Typ: a.Typ}
	}
	var body string
	if clone.K == "call" {
		body = ident(clone.Name) + "(" + strings.Join(g.callArgs(clone.Name, clone.Args), ", ") + ")"
	} else {
		body = g.builtin(&clone)
	}
	return fmt.Sprintf("([&]{ %s return %s; }())", strings.Join(inits, " "), body), true
}

func constish(e *vegoc.Expr) bool {
	return e.IsConst || isNil(e)
}

// addressable reports whether the expression names storage that
// outlives the full expression. Crossing a slice or string means
// heap storage; otherwise the chain must root in a variable.
func addressable(e *vegoc.Expr) bool {
	switch e.K {
	case "ident":
		return true
	case "field":
		if e.X.Typ.K == vegoc.KPtr {
			return true
		}
		return addressable(e.X)
	case "index", "slice_expr":
		if e.X.Typ.K == vegoc.KSlice || e.X.Typ.K == vegoc.KStr {
			return true
		}
		return addressable(e.X)
	}
	return false
}

func (g *gen) binary(e *vegoc.Expr) string {
	// C++ leaves binary operands unsequenced; Go is left to right.
	// Pin operands into ordered temporaries when a side effect can
	// make the difference observable, except for && and ||, which
	// C++ already sequences. The rebuilt expression re-dispatches,
	// so string and struct comparisons keep their helpers.
	if e.Op != "&&" && e.Op != "||" {
		if (vegoc.Impure(e.X) && !constish(e.Y)) || (vegoc.Impure(e.Y) && !constish(e.X)) {
			hx, hy := g.newTmp(), g.newTmp()
			inner := &vegoc.Expr{K: "binary", Op: e.Op, Typ: e.Typ,
				X: &vegoc.Expr{K: "ident", Name: hx, Typ: e.X.Typ},
				Y: &vegoc.Expr{K: "ident", Name: hy, Typ: e.Y.Typ}}
			return fmt.Sprintf("([&]{ auto %s = %s; auto %s = %s; return %s; }())",
				hx, g.expr(e.X), hy, g.expr(e.Y), g.expr(inner))
		}
	}
	if e.Op == "==" || e.Op == "!=" {
		if isNil(e.Y) && e.X.Typ.K == vegoc.KSlice {
			return "(" + g.expr(e.X) + ".p " + e.Op + " nullptr)"
		}
		if isNil(e.X) && e.Y.Typ.K == vegoc.KSlice {
			return "(" + g.expr(e.Y) + ".p " + e.Op + " nullptr)"
		}
	}
	if e.X.Typ.K == vegoc.KStr {
		x, y := g.expr(e.X), g.expr(e.Y)
		switch e.Op {
		case "==":
			return fmt.Sprintf("vg::streq(%s, %s)", x, y)
		case "!=":
			return fmt.Sprintf("(!vg::streq(%s, %s))", x, y)
		case "<", "<=", ">", ">=":
			return fmt.Sprintf("(vg::strcmp3(%s, %s) %s 0)", x, y, e.Op)
		}
	}
	x, y := g.expr(e.X), g.expr(e.Y)
	var body string
	switch e.Op {
	case "&&", "||", "==", "!=", "<", "<=", ">", ">=":
		return fmt.Sprintf("(%s %s %s)", x, e.Op, y)
	case "/":
		if e.Typ.Signed() {
			// Signed division overflow stays undefined even under
			// -fwrapv; Go defines MinInt / -1 as MinInt.
			return fmt.Sprintf("vg::sdiv<%s>(%s, %s)", g.typ(e.Typ), x, y)
		}
		body = fmt.Sprintf("%s / %s", x, y)
	case "%":
		if e.Typ.Signed() {
			return fmt.Sprintf("vg::srem<%s>(%s, %s)", g.typ(e.Typ), x, y)
		}
		body = fmt.Sprintf("%s %% %s", x, y)
	case "&^":
		body = fmt.Sprintf("%s & ~(%s)", x, y)
	case "+", "-", "*", "&", "|", "^", "<<", ">>":
		body = fmt.Sprintf("%s %s %s", x, e.Op, y)
	default:
		fatal("unknown binary op", e.Op)
	}
	if narrow(e.Typ) {
		return g.typ(e.Typ) + "(" + body + ")"
	}
	return "(" + body + ")"
}

func (g *gen) composite(e *vegoc.Expr) string {
	t := e.TypeRef
	switch t.K {
	case vegoc.KStruct:
		if len(e.Fields) == 0 {
			return ident(t.Name) + "{}"
		}
		var parts []string
		for _, f := range e.Fields {
			parts = append(parts, fmt.Sprintf("_c.%s = %s;", ident(f.Name), g.expr(f.Value)))
		}
		return fmt.Sprintf("([&]{ %s _c{}; %s return _c; }())", ident(t.Name), strings.Join(parts, " "))
	case vegoc.KSlice:
		var parts []string
		for _, el := range e.Elems {
			parts = append(parts, g.expr(el))
		}
		return fmt.Sprintf("vg::slice_of<%s>(mem, {%s})", g.typ(t.Elem), strings.Join(parts, ", "))
	case vegoc.KArray:
		var parts []string
		for _, el := range e.Elems {
			parts = append(parts, g.expr(el))
		}
		return fmt.Sprintf("%s{%s}", g.typ(t), strings.Join(parts, ", "))
	}
	fatal("composite of", t)
	return ""
}

// cppEscape escapes a string literal. Non-printable bytes use
// three-digit octal escapes, whose length is fixed, so a following
// digit cannot extend them the way a hex escape could.
func cppEscape(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString("\\\"")
		case c == '\\':
			b.WriteString("\\\\")
		case c < 32 || c > 126:
			fmt.Fprintf(&b, "\\%03o", c)
		default:
			b.WriteByte(c)
		}
	}
	return b.String()
}
