// Command json2zig converts the Vego JSON form into one Zig source file.
// The output imports the hand-written runtime vg.zig.
// That runtime supplies the Slice and Str value types, and the Go conversion and comparison helpers.
// Every function that allocates receives an explicit allocator as its first parameter, "mem".
// The output holds no global state.
//
// Usage:
//
//	json2zig [-o engine.zig] input.json
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"revera1/vegoc"
)

func fatal(args ...any) {
	fmt.Fprintln(os.Stderr, args...)
	os.Exit(1)
}

func main() {
	out := flag.String("o", "", "output file (default stdout)")
	flag.Parse()
	if flag.NArg() != 1 {
		fatal("usage: json2zig [-o engine.zig] input.json")
	}
	p, err := vegoc.LoadFile(flag.Arg(0))
	if err != nil {
		fatal(err)
	}
	g := &gen{p: p}
	src := g.file()
	if *out == "" {
		os.Stdout.WriteString(src)
		return
	}
	if err := os.WriteFile(*out, []byte(src), 0o644); err != nil {
		fatal(err)
	}
}

type gen struct {
	p    *vegoc.Program
	b    strings.Builder
	fn   *vegoc.FuncDecl
	tmp  int
	used map[string]bool
}

var zigKeywords = map[string]bool{
	"addrspace": true, "align": true, "allowzero": true, "and": true,
	"anyframe": true, "anytype": true, "asm": true, "async": true,
	"await": true, "break": true, "callconv": true, "catch": true,
	"comptime": true, "const": true, "continue": true, "defer": true,
	"else": true, "enum": true, "errdefer": true, "error": true,
	"export": true, "extern": true, "fn": true, "for": true, "if": true,
	"inline": true, "linksection": true, "noalias": true,
	"noinline": true, "nosuspend": true, "opaque": true, "or": true,
	"orelse": true, "packed": true, "pub": true, "resume": true,
	"return": true, "struct": true, "suspend": true, "switch": true,
	"test": true, "threadlocal": true, "try": true, "union": true,
	"unreachable": true, "usingnamespace": true, "var": true,
	"volatile": true, "while": true, "void": true, "bool": true,
	"type": true, "null": true, "undefined": true, "true": true,
	"false": true,
}

func ident(name string) string {
	if zigKeywords[name] {
		return "@\"" + name + "\""
	}
	return name
}

func (g *gen) file() string {
	tups := map[string][2]*vegoc.Type{}
	for _, f := range g.p.Funcs {
		if len(f.Results) == 2 {
			pair := [2]*vegoc.Type{f.Results[0], f.Results[1]}
			tups[vegoc.TupName(pair)] = pair
		}
	}
	g.wf("// Code generated by json2zig from the Vego JSON form. DO NOT EDIT.\n\n")
	g.wf("const vg = @import(\"vg.zig\");\n\n")
	var names []string
	for n := range tups {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		pair := tups[n]
		g.wf("pub const %s = struct { %s, %s };\n", n, g.typ(pair[0]), g.typ(pair[1]))
	}
	g.wf("\n")
	for _, d := range g.p.Consts {
		if d.Type != nil {
			g.wf("pub const %s: %s = %s;\n", ident(d.Name), g.typ(d.Type), g.expr(d.Value))
		} else {
			g.wf("pub const %s = %s;\n", ident(d.Name), g.expr(d.Value))
		}
	}
	g.wf("\n")
	for _, d := range g.p.Vars {
		g.wf("pub const %s: %s = %s;\n", ident(d.Name), g.typ(d.Inferred), g.expr(d.Value))
	}
	g.wf("\n")
	for _, s := range g.p.Types {
		g.wf("pub const %s = struct {\n", ident(s.Name))
		for _, f := range s.Fields {
			g.wf("    %s: %s = %s,\n", ident(f.Name), g.typ(f.Type), g.zero(f.Type))
		}
		g.wf("};\n\n")
	}
	for _, f := range g.p.Funcs {
		g.emitFunc(f)
	}
	return g.b.String()
}

func (g *gen) wf(format string, args ...any) {
	fmt.Fprintf(&g.b, format, args...)
}

func (g *gen) typ(t *vegoc.Type) string {
	switch t.K {
	case vegoc.KBool:
		return "bool"
	case vegoc.KU8:
		return "u8"
	case vegoc.KU16:
		return "u16"
	case vegoc.KU32:
		return "u32"
	case vegoc.KU64:
		return "u64"
	case vegoc.KI32:
		return "i32"
	case vegoc.KI64, vegoc.KInt:
		return "i64"
	case vegoc.KStr:
		return "vg.Str"
	case vegoc.KSlice:
		return "vg.Slice(" + g.typ(t.Elem) + ")"
	case vegoc.KArray:
		return "[" + g.expr(t.ALen) + "]" + g.typ(t.Elem)
	case vegoc.KStruct:
		return ident(t.Name)
	case vegoc.KPtr:
		return "*" + ident(t.Name)
	}
	fatal("cannot map type", t)
	return ""
}

func (g *gen) zero(t *vegoc.Type) string {
	switch t.K {
	case vegoc.KBool:
		return "false"
	case vegoc.KStr, vegoc.KSlice, vegoc.KStruct:
		return ".{}"
	case vegoc.KArray:
		return "@splat(" + g.zero(t.Elem) + ")"
	default:
		return "0"
	}
}

func (g *gen) emitFunc(f *vegoc.FuncDecl) {
	g.fn = f
	g.resetNames(f)
	var params []string
	if f.Allocates {
		params = append(params, "mem: vg.Allocator")
	}
	for _, pa := range f.Params {
		params = append(params, ident(pa.Name)+": "+g.typ(pa.Type))
	}
	ret := "void"
	switch len(f.Results) {
	case 1:
		ret = g.typ(f.Results[0])
	case 2:
		ret = vegoc.TupName([2]*vegoc.Type{f.Results[0], f.Results[1]})
	}
	if f.Allocates {
		ret = "vg.Allocator.Error!" + ret
	}
	g.wf("pub fn %s(%s) %s {\n", ident(f.Name), strings.Join(params, ", "), ret)
	for _, pa := range f.Params {
		if info := f.Info[pa.Name]; info != nil && !info.Used {
			g.wf("    _ = %s;\n", ident(pa.Name))
		}
	}
	g.body(f.Body, 1)
	g.wf("}\n\n")
	g.fn = nil
}

func (g *gen) indent(depth int) {
	for i := 0; i < depth; i++ {
		g.b.WriteString("    ")
	}
}

func (g *gen) body(body []*vegoc.Stmt, depth int) {
	for _, s := range body {
		g.stmt(s, depth)
	}
}

func (g *gen) declKw(name string) string {
	if info := g.fn.Info[name]; info != nil && info.Mutated {
		return "var"
	}
	return "const"
}

func (g *gen) declLine(depth int, name string, t *vegoc.Type, value string) {
	g.indent(depth)
	g.wf("%s %s: %s = %s;\n", g.declKw(name), ident(name), g.typ(t), value)
	if info := g.fn.Info[name]; info != nil && !info.Used {
		g.indent(depth)
		g.wf("_ = &%s;\n", ident(name))
	}
}

func (g *gen) stmt(s *vegoc.Stmt, depth int) {
	switch s.K {
	case "var_decl":
		val := g.zero(s.TypeRef)
		if s.Value != nil {
			val = g.expr(s.Value)
		}
		g.declLine(depth, s.Name, s.TypeRef, val)
	case "define":
		if len(s.Names) == 1 {
			g.declLine(depth, s.Names[0], s.DeclaredTypes[0], g.expr(s.Value))
			return
		}
		tmp := g.newTmp()
		g.indent(depth)
		g.wf("const %s = %s;\n", tmp, g.expr(s.Value))
		for i, n := range s.Names {
			if n == "_" {
				continue
			}
			g.declLine(depth, n, s.DeclaredTypes[i], fmt.Sprintf("%s[%d]", tmp, i))
		}
	case "assign":
		if len(s.Lhs) == 2 {
			tmp := g.newTmp()
			g.indent(depth)
			g.wf("{\n")
			g.indent(depth + 1)
			g.wf("const %s = %s;\n", tmp, g.expr(s.Value))
			for i, l := range s.Lhs {
				if l.K == "ident" && l.Name == "_" {
					continue
				}
				g.indent(depth + 1)
				g.wf("%s = %s[%d];\n", g.expr(l), tmp, i)
			}
			g.indent(depth)
			g.wf("}\n")
			return
		}
		g.indent(depth)
		l := s.Lhs[0]
		if l.K == "ident" && l.Name == "_" {
			g.wf("_ = %s;\n", g.expr(s.Value))
			return
		}
		g.wf("%s = %s;\n", g.expr(l), g.expr(s.Value))
	case "op_assign":
		if g.pinOpAssign(s) {
			place := g.newTmp()
			g.indent(depth)
			g.wf("{\n")
			g.indent(depth + 1)
			g.wf("const %s = &%s;\n", place, g.expr(s.Lhs[0]))
			g.indent(depth + 1)
			g.wf("%s;\n", g.opAssignPlace(s, place+".*"))
			g.indent(depth)
			g.wf("}\n")
			return
		}
		g.indent(depth)
		g.wf("%s;\n", g.opAssign(s))
	case "if":
		g.indent(depth)
		g.wf("if (%s) {\n", g.expr(s.Cond))
		g.body(s.Then, depth+1)
		g.indent(depth)
		if s.HasElse {
			g.wf("} else {\n")
			g.body(s.Else, depth+1)
			g.indent(depth)
		}
		g.wf("}\n")
	case "for":
		if s.Init == nil && s.Post == nil {
			g.indent(depth)
			cond := "true"
			if s.Cond != nil {
				cond = g.expr(s.Cond)
			}
			g.wf("while (%s) {\n", cond)
			g.body(s.Body, depth+1)
			g.indent(depth)
			g.wf("}\n")
			return
		}
		g.indent(depth)
		g.wf("{\n")
		if s.Init != nil {
			g.stmt(s.Init, depth+1)
		}
		cond := "true"
		if s.Cond != nil {
			cond = g.expr(s.Cond)
		}
		g.indent(depth + 1)
		if s.Post != nil {
			g.wf("while (%s) : (%s) {\n", cond, g.inlineStmt(s.Post))
		} else {
			g.wf("while (%s) {\n", cond)
		}
		g.body(s.Body, depth+2)
		g.indent(depth + 1)
		g.wf("}\n")
		g.indent(depth)
		g.wf("}\n")
	case "range":
		g.emitRange(s, depth)
	case "switch":
		g.indent(depth)
		g.wf("switch (%s) {\n", g.expr(s.Tag))
		for _, cs := range s.Cases {
			var vals []string
			for _, v := range cs.Values {
				vals = append(vals, g.expr(v))
			}
			g.indent(depth + 1)
			g.wf("%s => {\n", strings.Join(vals, ", "))
			g.body(cs.Body, depth+2)
			g.indent(depth + 1)
			g.wf("},\n")
		}
		g.indent(depth + 1)
		if s.HasDef {
			g.wf("else => {\n")
			g.body(s.Default, depth+2)
			g.indent(depth + 1)
			g.wf("},\n")
		} else {
			g.wf("else => {},\n")
		}
		g.indent(depth)
		g.wf("}\n")
	case "break":
		g.indent(depth)
		g.wf("break;\n")
	case "continue":
		g.indent(depth)
		g.wf("continue;\n")
	case "return":
		g.indent(depth)
		switch len(s.Values) {
		case 0:
			g.wf("return;\n")
		case 1:
			g.wf("return %s;\n", g.expr(s.Values[0]))
		default:
			g.wf("return .{ %s, %s };\n", g.expr(s.Values[0]), g.expr(s.Values[1]))
		}
	case "expr_stmt":
		g.indent(depth)
		if s.Value.Typ != nil {
			g.wf("_ = %s;\n", g.expr(s.Value))
		} else {
			g.wf("%s;\n", g.expr(s.Value))
		}
	case "block":
		g.indent(depth)
		g.wf("{\n")
		g.body(s.Body, depth+1)
		g.indent(depth)
		g.wf("}\n")
	default:
		fatal("unknown statement kind", s.K)
	}
}

// emitRange lowers a range statement to an index loop.
// The Vego engine has no range statement, but the form stays supported for completeness.
// The operand evaluates once, and a hidden counter drives the loop.
// A write to the user variables in the body therefore cannot change the iteration.
func (g *gen) emitRange(s *vegoc.Stmt, depth int) {
	over := g.newTmp()
	counter := g.newTmp()
	g.indent(depth)
	g.wf("{\n")
	g.indent(depth + 1)
	g.wf("const %s = %s;\n", over, g.expr(s.Value))
	limit := over
	switch s.Value.Typ.K {
	case vegoc.KSlice:
		limit = over + ".len"
	case vegoc.KArray:
		limit = g.expr(s.Value.Typ.ALen)
	}
	g.indent(depth + 1)
	g.wf("var %s: i64 = 0;\n", counter)
	g.indent(depth + 1)
	g.wf("while (%s < %s) : (%s += 1) {\n", counter, limit, counter)
	if s.IdxName != "" && s.IdxName != "_" {
		g.declLine(depth+2, s.IdxName, vegoc.TInt, counter)
	}
	if s.ValName != "" && s.ValName != "_" {
		read := &vegoc.Expr{K: "index", Typ: s.Value.Typ.Elem,
			X:     &vegoc.Expr{K: "ident", Name: over, Typ: s.Value.Typ},
			Index: &vegoc.Expr{K: "ident", Name: counter, Typ: vegoc.TInt}}
		g.declLine(depth+2, s.ValName, s.Value.Typ.Elem, g.expr(read))
	}
	g.body(s.Body, depth+2)
	g.indent(depth + 1)
	g.wf("}\n")
	g.indent(depth)
	g.wf("}\n")
}

func (g *gen) newTmp() string {
	if g.used == nil {
		g.resetNames(g.fn)
	}
	for {
		g.tmp++
		name := fmt.Sprintf("_t%d", g.tmp)
		if !g.used[name] {
			g.used[name] = true
			return name
		}
	}
}

func (g *gen) resetNames(f *vegoc.FuncDecl) {
	g.tmp = 0
	g.used = map[string]bool{}
	reserve := func(name string) { g.used[ident(name)] = true }
	for _, d := range g.p.Consts {
		reserve(d.Name)
	}
	for _, d := range g.p.Vars {
		reserve(d.Name)
	}
	for _, d := range g.p.Types {
		reserve(d.Name)
	}
	for _, d := range g.p.Funcs {
		reserve(d.Name)
	}
	if f != nil {
		for name := range f.Info {
			reserve(name)
		}
	}
}

// inlineStmt renders a loop post statement as a Zig continue expression.
func (g *gen) inlineStmt(s *vegoc.Stmt) string {
	switch s.K {
	case "assign":
		if len(s.Lhs) != 1 {
			fatal("two-value assign in loop post")
		}
		return g.expr(s.Lhs[0]) + " = " + g.expr(s.Value)
	case "op_assign":
		if g.pinOpAssign(s) {
			place := g.newTmp()
			return fmt.Sprintf("{ const %s = &%s; %s; }",
				place, g.expr(s.Lhs[0]), g.opAssignPlace(s, place+".*"))
		}
		return g.opAssign(s)
	case "expr_stmt":
		return g.expr(s.Value)
	}
	fatal("unsupported loop post statement", s.K)
	return ""
}

func (g *gen) opAssign(s *vegoc.Stmt) string {
	return g.opAssignPlace(s, g.expr(s.Lhs[0]))
}

func (g *gen) pinOpAssign(s *vegoc.Stmt) bool {
	return (s.Op == "/=" || s.Op == "%=") && vegoc.Impure(s.Lhs[0])
}

func (g *gen) opAssignPlace(s *vegoc.Stmt, lhs string) string {
	val := g.expr(s.Value)
	switch s.Op {
	case "+=", "-=", "*=":
		return lhs + " " + s.Op[:1] + "%= " + val
	case "/=":
		return fmt.Sprintf("%s = vg.divT(%s, %s)", lhs, lhs, val)
	case "%=":
		return fmt.Sprintf("%s = vg.remT(%s, %s)", lhs, lhs, val)
	case "|=", "&=", "^=":
		return fmt.Sprintf("%s %s %s", lhs, s.Op, val)
	case "<<=", ">>=":
		if s.Value.IsConst {
			return fmt.Sprintf("%s %s %s", lhs, s.Op, val)
		}
		return fmt.Sprintf("%s %s @intCast(%s)", lhs, s.Op, val)
	case "&^=":
		return fmt.Sprintf("%s &= ~(%s)", lhs, val)
	}
	fatal("unknown op-assign", s.Op)
	return ""
}

// idx renders an index or bound expression.
// An unsigned 64-bit value cannot coerce to the i64 that the runtime takes.
// @intCast keeps the abort-on-huge behavior that the bounds check of Go gives.
func (g *gen) idx(e *vegoc.Expr) string {
	if e.Typ.K == vegoc.KU64 {
		return "@intCast(" + g.expr(e) + ")"
	}
	return g.expr(e)
}

func (g *gen) expr(e *vegoc.Expr) string {
	switch e.K {
	case "int", "char":
		return e.Value
	case "str":
		return "vg.lit(\"" + zigEscape(e.Value) + "\")"
	case "bool":
		if e.BoolVal {
			return "true"
		}
		return "false"
	case "ident":
		if e.Name == "nil" {
			return "@as(" + g.typ(e.Typ) + ", .{})"
		}
		return ident(e.Name)
	case "field":
		return g.expr(e.X) + "." + ident(e.Name)
	case "index":
		switch e.X.Typ.K {
		case vegoc.KSlice:
			return g.expr(e.X) + ".at(" + g.idx(e.Index) + ").*"
		case vegoc.KStr:
			return g.expr(e.X) + ".byte(" + g.idx(e.Index) + ")"
		case vegoc.KArray:
			if e.Index.IsConst {
				return g.expr(e.X) + "[" + g.expr(e.Index) + "]"
			}
			return g.expr(e.X) + "[@intCast(" + g.expr(e.Index) + ")]"
		}
		fatal("index of", e.X.Typ)
	case "slice_expr":
		x := g.expr(e.X)
		switch e.X.Typ.K {
		case vegoc.KSlice, vegoc.KStr:
			switch {
			case e.Lo == nil && e.Hi == nil:
				return x
			case e.Lo == nil:
				return x + ".head(" + g.idx(e.Hi) + ")"
			case e.Hi == nil:
				return x + ".tail(" + g.idx(e.Lo) + ")"
			default:
				return x + ".sub(" + g.idx(e.Lo) + ", " + g.idx(e.Hi) + ")"
			}
		case vegoc.KArray:
			lo := "0"
			if e.Lo != nil {
				lo = g.idx(e.Lo)
			}
			hi := g.expr(e.X.Typ.ALen)
			if e.Hi != nil {
				hi = g.idx(e.Hi)
			}
			return fmt.Sprintf("vg.arrSlice(%s, &%s, %s, %s)", g.typ(e.X.Typ.Elem), x, lo, hi)
		}
		fatal("slice of", e.X.Typ)
	case "call":
		var args []string
		prefix := ""
		if g.p.CalleeAllocates(e.Name) {
			args = append(args, "mem")
			prefix = "try "
		}
		for _, a := range e.Args {
			args = append(args, g.expr(a))
		}
		return prefix + ident(e.Name) + "(" + strings.Join(args, ", ") + ")"
	case "builtin":
		return g.builtin(e)
	case "conv":
		if e.TypeRef.K == vegoc.KStr {
			return "try vg.strFromBytes(mem, " + g.expr(e.X) + ")"
		}
		if e.TypeRef.K == vegoc.KSlice {
			return "try vg.bytesFromStr(mem, " + g.expr(e.X) + ")"
		}
		return fmt.Sprintf("vg.cv(%s, %s)", g.typ(e.TypeRef), g.expr(e.X))
	case "unary":
		switch e.Op {
		case "-":
			return "(-%" + g.expr(e.X) + ")"
		case "^":
			return "(~" + g.expr(e.X) + ")"
		case "!":
			return "(!" + g.expr(e.X) + ")"
		case "&":
			return "&" + g.expr(e.X)
		}
		fatal("unknown unary", e.Op)
	case "binary":
		return g.binary(e)
	case "composite":
		return g.composite(e)
	}
	fatal("unknown expression kind", e.K)
	return ""
}

func (g *gen) builtin(e *vegoc.Expr) string {
	switch e.Name {
	case "len":
		switch e.Args[0].Typ.K {
		case vegoc.KStr, vegoc.KSlice:
			return g.expr(e.Args[0]) + ".len"
		case vegoc.KArray:
			return "@as(i64, " + g.expr(e.Args[0].Typ.ALen) + ")"
		}
		fatal("len of", e.Args[0].Typ)
	case "cap":
		return g.expr(e.Args[0]) + ".cap"
	case "make":
		elem := g.typ(e.TypeRef.Elem)
		if len(e.Args) == 2 {
			return fmt.Sprintf("try vg.makeCap(mem, %s, %s, %s)", elem, g.idx(e.Args[0]), g.idx(e.Args[1]))
		}
		return fmt.Sprintf("try vg.make(mem, %s, %s)", elem, g.idx(e.Args[0]))
	case "append":
		st := e.Args[0].Typ
		elem := g.typ(st.Elem)
		if e.Spread {
			if e.Args[1].Typ.K == vegoc.KStr {
				return fmt.Sprintf("try vg.appendStr(mem, %s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
			}
			return fmt.Sprintf("try vg.appendSlice(mem, %s, %s, %s)", elem, g.expr(e.Args[0]), g.expr(e.Args[1]))
		}
		out := g.expr(e.Args[0])
		for _, a := range e.Args[1:] {
			out = fmt.Sprintf("try vg.append(mem, %s, %s, %s)", elem, out, g.expr(a))
		}
		return out
	case "copy":
		if e.Args[1].Typ.K == vegoc.KStr {
			return fmt.Sprintf("vg.copyStr(%s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
		}
		return fmt.Sprintf("vg.copy(%s, %s, %s)", g.typ(e.Args[0].Typ.Elem), g.expr(e.Args[0]), g.expr(e.Args[1]))
	case "min":
		return fmt.Sprintf("@min(%s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
	case "max":
		return fmt.Sprintf("@max(%s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
	}
	fatal("unknown builtin", e.Name)
	return ""
}

func isNil(e *vegoc.Expr) bool {
	return e.K == "ident" && e.Name == "nil"
}

func (g *gen) binary(e *vegoc.Expr) string {
	// Slice-to-nil comparisons test the data pointer, like Go.
	if e.Op == "==" || e.Op == "!=" {
		if isNil(e.Y) && e.X.Typ.K == vegoc.KSlice {
			return "(" + g.expr(e.X) + ".p " + e.Op + " null)"
		}
		if isNil(e.X) && e.Y.Typ.K == vegoc.KSlice {
			return "(" + g.expr(e.Y) + ".p " + e.Op + " null)"
		}
	}
	if e.X.Typ.K == vegoc.KStr {
		x, y := g.expr(e.X), g.expr(e.Y)
		switch e.Op {
		case "==":
			return fmt.Sprintf("vg.streq(%s, %s)", x, y)
		case "!=":
			return fmt.Sprintf("(!vg.streq(%s, %s))", x, y)
		case "<", "<=", ">", ">=":
			return fmt.Sprintf("(vg.strcmp3(%s, %s) %s 0)", x, y, e.Op)
		}
	}
	if e.X.Typ.K == vegoc.KStruct {
		x, y := g.expr(e.X), g.expr(e.Y)
		switch e.Op {
		case "==":
			return fmt.Sprintf("vg.structEq(%s, %s)", x, y)
		case "!=":
			return fmt.Sprintf("(!vg.structEq(%s, %s))", x, y)
		}
	}
	x, y := g.expr(e.X), g.expr(e.Y)
	// A constant left operand would reach a division helper as comptime_int.
	// It could also make the @intCast of a shift lose its result type.
	// The operand therefore takes its concrete type here.
	switch e.Op {
	case "/", "%", "<<", ">>":
		if e.X.IsConst && !e.Y.IsConst {
			x = fmt.Sprintf("@as(%s, %s)", g.typ(e.X.Typ), x)
		}
	}
	switch e.Op {
	case "+", "-", "*":
		return fmt.Sprintf("(%s %s%% %s)", x, e.Op, y)
	case "/":
		return fmt.Sprintf("vg.divT(%s, %s)", x, y)
	case "%":
		return fmt.Sprintf("vg.remT(%s, %s)", x, y)
	case "&&":
		return fmt.Sprintf("(%s and %s)", x, y)
	case "||":
		return fmt.Sprintf("(%s or %s)", x, y)
	case "&^":
		return fmt.Sprintf("(%s & ~(%s))", x, y)
	case "&", "|", "^", "==", "!=", "<", "<=", ">", ">=":
		return fmt.Sprintf("(%s %s %s)", x, e.Op, y)
	case "<<", ">>":
		if e.Y.IsConst {
			return fmt.Sprintf("(%s %s %s)", x, e.Op, y)
		}
		return fmt.Sprintf("(%s %s @intCast(%s))", x, e.Op, y)
	}
	fatal("unknown binary op", e.Op)
	return ""
}

func (g *gen) composite(e *vegoc.Expr) string {
	t := e.TypeRef
	switch t.K {
	case vegoc.KStruct:
		if len(e.Fields) == 0 {
			return ".{}"
		}
		var parts []string
		for _, f := range e.Fields {
			parts = append(parts, "."+ident(f.Name)+" = "+g.expr(f.Value))
		}
		return ident(t.Name) + "{ " + strings.Join(parts, ", ") + " }"
	case vegoc.KSlice:
		var parts []string
		for _, el := range e.Elems {
			parts = append(parts, g.expr(el))
		}
		elem := g.typ(t.Elem)
		return fmt.Sprintf("try vg.sliceOf(mem, %s, &[_]%s{ %s })", elem, elem, strings.Join(parts, ", "))
	case vegoc.KArray:
		var parts []string
		for _, el := range e.Elems {
			parts = append(parts, g.expr(el))
		}
		// Go zero-fills omitted trailing elements.
		if n, ok := g.p.ArrayLen(t); ok {
			for int64(len(parts)) < n {
				parts = append(parts, g.zero(t.Elem))
			}
		}
		return fmt.Sprintf("[%s]%s{ %s }", g.expr(t.ALen), g.typ(t.Elem), strings.Join(parts, ", "))
	}
	fatal("composite of", t)
	return ""
}

func zigEscape(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString("\\\"")
		case c == '\\':
			b.WriteString("\\\\")
		case c == '\n':
			b.WriteString("\\n")
		case c < 32 || c > 126:
			fmt.Fprintf(&b, "\\x%02x", c)
		default:
			b.WriteByte(c)
		}
	}
	return b.String()
}
