// Code generated by json2zig from the Vego JSON form. DO NOT EDIT.

const vg = @import("vg.zig");

pub const Tup_i32_i32 = struct { i32, i32 };
pub const Tup_i64_i64 = struct { i64, i64 };

pub const minI64 = (-%9223372036854775808);


pub const Counter = struct {
    n: i64 = 0,
    log: vg.Slice(i32) = .{},
};

pub const Tagged = struct {
    Tags: [2]vg.Str = @splat(.{}),
    N: i32 = 0,
};

pub fn bump(mem: vg.Allocator, c: *Counter, tag: i32) i64 {
    c.n +%= 1;
    c.log = vg.append(mem, i32, c.log, tag);
    return vg.cv(i64, tag);
}

pub fn logCode(c: *Counter) i64 {
    var v: i64 = vg.cv(i64, 0);
    {
        var i: i64 = 0;
        while ((i < c.log.len)) : (i +%= 1) {
            v = ((v *% 10) +% vg.cv(i64, c.log.at(i).*));
        }
    }
    return ((v *% 100) +% vg.cv(i64, c.n));
}

pub fn DivMod(a: i64, b: i64) Tup_i64_i64 {
    return .{ vg.divT(a, b), vg.remT(a, b) };
}

pub fn DivMod32(a: i32, b: i32) Tup_i32_i32 {
    return .{ vg.divT(a, b), vg.remT(a, b) };
}

pub fn BytesProbe(mem: vg.Allocator, s: vg.Str) i64 {
    const b: vg.Slice(u8) = vg.bytesFromStr(mem, s);
    if ((b.len > 0)) {
        b.at(0).* = 88;
    }
    var t: i64 = vg.cv(i64, 0);
    {
        var i: i64 = 0;
        while ((i < b.len)) : (i +%= 1) {
            t = ((t *% 31) +% vg.cv(i64, b.at(i).*));
        }
    }
    return t;
}

pub fn sliceFrom(mem: vg.Allocator, c: *Counter, n: i64) vg.Slice(i32) {
    c.n +%= 1;
    const out: vg.Slice(i32) = vg.make(mem, i32, n);
    {
        var i: i64 = 0;
        while ((i < n)) : (i +%= 1) {
            out.at(i).* = vg.cv(i32, (i +% 1));
        }
    }
    return out;
}

pub fn RangeProbe(mem: vg.Allocator, c: *Counter) i64 {
    var t: i64 = vg.cv(i64, 0);
    {
        const _t1 = sliceFrom(mem, c, 4);
        var _t2: i64 = 0;
        while (_t2 < _t1.len) : (_t2 += 1) {
            var i: i64 = _t2;
            const v: i32 = _t1.at(_t2).*;
            t +%= (vg.cv(i64, i) *% vg.cv(i64, v));
            i = 100;
        }
    }
    return ((t *% 10) +% vg.cv(i64, c.n));
}

pub fn RangeValProbe(xs: vg.Slice(i32)) i64 {
    var t: i64 = vg.cv(i64, 0);
    {
        const _t1 = xs;
        var _t2: i64 = 0;
        while (_t2 < _t1.len) : (_t2 += 1) {
            var v: i32 = _t1.at(_t2).*;
            v = (v +% 1);
            t +%= vg.cv(i64, v);
        }
    }
    {
        var i: i64 = 0;
        while ((i < xs.len)) : (i +%= 1) {
            t +%= (vg.cv(i64, xs.at(i).*) *% 100);
        }
    }
    return t;
}

pub fn RangeIntProbe(n: i64) i64 {
    var t: i64 = vg.cv(i64, 0);
    {
        const _t1 = n;
        var _t2: i64 = 0;
        while (_t2 < _t1) : (_t2 += 1) {
            const i: i64 = _t2;
            t = ((t *% 2) +% vg.cv(i64, i));
        }
    }
    return t;
}

pub fn PartialArray() i64 {
    const a: [5]i64 = [5]i64{ 7, 9, 0, 0, 0 };
    const names: [3]vg.Str = [3]vg.Str{ vg.lit("a"), .{}, .{} };
    var t: i64 = vg.cv(i64, 0);
    {
        var i: i64 = 0;
        while ((i < 5)) : (i +%= 1) {
            t = ((t *% 10) +% a[@intCast(i)]);
        }
    }
    return (((t *% 10) +% vg.cv(i64, names[1].len)) +% vg.cv(i64, names[0].len));
}

pub fn TaggedEq(a: Tagged, b: Tagged) bool {
    return vg.structEq(a, b);
}

pub fn three(a: i64, b: i64, x: i64) i64 {
    return (((a *% 100) +% (b *% 10)) +% x);
}

pub fn OrderArgs(mem: vg.Allocator, c: *Counter) i64 {
    return (three(bump(mem, c, 1), bump(mem, c, 2), bump(mem, c, 3)) +% logCode(c));
}

pub fn OrderBinary(mem: vg.Allocator, c: *Counter) i64 {
    const v: i64 = (bump(mem, c, 4) -% (2 *% bump(mem, c, 5)));
    return ((v *% 10000) +% logCode(c));
}

pub fn OrderIndex(mem: vg.Allocator, c: *Counter) i64 {
    const s: vg.Slice(i32) = sliceFrom(mem, c, 6);
    const v: i64 = vg.cv(i64, s.at(bump(mem, c, 2)).*);
    return ((v *% 10000) +% logCode(c));
}

pub fn SpareProbe(mem: vg.Allocator) i64 {
    var s: vg.Slice(i64) = vg.makeCap(mem, i64, 0, 4);
    s = vg.append(mem, i64, s, 5);
    s = s.head(4);
    var t: i64 = vg.cv(i64, 0);
    {
        var i: i64 = 0;
        while ((i < s.len)) : (i +%= 1) {
            t = (((t *% 10) +% s.at(i).*) +% 1);
        }
    }
    var g: vg.Slice(i64) = vg.makeCap(mem, i64, 0, 2);
    g = vg.append(mem, i64, g, 1);
    g = vg.append(mem, i64, g, 2);
    g = vg.append(mem, i64, g, 3);
    if ((g.cap >= 4)) {
        g = g.head(4);
    }
    {
        var i_2: i64 = 0;
        while ((i_2 < 4)) : (i_2 +%= 1) {
            t = (((t *% 10) +% g.at(i_2).*) +% 1);
        }
    }
    return t;
}

pub fn NilProbe(mem: vg.Allocator) i64 {
    var s: vg.Slice(i32) = .{};
    var t: i64 = vg.cv(i64, 0);
    if ((s.p == null)) {
        t +%= 1;
    }
    const s2: vg.Slice(i32) = vg.make(mem, i32, 0);
    if ((s2.p != null)) {
        t +%= 2;
    }
    s = vg.append(mem, i32, s, 5);
    if ((s.p != null)) {
        t +%= 4;
    }
    return t;
}

pub fn WrapProbe(a: i64, b: i64) i64 {
    return (((a *% b) +% a) -% b);
}

pub fn Narrow32(a: i32, b: i32) i32 {
    return (((a *% b) -% vg.divT(a, b)) +% vg.remT(a, b));
}

pub fn WrapU8(a: u8, b: u8) u8 {
    return ((a -% b) *% 3);
}

pub fn AndNotProbe(a: u32, b: u32) u32 {
    var a_v: u32 = a;
    a_v &= ~(b);
    return (a_v & ~((b >> 1)));
}

pub fn ShiftProbe(x: u64, n: i64) u64 {
    return ((x << @intCast(n)) >> @intCast(vg.divT(n, 2)));
}

pub fn ConvProbe(x: i64) u64 {
    return (vg.cv(u64, vg.cv(u8, x)) +% (vg.cv(u64, vg.cv(u32, vg.cv(i32, x))) *% 1000));
}

pub fn SubWrite(mem: vg.Allocator, n: i64) i64 {
    const s: vg.Slice(i64) = vg.make(mem, i64, n);
    s.tail(1).at(0).* = 7;
    s.tail(1).tail(1).at(0).* = 9;
    var t: i64 = vg.cv(i64, 0);
    {
        var i: i64 = 0;
        while ((i < s.len)) : (i +%= 1) {
            t = ((t *% 10) +% s.at(i).*);
        }
    }
    return t;
}

pub fn AndNotOrder(mem: vg.Allocator, c: *Counter) i64 {
    const s: vg.Slice(u64) = vg.make(mem, u64, 8);
    s.at(3).* = 255;
    s.at((bump(mem, c, 1) +% 2)).* &= ~((vg.cv(u64, bump(mem, c, 2)) +% 15));
    return ((vg.cv(i64, s.at(3).*) *% 100000) +% logCode(c));
}

pub fn ZeroArray() i64 {
    var a: [0]i32 = @splat(0);
    var t: i64 = vg.cv(i64, 0);
    if ((vg.arrSlice(i32, &a, 0, 0).p != null)) {
        t +%= 1;
    }
    t = ((t *% 10) +% vg.cv(i64, vg.arrSlice(i32, &a, 0, 0).len));
    return t;
}

pub fn MakeU64(mem: vg.Allocator, n: u64) i64 {
    const s: vg.Slice(i32) = vg.make(mem, i32, @intCast(n));
    return vg.cv(i64, s.len);
}

pub fn mkTriple(x: i64) [3]i64 {
    var a: [3]i64 = @splat(0);
    a[0] = x;
    a[1] = (x +% 1);
    a[2] = (x +% 2);
    return a;
}

pub fn PickArray(mem: vg.Allocator, c: *Counter) i64 {
    const v: i64 = mkTriple(40)[@intCast(bump(mem, c, 2))];
    return ((v *% 10000) +% logCode(c));
}

