// Package rust prints the Vego JSON form as one Rust source file.
// The output imports the hand-written runtime vg.rs.
// That runtime supplies the Slice and Str value types, the Arena allocator, and the Go comparison helpers.
// Every function that allocates receives an Arena reference as its first parameter, "mem".
// The output holds no global state.
package rust

import (
	"errors"
	"fmt"
	"math/big"
	"sort"
	"strings"

	"github.com/oneregex/revera/vego/compiler"
)

// failure carries a printer error out of the recursive emitters.
type failure string

func fatal(args ...any) {
	panic(failure(strings.TrimSuffix(fmt.Sprintln(args...), "\n")))
}

// catch turns a failure raised by fatal into the error result of an Emit call.
// Any other panic is a bug and keeps propagating.
func catch(err *error) {
	if r := recover(); r != nil {
		f, ok := r.(failure)
		if !ok {
			panic(r)
		}
		*err = errors.New(string(f))
	}
}

// Emit prints the program as one Rust source file.
func Emit(p *compiler.Program) (src string, err error) {
	defer catch(&err)
	g := &gen{p: p}
	return g.file(), nil
}

type loopCtx struct {
	brk  string
	cont string
}

type gen struct {
	p     *compiler.Program
	b     strings.Builder
	fn    *compiler.FuncDecl
	tmp   int
	used  map[string]bool
	loops []loopCtx
	eqs   map[string]bool
}

// Rust keywords that can hide behind a raw identifier.
// The names that cannot are self, Self, super and crate, and the vegoc renamer already reserves them.
var rustKeywords = map[string]bool{
	"as": true, "break": true, "const": true, "continue": true,
	"dyn": true, "else": true, "enum": true, "extern": true,
	"false": true, "fn": true, "for": true, "if": true, "impl": true,
	"in": true, "let": true, "loop": true, "match": true, "mod": true,
	"move": true, "mut": true, "pub": true, "ref": true,
	"return": true, "static": true, "struct": true, "trait": true,
	"true": true, "type": true, "unsafe": true, "use": true,
	"where": true, "while": true, "async": true, "await": true,
	"abstract": true, "become": true, "box": true, "do": true,
	"final": true, "macro": true,
	"override": true, "priv": true, "typeof": true, "unsized": true,
	"virtual": true, "yield": true, "gen": true, "try": true,
}

const rustInternalPrefix = "vego_"

func ident(name string) string {
	if strings.HasPrefix(name, rustInternalPrefix) {
		return rustInternalPrefix + name
	}
	if rustKeywords[name] {
		return "r#" + name
	}
	return name
}

func structEqName(name string) string {
	return rustInternalPrefix + "eq_" + name
}

func (g *gen) file() string {
	g.wf("// Code generated by vegoc from the Vego JSON form. DO NOT EDIT.\n\n")
	g.wf("#![forbid(unsafe_code)]\n")
	g.wf("#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]\n")
	g.wf("#![allow(unused_parens, unused_mut, unused_variables, dead_code)]\n")
	g.wf("#![allow(unreachable_code, unused_assignments)]\n\n")
	g.wf("use crate::vg;\n\n")
	for _, d := range g.p.Consts {
		g.wf("pub const %s: %s = %s;\n", ident(d.Name), g.typ(d.Inferred), g.expr(d.Value))
	}
	g.wf("\n")
	for _, d := range g.p.Vars {
		g.wf("pub static %s: %s = %s;\n", ident(d.Name), g.typ(d.Inferred), g.expr(d.Value))
	}
	g.wf("\n")
	for _, s := range g.p.Types {
		g.wf("#[derive(Clone, Copy)]\npub struct %s {\n", ident(s.Name))
		for _, f := range s.Fields {
			g.wf("    pub %s: %s,\n", ident(f.Name), g.typ(f.Type))
		}
		g.wf("}\n\n")
	}
	g.emitStructEqs()
	for _, f := range g.p.Funcs {
		g.emitFunc(f)
	}
	return g.b.String()
}

func (g *gen) wf(format string, args ...any) {
	fmt.Fprintf(&g.b, format, args...)
}

func (g *gen) typ(t *compiler.Type) string {
	switch t.K {
	case compiler.KBool:
		return "bool"
	case compiler.KU8:
		return "u8"
	case compiler.KU16:
		return "u16"
	case compiler.KU32:
		return "u32"
	case compiler.KU64:
		return "u64"
	case compiler.KI32:
		return "i32"
	case compiler.KI64, compiler.KInt:
		return "i64"
	case compiler.KStr:
		return "vg::Str"
	case compiler.KSlice:
		return "vg::Slice<" + g.typ(t.Elem) + ">"
	case compiler.KArray:
		return "[" + g.typ(t.Elem) + "; (" + g.constPlain(t.ALen) + ") as usize]"
	case compiler.KStruct:
		return ident(t.Name)
	case compiler.KPtr:
		return "&mut " + ident(t.Name)
	}
	fatal("cannot map type", t)
	return ""
}

// constPlain renders a compile-time length expression without literal suffixes, for array-length positions.
func (g *gen) constPlain(e *compiler.Expr) string {
	switch e.K {
	case "int", "char":
		return e.Value
	case "ident":
		return ident(e.Name)
	case "unary":
		return "-(" + g.constPlain(e.X) + ")"
	case "binary":
		return "(" + g.constPlain(e.X) + " " + e.Op + " " + g.constPlain(e.Y) + ")"
	}
	fatal("unsupported array length expression", e.K)
	return ""
}

// intLiteral renders an integer literal with its type suffix.
// A signed literal past the maximum of its type routes through the unsigned type.
// That case is the magnitude of MinInt under unary minus, and the `as` cast wraps like Go.
func intLiteral(e *compiler.Expr) string {
	t := e.Typ
	if t.Signed() {
		v := new(big.Int)
		v.SetString(e.Value, 10)
		max := new(big.Int).Lsh(big.NewInt(1), uint(t.Width()-1))
		max.Sub(max, big.NewInt(1))
		if v.Cmp(max) > 0 {
			u := litSuffix(&compiler.Type{K: unsignedKind(t)})
			return fmt.Sprintf("(%s%s as %s)", e.Value, u, litSuffix(t))
		}
	}
	return e.Value + litSuffix(t)
}

func unsignedKind(t *compiler.Type) compiler.TypeKind {
	switch t.K {
	case compiler.KI32:
		return compiler.KU32
	default:
		return compiler.KU64
	}
}

func litSuffix(t *compiler.Type) string {
	switch t.K {
	case compiler.KU8:
		return "u8"
	case compiler.KU16:
		return "u16"
	case compiler.KU32:
		return "u32"
	case compiler.KU64:
		return "u64"
	case compiler.KI32:
		return "i32"
	case compiler.KI64, compiler.KInt:
		return "i64"
	}
	fatal("no literal suffix for type", t)
	return ""
}

// Struct equality.
// Go compares structs field by field, and it compares string fields by content.
// The printer emits one function per struct type that appears as an operand of == or !=.

func (g *gen) emitStructEqs() {
	g.eqs = map[string]bool{}
	for _, f := range g.p.Funcs {
		compiler.WalkBody(f.Body, func(e *compiler.Expr) {
			if e.K == "binary" && (e.Op == "==" || e.Op == "!=") &&
				e.X.Typ != nil && e.X.Typ.K == compiler.KStruct {
				g.needEq(e.X.Typ.Name)
			}
		}, nil)
	}
	var names []string
	for n := range g.eqs {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		sd := g.p.StructMap[n]
		var parts []string
		for _, f := range sd.Fields {
			fx := "a." + ident(f.Name)
			fy := "b." + ident(f.Name)
			switch f.Type.K {
			case compiler.KStr:
				parts = append(parts, fmt.Sprintf("vg::streq(%s, %s)", fx, fy))
			case compiler.KStruct:
				parts = append(parts, fmt.Sprintf("%s(%s, %s)", structEqName(f.Type.Name), fx, fy))
			case compiler.KArray:
				elemCmp := ""
				switch f.Type.Elem.K {
				case compiler.KStr:
					elemCmp = "vg::streq(*x, *y)"
				case compiler.KStruct:
					elemCmp = fmt.Sprintf("%s(*x, *y)", structEqName(f.Type.Elem.Name))
				case compiler.KSlice, compiler.KArray, compiler.KPtr:
					fatal("struct compared with == has a non-comparable field:", n, f.Name)
				default:
					elemCmp = "x == y"
				}
				parts = append(parts, fmt.Sprintf("%s.iter().zip(%s.iter()).all(|(x, y)| %s)", fx, fy, elemCmp))
			case compiler.KSlice, compiler.KPtr:
				fatal("struct compared with == has a non-comparable field:", n, f.Name)
			default:
				parts = append(parts, fmt.Sprintf("%s == %s", fx, fy))
			}
		}
		g.wf("pub fn %s(a: %s, b: %s) -> bool {\n    %s\n}\n\n",
			structEqName(n), ident(n), ident(n), strings.Join(parts, " && "))
	}
}

func (g *gen) needEq(name string) {
	if g.eqs[name] {
		return
	}
	g.eqs[name] = true
	for _, f := range g.p.StructMap[name].Fields {
		if f.Type.K == compiler.KStruct {
			g.needEq(f.Type.Name)
		}
		if f.Type.K == compiler.KArray && f.Type.Elem.K == compiler.KStruct {
			g.needEq(f.Type.Elem.Name)
		}
	}
}

func (g *gen) emitFunc(f *compiler.FuncDecl) {
	g.fn = f
	g.resetNames(f)
	g.loops = nil
	var params []string
	if f.Allocates {
		params = append(params, "mem: &vg::Arena")
	}
	for _, pa := range f.Params {
		params = append(params, ident(pa.Name)+": "+g.typ(pa.Type))
	}
	ret := ""
	switch len(f.Results) {
	case 1:
		ret = " -> " + g.typ(f.Results[0])
	case 2:
		ret = " -> (" + g.typ(f.Results[0]) + ", " + g.typ(f.Results[1]) + ")"
	}
	g.wf("pub fn %s(%s)%s {\n", ident(f.Name), strings.Join(params, ", "), ret)
	g.body(f.Body, 1)
	// Go guarantees a terminating statement.
	// A Rust block whose last statement is a loop still types as ().
	// The marker keeps the tail well typed on every shape.
	if len(f.Results) > 0 && (len(f.Body) == 0 || f.Body[len(f.Body)-1].K != "return") {
		g.wf("    unreachable!()\n")
	}
	g.wf("}\n\n")
	g.fn = nil
}

func (g *gen) indent(depth int) {
	for range depth {
		g.b.WriteString("    ")
	}
}

func (g *gen) body(body []*compiler.Stmt, depth int) {
	for _, s := range body {
		g.stmt(s, depth)
	}
}

func (g *gen) newTmp() string {
	if g.used == nil {
		g.resetNames(g.fn)
	}
	for {
		g.tmp++
		name := fmt.Sprintf("_t%d", g.tmp)
		if !g.used[name] {
			g.used[name] = true
			return name
		}
	}
}

func (g *gen) resetNames(f *compiler.FuncDecl) {
	g.tmp = 0
	g.used = map[string]bool{}
	reserve := func(name string) { g.used[ident(name)] = true }
	for _, d := range g.p.Consts {
		reserve(d.Name)
	}
	for _, d := range g.p.Vars {
		reserve(d.Name)
	}
	for _, d := range g.p.Types {
		reserve(d.Name)
	}
	for _, d := range g.p.Funcs {
		reserve(d.Name)
	}
	if f != nil {
		for name := range f.Info {
			reserve(name)
		}
	}
}

// newLabels mints the break and continue labels of one lowered loop.
func (g *gen) newLabels() (string, string) {
	g.tmp++
	return fmt.Sprintf("'_b%d", g.tmp), fmt.Sprintf("'_c%d", g.tmp)
}

func (g *gen) letKw(name string) string {
	if info := g.fn.Info[name]; info != nil && info.Mutated {
		return "let mut"
	}
	return "let"
}

// place renders a Rust place that does not cross a Vego slice.
func (g *gen) place(e *compiler.Expr) string {
	switch e.K {
	case "ident":
		return ident(e.Name)
	case "field":
		return g.place(e.X) + "." + ident(e.Name)
	case "index":
		if e.X.Typ.K == compiler.KArray {
			return g.place(e.X) + "[(" + g.expr(e.Index) + ") as usize]"
		}
	}
	fatal("unsupported assignment target", e.K)
	return ""
}

type placeStep struct {
	field  string
	index  *compiler.Expr
	length *compiler.Expr
}

type assignmentPlace struct {
	root       string
	slice      *compiler.Expr
	sliceIndex *compiler.Expr
	steps      []placeStep
}

// assignmentPlace finds the deepest slice crossed by a destination.
// That slice owns the slot to pin before the right-hand side runs.
func (g *gen) assignmentPlace(e *compiler.Expr) assignmentPlace {
	switch e.K {
	case "ident":
		return assignmentPlace{root: ident(e.Name)}
	case "field":
		p := g.assignmentPlace(e.X)
		p.steps = append(p.steps, placeStep{field: ident(e.Name)})
		return p
	case "index":
		switch e.X.Typ.K {
		case compiler.KSlice:
			return assignmentPlace{slice: e.X, sliceIndex: e.Index}
		case compiler.KArray:
			p := g.assignmentPlace(e.X)
			p.steps = append(p.steps, placeStep{index: e.Index, length: e.X.Typ.ALen})
			return p
		}
	}
	fatal("unsupported assignment target", e.K)
	return assignmentPlace{}
}

// idx renders an index or bound expression as i64.
func (g *gen) idx(e *compiler.Expr) string {
	if e.Typ.K == compiler.KI64 || e.Typ.K == compiler.KInt {
		return g.expr(e)
	}
	return "((" + g.expr(e) + ") as i64)"
}

func (g *gen) assignLine(depth int, lhs *compiler.Expr, rhs string) {
	if lhs.K == "ident" && lhs.Name == "_" {
		g.indent(depth)
		g.wf("let _ = %s;\n", rhs)
		return
	}
	g.assignOperation(depth, lhs, rhs, "=")
}

func (g *gen) assignOperation(depth int, lhs *compiler.Expr, rhs, op string) {
	p := g.assignmentPlace(lhs)
	if p.slice != nil && !compiler.Impure(lhs) && !hasArrayStep(p.steps) {
		g.indent(depth)
		if len(p.steps) == 0 && op == "=" {
			g.wf("%s.set(%s, %s);\n", g.expr(p.slice), g.idx(p.sliceIndex), rhs)
		} else {
			value, elem := g.newTmp(), g.newTmp()
			place := renderDirectPlace(g, elem, p.steps)
			g.wf("%s.update(%s, %s, |mut %s, %s| { %s; %s });\n",
				g.expr(p.slice), g.idx(p.sliceIndex), rhs, elem, value,
				assignmentExpr(place, value, op, lhs.Typ), elem)
		}
		return
	}
	if p.slice == nil && !compiler.Impure(lhs) {
		g.indent(depth)
		g.wf("%s;\n", assignmentExpr(g.place(lhs), rhs, op, lhs.Typ))
		return
	}

	g.indent(depth)
	g.wf("{\n")
	inner := depth + 1
	slot := ""
	if p.slice != nil {
		slot = g.newTmp()
		g.indent(inner)
		g.wf("let %s = %s.slot(%s);\n", slot, g.expr(p.slice), g.idx(p.sliceIndex))
	}
	indexes := make([]string, len(p.steps))
	for i, step := range p.steps {
		if step.index == nil {
			continue
		}
		indexes[i] = g.newTmp()
		g.indent(inner)
		g.wf("let %s = vg::array_index(%s, ((%s) as usize));\n",
			indexes[i], g.idx(step.index), g.constPlain(step.length))
	}
	value := g.newTmp()
	g.indent(inner)
	g.wf("let %s = %s;\n", value, rhs)
	if slot == "" {
		g.indent(inner)
		place := renderPlace(p.root, p.steps, indexes)
		g.wf("%s;\n", assignmentExpr(place, value, op, lhs.Typ))
	} else if len(p.steps) == 0 && op == "=" {
		g.indent(inner)
		g.wf("%s.set(%s);\n", slot, value)
	} else {
		elem := g.newTmp()
		g.indent(inner)
		place := renderPlace(elem, p.steps, indexes)
		g.wf("%s.update(%s, |mut %s, %s| { %s; %s });\n",
			slot, value, elem, value, assignmentExpr(place, value, op, lhs.Typ), elem)
	}
	g.indent(depth)
	g.wf("}\n")
}

func assignmentExpr(lhs, rhs, op string, typ *compiler.Type) string {
	if method := wrappingMethod(strings.TrimSuffix(op, "="), typ); method != "" {
		return fmt.Sprintf("%s = (%s).%s(%s)", lhs, lhs, method, rhs)
	}
	return fmt.Sprintf("%s %s %s", lhs, op, rhs)
}

func wrappingMethod(op string, typ *compiler.Type) string {
	switch op {
	case "+":
		return "wrapping_add"
	case "-":
		return "wrapping_sub"
	case "*":
		return "wrapping_mul"
	case "/":
		if typ != nil && typ.Signed() {
			return "wrapping_div"
		}
	case "%":
		if typ != nil && typ.Signed() {
			return "wrapping_rem"
		}
	}
	return ""
}

func hasArrayStep(steps []placeStep) bool {
	for _, step := range steps {
		if step.index != nil {
			return true
		}
	}
	return false
}

func renderPlace(root string, steps []placeStep, indexes []string) string {
	var b strings.Builder
	b.WriteString(root)
	for i, step := range steps {
		if step.field != "" {
			b.WriteByte('.')
			b.WriteString(step.field)
		} else {
			fmt.Fprintf(&b, "[%s]", indexes[i])
		}
	}
	return b.String()
}

func renderDirectPlace(g *gen, root string, steps []placeStep) string {
	var b strings.Builder
	b.WriteString(root)
	for _, step := range steps {
		if step.field != "" {
			b.WriteByte('.')
			b.WriteString(step.field)
		} else {
			fmt.Fprintf(&b, "[(%s) as usize]", g.expr(step.index))
		}
	}
	return b.String()
}

func (g *gen) stmt(s *compiler.Stmt, depth int) {
	switch s.K {
	case "var_decl":
		val := "vg::zero()"
		if s.Value != nil {
			val = g.expr(s.Value)
		}
		g.indent(depth)
		g.wf("%s %s: %s = %s;\n", g.letKw(s.Name), ident(s.Name), g.typ(s.TypeRef), val)
	case "define":
		if len(s.Names) == 1 {
			g.indent(depth)
			g.wf("%s %s: %s = %s;\n", g.letKw(s.Names[0]), ident(s.Names[0]),
				g.typ(s.DeclaredTypes[0]), g.expr(s.Value))
			return
		}
		tmp := g.newTmp()
		g.indent(depth)
		g.wf("let %s = %s;\n", tmp, g.expr(s.Value))
		for i, n := range s.Names {
			if n == "_" {
				continue
			}
			g.indent(depth)
			g.wf("%s %s: %s = %s.%d;\n", g.letKw(n), ident(n), g.typ(s.DeclaredTypes[i]), tmp, i)
		}
	case "assign":
		if len(s.Lhs) == 2 {
			tmp := g.newTmp()
			g.indent(depth)
			g.wf("{\n")
			g.indent(depth + 1)
			g.wf("let %s = %s;\n", tmp, g.expr(s.Value))
			for i, l := range s.Lhs {
				if l.K == "ident" && l.Name == "_" {
					continue
				}
				g.assignLine(depth+1, l, fmt.Sprintf("%s.%d", tmp, i))
			}
			g.indent(depth)
			g.wf("}\n")
			return
		}
		g.assignLine(depth, s.Lhs[0], g.expr(s.Value))
	case "op_assign":
		op := s.Op
		val := g.expr(s.Value)
		if op == "&^=" {
			// Rust has no &^=, so the printer complements the value and uses &=.
			op = "&="
			val = "!(" + val + ")"
		}
		g.assignOperation(depth, s.Lhs[0], val, op)
	case "if":
		g.indent(depth)
		g.wf("if %s {\n", g.expr(s.Cond))
		g.body(s.Then, depth+1)
		g.indent(depth)
		if s.HasElse {
			g.wf("} else {\n")
			g.body(s.Else, depth+1)
			g.indent(depth)
		}
		g.wf("}\n")
	case "for":
		g.emitFor(s, depth)
	case "range":
		g.emitRange(s, depth)
	case "switch":
		tmp := g.newTmp()
		g.indent(depth)
		g.wf("{\n")
		g.indent(depth + 1)
		g.wf("let %s = %s;\n", tmp, g.expr(s.Tag))
		for i, cs := range s.Cases {
			var conds []string
			for _, v := range cs.Values {
				conds = append(conds, fmt.Sprintf("%s == %s", tmp, g.expr(v)))
			}
			g.indent(depth + 1)
			if i == 0 {
				g.wf("if %s {\n", strings.Join(conds, " || "))
			} else {
				g.wf("} else if %s {\n", strings.Join(conds, " || "))
			}
			g.body(cs.Body, depth+2)
		}
		g.indent(depth + 1)
		if s.HasDef {
			g.wf("} else {\n")
			g.body(s.Default, depth+2)
			g.indent(depth + 1)
		}
		g.wf("}\n")
		g.indent(depth)
		g.wf("}\n")
	case "break":
		g.indent(depth)
		if n := len(g.loops); n > 0 && g.loops[n-1].brk != "" {
			g.wf("break %s;\n", g.loops[n-1].brk)
		} else {
			g.wf("break;\n")
		}
	case "continue":
		g.indent(depth)
		if n := len(g.loops); n > 0 && g.loops[n-1].cont != "" {
			g.wf("break %s;\n", g.loops[n-1].cont)
		} else {
			g.wf("continue;\n")
		}
	case "return":
		g.indent(depth)
		switch len(s.Values) {
		case 0:
			g.wf("return;\n")
		case 1:
			g.wf("return %s;\n", g.expr(s.Values[0]))
		default:
			g.wf("return (%s, %s);\n", g.expr(s.Values[0]), g.expr(s.Values[1]))
		}
	case "expr_stmt":
		g.indent(depth)
		if s.Value.Typ != nil {
			g.wf("let _ = %s;\n", g.expr(s.Value))
		} else {
			g.wf("%s;\n", g.expr(s.Value))
		}
	case "block":
		g.indent(depth)
		g.wf("{\n")
		g.body(s.Body, depth+1)
		g.indent(depth)
		g.wf("}\n")
	default:
		fatal("unknown statement kind", s.K)
	}
}

// emitFor lowers the three Go loop forms.
// A loop with a post statement gets labels, so continue still runs the post and break still skips it.
func (g *gen) emitFor(s *compiler.Stmt, depth int) {
	if s.Init == nil && s.Post == nil {
		g.indent(depth)
		if s.Cond != nil {
			g.wf("while %s {\n", g.expr(s.Cond))
		} else {
			g.wf("loop {\n")
		}
		g.loops = append(g.loops, loopCtx{})
		g.body(s.Body, depth+1)
		g.loops = g.loops[:len(g.loops)-1]
		g.indent(depth)
		g.wf("}\n")
		return
	}
	brk, cont := g.newLabels()
	g.indent(depth)
	g.wf("{\n")
	if s.Init != nil {
		g.stmt(s.Init, depth+1)
	}
	g.indent(depth + 1)
	if s.Cond != nil {
		g.wf("%s: while %s {\n", brk, g.expr(s.Cond))
	} else {
		g.wf("%s: loop {\n", brk)
	}
	if s.Post == nil {
		g.loops = append(g.loops, loopCtx{})
		g.body(s.Body, depth+2)
		g.loops = g.loops[:len(g.loops)-1]
	} else {
		g.indent(depth + 2)
		g.wf("%s: {\n", cont)
		g.loops = append(g.loops, loopCtx{brk: brk, cont: cont})
		g.body(s.Body, depth+3)
		g.loops = g.loops[:len(g.loops)-1]
		g.indent(depth + 2)
		g.wf("}\n")
		g.stmt(s.Post, depth+2)
	}
	g.indent(depth + 1)
	g.wf("}\n")
	g.indent(depth)
	g.wf("}\n")
}

// emitRange lowers a range statement to an index loop.
// The Vego engine has no range statement, but the form stays supported.
// The operand evaluates once into a copy, and a hidden counter drives the loop.
// A write to the user variables in the body therefore cannot change the iteration.
func (g *gen) emitRange(s *compiler.Stmt, depth int) {
	over := g.newTmp()
	counter := g.newTmp()
	brk, cont := g.newLabels()
	g.indent(depth)
	g.wf("{\n")
	g.indent(depth + 1)
	g.wf("let %s = %s;\n", over, g.expr(s.Value))
	limit := over
	switch s.Value.Typ.K {
	case compiler.KSlice:
		limit = over + ".len"
	case compiler.KArray:
		limit = "((" + g.constPlain(s.Value.Typ.ALen) + ") as i64)"
	}
	g.indent(depth + 1)
	g.wf("let mut %s: i64 = 0;\n", counter)
	g.indent(depth + 1)
	g.wf("%s: while %s < %s {\n", brk, counter, limit)
	g.indent(depth + 2)
	g.wf("%s: {\n", cont)
	if s.IdxName != "" && s.IdxName != "_" {
		g.indent(depth + 3)
		g.wf("%s %s: i64 = %s;\n", g.letKw(s.IdxName), ident(s.IdxName), counter)
	}
	if s.ValName != "" && s.ValName != "_" {
		g.indent(depth + 3)
		elem := s.Value.Typ.Elem
		iexpr := &compiler.Expr{K: "ident", Name: counter, Typ: compiler.TInt}
		overRef := &compiler.Expr{K: "ident", Name: over, Typ: s.Value.Typ}
		read := g.expr(&compiler.Expr{K: "index", X: overRef, Index: iexpr, Typ: elem})
		g.wf("%s %s: %s = %s;\n", g.letKw(s.ValName), ident(s.ValName), g.typ(elem), read)
	}
	g.loops = append(g.loops, loopCtx{brk: brk, cont: cont})
	g.body(s.Body, depth+3)
	g.loops = g.loops[:len(g.loops)-1]
	g.indent(depth + 2)
	g.wf("}\n")
	g.indent(depth + 2)
	g.wf("%s += 1;\n", counter)
	g.indent(depth + 1)
	g.wf("}\n")
	g.indent(depth)
	g.wf("}\n")
}

func isNil(e *compiler.Expr) bool {
	return e.K == "ident" && e.Name == "nil"
}

func isBorrowArg(a *compiler.Expr) bool {
	if a.K == "unary" && a.Op == "&" {
		return true
	}
	return a.Typ != nil && a.Typ.K == compiler.KPtr
}

// constLiteral renders a constant integer expression as one literal of its type.
// The value folds at the precision Go uses, so no intermediate result truncates to a leaf type.
func (g *gen) constLiteral(e *compiler.Expr) (string, bool) {
	switch e.K {
	case "int", "char", "ident":
		return "", false
	}
	v, ok := compiler.FoldConst(g.p, e)
	if !ok {
		return "", false
	}
	return g.expr(compiler.ConstExpr(v, e.Typ)), true
}

func (g *gen) expr(e *compiler.Expr) string {
	if lit, ok := g.constLiteral(e); ok {
		return lit
	}
	switch e.K {
	case "int", "char":
		return intLiteral(e)
	case "str":
		return "vg::lit(b\"" + rustEscape(e.Value) + "\")"
	case "bool":
		if e.BoolVal {
			return "true"
		}
		return "false"
	case "ident":
		if e.Name == "nil" {
			return "vg::zero::<" + g.typ(e.Typ) + ">()"
		}
		// An untyped constant adopts the type of its use site.
		// The Rust declaration fixed one type, so every other site casts.
		if d, ok := g.p.ConstMap[e.Name]; ok && !compiler.Same(d.Inferred, e.Typ) {
			return "((" + ident(e.Name) + ") as " + g.typ(e.Typ) + ")"
		}
		return ident(e.Name)
	case "field":
		return g.expr(e.X) + "." + ident(e.Name)
	case "index":
		switch e.X.Typ.K {
		case compiler.KSlice:
			return g.expr(e.X) + ".get(" + g.idx(e.Index) + ")"
		case compiler.KStr:
			return g.expr(e.X) + ".byte(" + g.idx(e.Index) + ")"
		case compiler.KArray:
			return g.expr(e.X) + "[(" + g.expr(e.Index) + ") as usize]"
		}
		fatal("index of", e.X.Typ)
	case "slice_expr":
		x := g.expr(e.X)
		switch e.X.Typ.K {
		case compiler.KSlice, compiler.KStr:
			switch {
			case e.Lo == nil && e.Hi == nil:
				return x
			case e.Lo == nil:
				return x + ".head(" + g.idx(e.Hi) + ")"
			case e.Hi == nil:
				return x + ".tail(" + g.idx(e.Lo) + ")"
			default:
				return x + ".sub(" + g.idx(e.Lo) + ", " + g.idx(e.Hi) + ")"
			}
		case compiler.KArray:
			pl := g.place(e.X)
			lo := "0i64"
			if e.Lo != nil {
				lo = g.idx(e.Lo)
			}
			hi := "((" + g.constPlain(e.X.Typ.ALen) + ") as i64)"
			if e.Hi != nil {
				hi = g.idx(e.Hi)
			}
			return fmt.Sprintf("vg::arr_slice(&raw mut %s, %s, %s)", pl, lo, hi)
		}
		fatal("slice of", e.X.Typ)
	case "call":
		return g.call(e)
	case "builtin":
		return g.builtin(e)
	case "conv":
		if e.TypeRef.K == compiler.KStr {
			return "vg::str_from_bytes(mem, " + g.expr(e.X) + ")"
		}
		if e.TypeRef.K == compiler.KSlice {
			return "vg::bytes_from_str(mem, " + g.expr(e.X) + ")"
		}
		return "((" + g.expr(e.X) + ") as " + g.typ(e.TypeRef) + ")"
	case "unary":
		switch e.Op {
		case "-":
			return "(" + g.expr(e.X) + ").wrapping_neg()"
		case "^":
			return "(!(" + g.expr(e.X) + "))"
		case "!":
			return "(!" + g.expr(e.X) + ")"
		case "&":
			return "&mut " + g.place(e.X)
		}
		fatal("unknown unary", e.Op)
	case "binary":
		return g.binary(e)
	case "composite":
		return g.composite(e)
	}
	fatal("unknown expression kind", e.K)
	return ""
}

// call renders a function call.
// When an argument borrows a local, the other arguments hoist into temporaries first, in the evaluation order of Go.
// The borrow then never overlaps their reads.
func (g *gen) call(e *compiler.Expr) string {
	var memArg []string
	if g.p.CalleeAllocates(e.Name) {
		memArg = []string{"mem"}
	}
	hasBorrow := false
	for _, a := range e.Args {
		if isBorrowArg(a) {
			hasBorrow = true
		}
	}
	if !hasBorrow {
		args := memArg
		for _, a := range e.Args {
			args = append(args, g.expr(a))
		}
		return ident(e.Name) + "(" + strings.Join(args, ", ") + ")"
	}
	var pre []string
	args := memArg
	for _, a := range e.Args {
		if isBorrowArg(a) {
			args = append(args, g.expr(a))
			continue
		}
		tmp := g.newTmp()
		pre = append(pre, fmt.Sprintf("let %s = %s;", tmp, g.expr(a)))
		args = append(args, tmp)
	}
	call := ident(e.Name) + "(" + strings.Join(args, ", ") + ")"
	if len(pre) == 0 {
		return call
	}
	return "{ " + strings.Join(pre, " ") + " " + call + " }"
}

func (g *gen) builtin(e *compiler.Expr) string {
	switch e.Name {
	case "len":
		switch e.Args[0].Typ.K {
		case compiler.KStr, compiler.KSlice:
			return g.expr(e.Args[0]) + ".len"
		case compiler.KArray:
			return "((" + g.constPlain(e.Args[0].Typ.ALen) + ") as i64)"
		}
		fatal("len of", e.Args[0].Typ)
	case "cap":
		return g.expr(e.Args[0]) + ".cap"
	case "make":
		elem := g.typ(e.TypeRef.Elem)
		if len(e.Args) == 2 {
			return fmt.Sprintf("vg::make_cap::<%s>(mem, %s, %s)", elem, g.idx(e.Args[0]), g.idx(e.Args[1]))
		}
		return fmt.Sprintf("vg::make::<%s>(mem, %s)", elem, g.idx(e.Args[0]))
	case "append":
		if e.Spread {
			if e.Args[1].Typ.K == compiler.KStr {
				return fmt.Sprintf("vg::append_str(mem, %s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
			}
			return fmt.Sprintf("vg::append_slice(mem, %s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
		}
		out := g.expr(e.Args[0])
		if compiler.AppendNeedsPin(e) {
			// Every element evaluates before the first append writes, as in Go.
			var pre []string
			for _, a := range e.Args[1:] {
				tmp := g.newTmp()
				pre = append(pre, fmt.Sprintf("let %s = %s;", tmp, g.expr(a)))
				out = fmt.Sprintf("vg::append(mem, %s, %s)", out, tmp)
			}
			return "{ " + strings.Join(pre, " ") + " " + out + " }"
		}
		for _, a := range e.Args[1:] {
			out = fmt.Sprintf("vg::append(mem, %s, %s)", out, g.expr(a))
		}
		return out
	case "copy":
		if e.Args[1].Typ.K == compiler.KStr {
			return fmt.Sprintf("vg::vcopy_str(%s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
		}
		return fmt.Sprintf("vg::vcopy(%s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
	case "min":
		return fmt.Sprintf("std::cmp::min(%s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
	case "max":
		return fmt.Sprintf("std::cmp::max(%s, %s)", g.expr(e.Args[0]), g.expr(e.Args[1]))
	}
	fatal("unknown builtin", e.Name)
	return ""
}

func (g *gen) binary(e *compiler.Expr) string {
	// Slice-to-nil comparisons test the data pointer, like Go.
	if e.Op == "==" || e.Op == "!=" {
		if isNil(e.Y) && e.X.Typ.K == compiler.KSlice {
			if e.Op == "==" {
				return "(" + g.expr(e.X) + ".p.is_null())"
			}
			return "(!" + g.expr(e.X) + ".p.is_null())"
		}
		if isNil(e.X) && e.Y.Typ.K == compiler.KSlice {
			if e.Op == "==" {
				return "(" + g.expr(e.Y) + ".p.is_null())"
			}
			return "(!" + g.expr(e.Y) + ".p.is_null())"
		}
	}
	if e.X.Typ.K == compiler.KStr {
		x, y := g.expr(e.X), g.expr(e.Y)
		switch e.Op {
		case "==":
			return fmt.Sprintf("vg::streq(%s, %s)", x, y)
		case "!=":
			return fmt.Sprintf("(!vg::streq(%s, %s))", x, y)
		case "<", "<=", ">", ">=":
			return fmt.Sprintf("(vg::strcmp3(%s, %s) %s 0)", x, y, e.Op)
		}
	}
	if e.X.Typ.K == compiler.KStruct {
		x, y := g.expr(e.X), g.expr(e.Y)
		switch e.Op {
		case "==":
			return fmt.Sprintf("%s(%s, %s)", structEqName(e.X.Typ.Name), x, y)
		case "!=":
			return fmt.Sprintf("(!%s(%s, %s))", structEqName(e.X.Typ.Name), x, y)
		}
	}
	x, y := g.expr(e.X), g.expr(e.Y)
	if method := wrappingMethod(e.Op, e.Typ); method != "" {
		return fmt.Sprintf("(%s).%s(%s)", x, method, y)
	}
	switch e.Op {
	case "&^":
		return fmt.Sprintf("(%s & !(%s))", x, y)
	case "/":
		return fmt.Sprintf("(%s / %s)", x, y)
	case "%":
		return fmt.Sprintf("(%s %% %s)", x, y)
	case "&", "|", "^", "==", "!=",
		"<", "<=", ">", ">=", "&&", "||", "<<", ">>":
		return fmt.Sprintf("(%s %s %s)", x, e.Op, y)
	}
	fatal("unknown binary op", e.Op)
	return ""
}

func (g *gen) composite(e *compiler.Expr) string {
	t := e.TypeRef
	switch t.K {
	case compiler.KStruct:
		sd := g.p.StructMap[t.Name]
		var parts []string
		for _, f := range e.Fields {
			parts = append(parts, ident(f.Name)+": "+g.expr(f.Value))
		}
		if len(e.Fields) < len(sd.Fields) {
			parts = append(parts, "..vg::zero()")
		}
		return ident(t.Name) + " { " + strings.Join(parts, ", ") + " }"
	case compiler.KSlice:
		var parts []string
		for _, el := range e.Elems {
			parts = append(parts, g.expr(el))
		}
		return fmt.Sprintf("vg::slice_of::<%s>(mem, &[%s])", g.typ(t.Elem), strings.Join(parts, ", "))
	case compiler.KArray:
		var parts []string
		for _, el := range e.Elems {
			parts = append(parts, g.expr(el))
		}
		// Go zero-fills omitted trailing elements.
		if n, ok := g.p.ArrayLen(t); ok {
			for int64(len(parts)) < n {
				parts = append(parts, fmt.Sprintf("vg::zero::<%s>()", g.typ(t.Elem)))
			}
		}
		return "[" + strings.Join(parts, ", ") + "]"
	}
	fatal("composite of", t)
	return ""
}

func rustEscape(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString("\\\"")
		case c == '\\':
			b.WriteString("\\\\")
		case c == '\n':
			b.WriteString("\\n")
		case c < 32 || c > 126:
			fmt.Fprintf(&b, "\\x%02x", c)
		default:
			b.WriteByte(c)
		}
	}
	return b.String()
}
