// Code generated by vegoc from the Vego JSON form. DO NOT EDIT.

#pragma once

#include "vg.hpp"

namespace revera::engine {

inline constexpr uint8_t itemChar = 0;
inline constexpr uint8_t itemElem = 1;
inline constexpr uint8_t itemEquiv = 2;
inline constexpr uint8_t itemClass = 3;
inline constexpr int64_t capWorkLimit = 50000000LL;
inline constexpr int64_t solverArenaLimit = 67108864LL;
inline constexpr int64_t contractCap = 4611686018427387904LL;
inline constexpr int64_t frameBytes = 256LL;
inline constexpr int64_t matcherStackBytes = 2048LL;
inline constexpr int64_t singleLookupFrames = 8LL;
inline constexpr int64_t maxElemAhead = 8LL;
inline constexpr int64_t multiLookupFrames = 16LL;
inline constexpr int64_t ptreeBytes = 48LL;
inline constexpr int64_t kidBytes = 8LL;
inline constexpr int64_t mapEntryBytes = 128LL;
inline constexpr int64_t matchBytes = 16LL;
inline constexpr int64_t profileRowCost = 13LL;
inline constexpr int64_t queueCompactFactor = 2LL;
inline constexpr int32_t ErrNone = 0;
inline constexpr int32_t ErrNoMatch = 1;
inline constexpr int32_t ErrBadPat = 2;
inline constexpr int32_t ErrECollate = 3;
inline constexpr int32_t ErrECType = 4;
inline constexpr int32_t ErrEEscape = 5;
inline constexpr int32_t ErrESubReg = 6;
inline constexpr int32_t ErrEBrack = 7;
inline constexpr int32_t ErrEParen = 8;
inline constexpr int32_t ErrEBrace = 9;
inline constexpr int32_t ErrBadBR = 10;
inline constexpr int32_t ErrERange = 11;
inline constexpr int32_t ErrESpace = 12;
inline constexpr int32_t ErrBadRpt = 13;
inline constexpr int32_t ErrENoSub = 14;
inline constexpr uint32_t FlagICase = 1U;
inline constexpr uint32_t FlagNewline = 2U;
inline constexpr uint32_t FlagNoSub = 4U;
inline constexpr uint32_t FlagMinimal = 8U;
inline constexpr uint32_t ExecNotBOL = 1U;
inline constexpr uint32_t ExecNotEOL = 2U;
inline constexpr int64_t dupMax = 255LL;
inline constexpr uint8_t classAlnum = 0;
inline constexpr uint8_t classAlpha = 1;
inline constexpr uint8_t classBlank = 2;
inline constexpr uint8_t classCntrl = 3;
inline constexpr uint8_t classDigit = 4;
inline constexpr uint8_t classGraph = 5;
inline constexpr uint8_t classLower = 6;
inline constexpr uint8_t classPrint = 7;
inline constexpr uint8_t classPunct = 8;
inline constexpr uint8_t classSpace = 9;
inline constexpr uint8_t classUpper = 10;
inline constexpr uint8_t classXdigit = 11;
inline constexpr int64_t numClasses = 12LL;
inline constexpr int64_t firstSequenceID = 1114112LL;
inline constexpr int64_t secCtypeStage1 = 0LL;
inline constexpr int64_t secCtypeBlocks = 1LL;
inline constexpr int64_t secCaseDefault = 2LL;
inline constexpr int64_t secCaseTurkic = 3LL;
inline constexpr int64_t secSeqCodepoints = 4LL;
inline constexpr int64_t secSequences = 5LL;
inline constexpr int64_t secRootContractions = 6LL;
inline constexpr int64_t secRootEquivalences = 7LL;
inline constexpr int64_t secCollationOverrides = 8LL;
inline constexpr int64_t secContractionAdds = 9LL;
inline constexpr int64_t secContractionRemoves = 10LL;
inline constexpr int64_t secCollationProfiles = 11LL;
inline constexpr int64_t secTypeNames = 12LL;
inline constexpr int64_t secTypeNameOffsets = 13LL;
inline constexpr int64_t secLocaleNames = 14LL;
inline constexpr int64_t secLocaleNameOffsets = 15LL;
inline constexpr int64_t secLocales = 16LL;
inline constexpr int64_t secLocaleTypes = 17LL;
inline constexpr int64_t secInvUpperDefault = 18LL;
inline constexpr int64_t secInvLowerDefault = 19LL;
inline constexpr int64_t secInvUpperTurkic = 20LL;
inline constexpr int64_t secInvLowerTurkic = 21LL;
inline constexpr int64_t secScalars = 22LL;
inline constexpr int64_t numSections = 23LL;
inline constexpr int64_t ctypeStage1Entries = 4352LL;
inline constexpr int64_t normalizedNameMax = 127LL;
inline constexpr int64_t maxPreimages = 16LL;
inline constexpr uint8_t iRune = 0;
inline constexpr uint8_t iRuneFold = 1;
inline constexpr uint8_t iAny = 2;
inline constexpr uint8_t iBracket = 3;
inline constexpr uint8_t iBOL = 4;
inline constexpr uint8_t iEOL = 5;
inline constexpr uint8_t iSplit = 6;
inline constexpr uint8_t iJmp = 7;
inline constexpr uint8_t iMatch = 8;
inline constexpr uint8_t iFail = 9;
inline constexpr int64_t failMinNone = 4611686018427387904LL;
inline constexpr int64_t maxProgram = 1048576LL;
inline constexpr int64_t maskWidth = 64LL;
inline constexpr int64_t subjectLimit = 2147483647LL;
inline constexpr int64_t lengthCap = 1099511627776LL;
inline constexpr uint8_t opChar = 0;
inline constexpr uint8_t opAny = 1;
inline constexpr uint8_t opBracket = 2;
inline constexpr uint8_t opBOL = 3;
inline constexpr uint8_t opEOL = 4;
inline constexpr uint8_t opConcat = 5;
inline constexpr uint8_t opAlt = 6;
inline constexpr uint8_t opRepeat = 7;
inline constexpr uint8_t opGroup = 8;
inline constexpr int64_t infinite = int64_t(0ULL - uint64_t(1LL));
inline constexpr int64_t lenInf = 1073741824LL;
inline constexpr int32_t invalidRune = int32_t(0ULL - uint64_t(1));

struct runeRange;
struct bracketSet;
struct bracketItem;
struct elemBuf;
struct ptree;
struct capSolver;
struct repBest;
struct repWin;
struct BackendContract;
struct Contract;
struct lookupCosts;
struct slotTable;
struct engineWS;
struct engineResult;
struct phaseAState;
struct Error;
struct memoKey;
struct memoVal;
struct memoTab;
struct SecRange;
struct Locale;
struct LocaleRow;
struct localeRequest;
struct CasePair;
struct preimageBuf;
struct CollProfile;
struct Match;
struct decoded;
struct instr;
struct scanFilter;
struct program;
struct patchSlot;
struct frag;
struct progBuilder;
struct Regexp;
struct groupStack;
struct MatchIter;
struct replPart;
struct node;
struct parser;
struct interval;

struct runeRange {
    int32_t lo = {};
    int32_t hi = {};
    bool operator==(const runeRange&) const = default;
};

struct bracketSet {
    bool negated = {};
    bool icase = {};
    bool nlMode = {};
    vg::Slice<runeRange> ranges = {};
    uint16_t classMask = {};
    vg::Slice<vg::Slice<int32_t>> elems = {};
    vg::Slice<vg::Slice<int32_t>> equivs = {};
    uint16_t multiLens = {};
};

struct bracketItem {
    uint8_t kind = {};
    int32_t r = {};
    vg::Slice<int32_t> seq = {};
    uint8_t vego_class = {};
};

struct elemBuf {
    std::array<int32_t, maxElemAhead> r = {};
    bool operator==(const elemBuf&) const = default;
};

struct ptree {
    int32_t n = {};
    int32_t i = {};
    int32_t j = {};
    int32_t branch = {};
    int32_t kidsOff = {};
    int32_t kidsLen = {};
    bool operator==(const ptree&) const = default;
};

struct memoTab {
    vg::Slice<memoKey> keys = {};
    vg::Slice<memoVal> vals = {};
    vg::Slice<uint8_t> used = {};
    int64_t count = {};
};

struct capSolver {
    uint32_t eflags = {};
    memoTab memo = {};
    memoTab cmemo = {};
    memoTab rmemo = {};
    vg::Slice<int64_t> ctrA = {};
    vg::Slice<int64_t> ctrB = {};
    int64_t work = {};
    bool failed = {};
    vg::Slice<ptree> trees = {};
    vg::Slice<int32_t> kidStore = {};
};

struct repBest {
    int64_t off = {};
    int64_t length = {};
    int32_t tree = {};
    bool found = {};
    bool operator==(const repBest&) const = default;
};

struct repWin {
    int64_t off = {};
    int64_t length = {};
    bool ok = {};
    bool operator==(const repWin&) const = default;
};

struct BackendContract {
    int64_t HeapBytes = {};
    int64_t StackBytes = {};
    int64_t Steps = {};
    bool operator==(const BackendContract&) const = default;
};

struct Contract {
    int64_t MaxInput = {};
    BackendContract Matcher = {};
    BackendContract OnePass = {};
    bool HasOnePass = {};
    BackendContract Solver = {};
    bool HasSolver = {};
    bool operator==(const Contract&) const = default;
};

struct lookupCosts {
    int64_t sequenceSearch = {};
    int64_t contraction = {};
    int64_t primaryToken = {};
    int64_t classMask = {};
    int64_t casePreimages = {};
    int64_t caseConvert = {};
    int64_t preimages = {};
    bool operator==(const lookupCosts&) const = default;
};

struct slotTable {
    vg::Slice<uint32_t> stamp = {};
    vg::Slice<int32_t> starts = {};
    vg::Slice<uint32_t> ctr = {};
    vg::Slice<uint32_t> active = {};
    uint32_t gen = {};
};

struct engineWS {
    vg::Slice<slotTable> slots = {};
    vg::Slice<uint32_t> queue = {};
    vg::Slice<uint8_t> onq = {};
    vg::Slice<uint32_t> bestCtr = {};
    vg::Slice<uint32_t> ctrBuf = {};
    vg::Slice<uint32_t> zeros = {};
    vg::Slice<int32_t> ahead = {};
};

struct engineResult {
    bool matched = {};
    int64_t so = {};
    int64_t eo = {};
    bool operator==(const engineResult&) const = default;
};

struct phaseAState {
    vg::Str subject = {};
    uint32_t eflags = {};
    int64_t k = {};
    int64_t ring = {};
    bool nlMode = {};
    int64_t ci = {};
    int64_t pos = {};
    bool bol = {};
    bool eol = {};
    int32_t cur = {};
    int64_t size = {};
    bool matched = {};
    int64_t so = {};
    int64_t eo = {};
    bool operator==(const phaseAState&) const = default;
};

struct Error {
    int32_t Code = {};
    int64_t Pos = {};
    bool operator==(const Error&) const = default;
};

struct memoKey {
    int32_t a = {};
    int32_t b = {};
    int32_t c = {};
    int32_t d = {};
    bool operator==(const memoKey&) const = default;
};

struct memoVal {
    int32_t x = {};
    int32_t y = {};
    int32_t z = {};
    bool operator==(const memoVal&) const = default;
};

struct SecRange {
    int64_t Off = {};
    int64_t End = {};
    bool operator==(const SecRange&) const = default;
};

struct Locale {
    vg::Str blob = {};
    std::array<SecRange, numSections> sec = {};
    int64_t maxSeq = {};
    int64_t preimagesDefault = {};
    int64_t preimagesTurkic = {};
    uint16_t collationProfile = {};
    uint8_t caseProfile = {};
    bool posix = {};
    bool valid = {};
    bool operator==(const Locale&) const = default;
};

struct LocaleRow {
    int64_t TypeFirst = {};
    int64_t TypeCount = {};
    uint8_t CaseProfile = {};
    uint16_t DefaultCollation = {};
    bool operator==(const LocaleRow&) const = default;
};

struct localeRequest {
    vg::Str name = {};
    vg::Str ctype = {};
    bool posix = {};
    bool operator==(const localeRequest&) const = default;
};

struct CasePair {
    int32_t Upper = {};
    int32_t Lower = {};
    bool operator==(const CasePair&) const = default;
};

struct preimageBuf {
    std::array<int32_t, maxPreimages> r = {};
    int64_t n = {};
    bool operator==(const preimageBuf&) const = default;
};

struct CollProfile {
    int64_t OverrideFirst = {};
    int64_t OverrideCount = {};
    int64_t AddFirst = {};
    int64_t AddCount = {};
    int64_t RemoveFirst = {};
    int64_t RemoveCount = {};
    bool operator==(const CollProfile&) const = default;
};

struct Match {
    int64_t So = {};
    int64_t Eo = {};
    bool operator==(const Match&) const = default;
};

struct decoded {
    vg::Slice<int32_t> runes = {};
    vg::Slice<int64_t> byteAt = {};
    bool atSubjectStart = {};
    bool atSubjectEnd = {};
    bool prevIsNewline = {};
    bool nextIsNewline = {};
};

struct instr {
    uint8_t op = {};
    uint32_t next = {};
    uint32_t alt = {};
    uint32_t arg = {};
    uint64_t mask = {};
    vg::Slice<uint32_t> extra = {};
};

struct scanFilter {
    bool enabled = {};
    bool single = {};
    uint8_t b = {};
    std::array<bool, 256> stop = {};
    bool operator==(const scanFilter&) const = default;
};

struct program {
    vg::Slice<instr> ins = {};
    uint32_t start = {};
    vg::Slice<vg::Slice<int32_t>> foldSets = {};
    bool multi = {};
    int64_t failMin = {};
    scanFilter scan = {};
    int64_t depth = {};
};

struct patchSlot {
    uint32_t idx = {};
    bool alt = {};
    bool operator==(const patchSlot&) const = default;
};

struct frag {
    uint32_t start = {};
    vg::Slice<patchSlot> out = {};
};

struct progBuilder {
    program prog = {};
    bool tooBig = {};
    int64_t failMin = {};
    int32_t errCode = {};
    bool icase = {};
};

struct Regexp {
    vg::Slice<node> nodes = {};
    vg::Slice<bracketSet> brackets = {};
    int32_t root = {};
    int64_t nsub = {};
    uint32_t flags = {};
    Locale loc = {};
    int64_t minSlots = {};
    vg::Slice<vg::Slice<int32_t>> nested = {};
    bool multi = {};
    bool progOK = {};
    program prog = {};
    int64_t minLen = {};
    bool anchors = {};
    bool onePass = {};
};

struct groupStack {
    vg::Slice<int32_t> g = {};
};

struct MatchIter {
    int64_t pos = {};
    int64_t lastEnd = {};
    int64_t limit = {};
    bool done = {};
    bool operator==(const MatchIter&) const = default;
};

struct replPart {
    vg::Str lit = {};
    int64_t group = {};
    bool operator==(const replPart&) const = default;
};

struct node {
    uint8_t op = {};
    vg::Slice<int32_t> ch = {};
    int32_t r = {};
    vg::Slice<int32_t> fold = {};
    int32_t br = {};
    int64_t min = {};
    int64_t max = {};
    bool minimal = {};
    int64_t vego_index = {};
    int64_t minL = {};
    int64_t maxL = {};
    vg::Slice<int64_t> sufMin = {};
    vg::Slice<int64_t> sufMax = {};
    vg::Slice<vg::Slice<int32_t>> firsts = {};
};

struct parser {
    vg::Str src = {};
    int64_t pos = {};
    uint32_t flags = {};
    int64_t groups = {};
    vg::Slice<node> nodes = {};
    vg::Slice<bracketSet> brackets = {};
    Error err = {};
};

struct interval {
    int64_t lo = {};
    int64_t hi = {};
    bool operator==(const interval&) const = default;
};

struct Tup_Str_bool { vg::Str r0; bool r1; };
struct Tup_Str_t4572726f72x { vg::Str r0; Error r1; };
struct Tup_bool_t4572726f72x { bool r0; Error r1; };
struct Tup_i32_i64 { int32_t r0; int64_t r1; };
struct Tup_i64_bool { int64_t r0; bool r1; };
struct Tup_i64_i64 { int64_t r0; int64_t r1; };
struct Tup_si32_bool { vg::Slice<int32_t> r0; bool r1; };
struct Tup_st7265706c50617274x_t4572726f72x { vg::Slice<replPart> r0; Error r1; };
struct Tup_t4361736550616972x_bool { CasePair r0; bool r1; };
struct Tup_t4c6f63616c65x_bool { Locale r0; bool r1; };
struct Tup_t4d6174636849746572x_t4572726f72x { MatchIter r0; Error r1; };
struct Tup_t526567657870x_t4572726f72x { Regexp r0; Error r1; };
struct Tup_t627261636b65744974656dx_bool { bracketItem r0; bool r1; };
struct Tup_t696e74657276616cx_bool { interval r0; bool r1; };
struct Tup_t6c6f63616c6552657175657374x_bool { localeRequest r0; bool r1; };
struct Tup_t6d656d6f56616cx_bool { memoVal r0; bool r1; };
struct Tup_u32_bool { uint32_t r0; bool r1; };
struct Tup_u8_bool { uint8_t r0; bool r1; };

inline constexpr std::array<vg::Str, numClasses> classNames = std::array<vg::Str, numClasses>{vg::lit("alnum"), vg::lit("alpha"), vg::lit("blank"), vg::lit("cntrl"), vg::lit("digit"), vg::lit("graph"), vg::lit("lower"), vg::lit("print"), vg::lit("punct"), vg::lit("space"), vg::lit("upper"), vg::lit("xdigit")};

int32_t parseBracket(vg::Arena& mem, parser& p, Locale& loc);
Tup_t627261636b65744974656dx_bool parseBracketItem(vg::Arena& mem, parser& p, Locale& loc, int64_t bracketStart);
vg::Str runesToString(vg::Arena& mem, vg::Slice<int32_t> seq);
Tup_si32_bool scanInner(vg::Arena& mem, parser& p, vg::Str closer, int32_t emptyCode);
void sortRanges(vg::Arena& mem, vg::Slice<runeRange> rr);
void finalizeBracket(vg::Arena& mem, bracketSet& b, Locale& loc);
bool bracketInRanges(vg::Slice<bracketSet> brs, int32_t bi, int32_t c);
bool bracketPositiveSingle(vg::Slice<bracketSet> brs, int32_t bi, Locale& loc, int32_t c);
bool bracketMatchesOne(vg::Slice<bracketSet> brs, int32_t bi, Locale& loc, int32_t c);
bool counterpartMatch(vg::Slice<bracketSet> brs, int32_t bi, Locale& loc, int32_t t, int32_t e);
bool bracketHasMultiMembers(vg::Slice<bracketSet> brs, int32_t bi);
bool bracketMatchesMulti(vg::Slice<bracketSet> brs, int32_t bi, Locale& loc, vg::Slice<int32_t> t);
bool equivCandidate(vg::Slice<bracketSet> brs, int32_t bi, Locale& loc, vg::Slice<int32_t> t, elemBuf& candidate, int64_t at);
bool bracketMatchesSpan(vg::Slice<bracketSet> brs, int32_t bi, Locale& loc, vg::Slice<int32_t> runes, int64_t i, int64_t j);
int64_t bracketMinChars(vg::Slice<bracketSet> brs, int32_t bi, Locale& loc);
bool capStep(capSolver& s);
void seedArenas(vg::Arena& mem, capSolver& s);
int32_t newTree(vg::Arena& mem, capSolver& s, ptree t);
int64_t kidAlloc(vg::Arena& mem, capSolver& s, int64_t length);
int64_t kidAlloc1(vg::Arena& mem, capSolver& s, int32_t t);
int64_t kidPrepend(vg::Arena& mem, capSolver& s, int32_t head, int64_t tailOff, int64_t tailLen);
void setMatch(vg::Slice<Match> caps, int64_t idx, int64_t so, int64_t eo);
void addCounters(capSolver& s, Regexp& re, int32_t t, vg::Slice<int64_t> out);
int64_t structCmp(capSolver& s, Regexp& re, int32_t a, int32_t b);
int64_t cmpCand(capSolver& s, Regexp& re, int32_t a, int32_t b);
int32_t bestParse(vg::Arena& mem, capSolver& s, Regexp& re, decoded& d, int32_t ni, int64_t i, int64_t j);
Tup_i64_i64 bestConcat(vg::Arena& mem, capSolver& s, Regexp& re, decoded& d, int32_t ni, int64_t idx, int64_t i, int64_t j);
void repTry(vg::Arena& mem, capSolver& s, Regexp& re, int32_t ni, int64_t i, int64_t j, int64_t off, int64_t length, repBest& best);
repWin bestRep(vg::Arena& mem, capSolver& s, Regexp& re, decoded& d, int32_t ni, int64_t i, int64_t j, int64_t done, bool hasEmpty);
Error solveCaptures(vg::Arena& mem, Regexp& re, decoded& d, int64_t so, int64_t eo, uint32_t eflags, vg::Slice<Match> caps);
void assignCaps(Regexp& re, capSolver& s, int32_t t, vg::Slice<Match> caps);
int64_t cAdd(int64_t a, int64_t b);
int64_t cMul(int64_t a, int64_t b);
int64_t ContractHeapBytes(Contract& c);
int64_t ContractStackBytes(Contract& c);
int64_t ContractSteps(Contract& c);
Contract ContractFor(Regexp& re, int64_t maxInput);
BackendContract matcherContract(Regexp& re, int64_t length, int64_t atom);
int64_t captureHeap(Regexp& re, int64_t length);
BackendContract onePassContract(Regexp& re, int64_t length, int64_t atom);
BackendContract solverContract(Regexp& re, int64_t length, int64_t atom);
int64_t astSize(vg::Slice<node> nodes, int32_t ni);
int64_t astHeight(vg::Slice<node> nodes, int32_t ni);
int64_t atomCost(Regexp& re);
int64_t atomCostNode(vg::Slice<node> nodes, vg::Slice<bracketSet> brs, lookupCosts& lc, int32_t ni);
int64_t searchSteps(int64_t count);
int64_t u32ContainsCost(int64_t count);
int64_t findPairCost(int64_t count);
int64_t findCaseCost(int64_t count);
int64_t pairSourcesRunCost(int64_t count, int64_t preimages);
int64_t compareSequenceCost(int64_t length);
lookupCosts localeLookupCosts(Locale& l);
int64_t elementIDCost(lookupCosts& lc, int64_t length);
int64_t collatingElementIDCost(lookupCosts& lc, int64_t length);
int64_t primaryEqualCost(lookupCosts& lc, int64_t left, int64_t right);
int64_t equivsCost(vg::Slice<bracketSet> brs, int32_t bi, lookupCosts& lc, int64_t length);
int64_t positiveSingleCost(vg::Slice<bracketSet> brs, int32_t bi, lookupCosts& lc);
int64_t matchesOneCost(vg::Slice<bracketSet> brs, int32_t bi, lookupCosts& lc);
int64_t candidateLeafCost(vg::Slice<bracketSet> brs, int32_t bi, lookupCosts& lc, int64_t length);
int64_t probeCost(vg::Slice<bracketSet> brs, int32_t bi, lookupCosts& lc, int64_t length);
int64_t bracketAtomCost(vg::Slice<bracketSet> brs, int32_t bi, lookupCosts& lc);
int64_t solverSteps(vg::Slice<node> nodes, int32_t ni, int64_t length);
int64_t repInstances(vg::Slice<node> nodes, int32_t ni, int64_t length);
int64_t solverDepth(vg::Slice<node> nodes, int32_t ni, int64_t length);
int64_t treeNodes(vg::Slice<node> nodes, int32_t ni, int64_t length);
int64_t solverFanout(vg::Slice<node> nodes, int32_t ni, int64_t length);
void prepare(vg::Arena& mem, engineWS& ws, int64_t n, int64_t k, int64_t ring);
int64_t workspaceHeapBound(int64_t n, int64_t k, int64_t ring);
bool ctrLess(vg::Slice<uint32_t> a, vg::Slice<uint32_t> b);
int64_t trailingZeros64(uint64_t x);
engineResult runPhaseA(vg::Arena& mem, Regexp& re, vg::Str subject, uint32_t eflags);
uint32_t paGen(int64_t boundary);
void paConsider(phaseAState& e, engineWS& ws, int32_t start, vg::Slice<uint32_t> ctr, int64_t end);
bool paPrune(phaseAState& e, engineWS& ws, int32_t start, vg::Slice<uint32_t> ctr);
bool paStore(vg::Arena& mem, phaseAState& e, engineWS& ws, int64_t si, uint32_t pc, int32_t start, vg::Slice<uint32_t> ctr);
void paRelax(vg::Arena& mem, phaseAState& e, engineWS& ws, int64_t si, uint32_t pc, int32_t start, vg::Slice<uint32_t> ctr);
void compactQueue(engineWS& ws);
void paClosure(vg::Arena& mem, phaseAState& e, engineWS& ws, Regexp& re, int64_t si);
void paArrive(vg::Arena& mem, phaseAState& e, engineWS& ws, Regexp& re, uint32_t pc, int64_t delta, int32_t start, vg::Slice<uint32_t> ctr);
void paConsume(vg::Arena& mem, phaseAState& e, engineWS& ws, Regexp& re, int64_t si);
void decodeAhead(vg::Arena& mem, phaseAState& e, engineWS& ws);
int64_t scanAhead(phaseAState& e, Regexp& re);
bool bolAt(phaseAState& e, int32_t prev);
uint32_t continuationFlags(Regexp& re, vg::Str subject, int64_t pos, uint32_t eflags);
void paRun(vg::Arena& mem, phaseAState& e, engineWS& ws, Regexp& re);
Error noError();
Error compileError(int32_t code, int64_t pos);
vg::Str ErrorText(int32_t code);
uint64_t memoHash(memoKey k);
Tup_t6d656d6f56616cx_bool memoGet(memoTab& t, memoKey k);
void memoInsert(memoTab& t, memoKey k, memoVal v);
void memoGrow(vg::Arena& mem, memoTab& t);
void memoPut(vg::Arena& mem, memoTab& t, memoKey k, memoVal v);
Locale LocalePOSIX();
bool LocaleValid(Locale& l);
uint32_t u32Raw(vg::Str blob, int64_t off);
uint16_t u16At(Locale& l, int64_t sec, int64_t vego_index);
uint32_t u32At(Locale& l, int64_t sec, int64_t vego_index);
int64_t sectionLen(Locale& l, int64_t sec);
vg::Str byteString(Locale& l, int64_t sec, int64_t off);
bool localeLoad(Locale& l, vg::Str blob);
bool localeValidate(Locale& l);
bool contractionIDsValid(Locale& l, int64_t sec, int64_t seqCount);
int64_t localeMaxElementLength(Locale& l);
bool validScalar(int32_t r);
uint8_t asciiLower(uint8_t c);
Tup_Str_bool normalizeName(vg::Arena& mem, vg::Str input);
Tup_Str_bool embeddedModifier(vg::Str name);
vg::Str longTypeAlias(vg::Str name);
Tup_Str_bool normalizeType(vg::Arena& mem, vg::Str input);
int64_t findName(Locale& l, vg::Str name, int64_t poolSec, int64_t offsetsSec, int64_t count);
int64_t localesCount(Locale& l);
LocaleRow localeRowAt(Locale& l, int64_t vego_index);
Tup_t6c6f63616c6552657175657374x_bool normalizeRequest(vg::Arena& mem, vg::Str name, vg::Str collationType);
Tup_t4c6f63616c65x_bool posixSelect(vg::Str ctype);
Tup_t4c6f63616c65x_bool LocaleLoad(vg::Str blob);
Tup_t4c6f63616c65x_bool resolveLocale(Locale& data, localeRequest req);
Tup_t4c6f63616c65x_bool LocaleSelect(vg::Arena& mem, Locale& data, vg::Str name, vg::Str collationType);
Tup_t4c6f63616c65x_bool LocaleOpen(vg::Arena& mem, vg::Str blob, vg::Str name, vg::Str collationType);
Tup_u8_bool classByName(vg::Str name);
uint16_t posixMask(int32_t r);
uint16_t localeClassMask(Locale& l, int32_t r);
Tup_t4361736550616972x_bool findCase(Locale& l, int64_t sec, int32_t r);
int32_t caseConvert(Locale& l, int32_t r, bool toUpper);
void pairSourcesRun(Locale& l, preimageBuf& buf, int64_t sec, int32_t r);
int64_t maxPairRun(Locale& l, int64_t sec);
int64_t localeMaxPreimages(Locale& l);
void localeCasePreimages(Locale& l, preimageBuf& buf, int32_t r);
int32_t localeToUpper(Locale& l, int32_t r);
int32_t localeToLower(Locale& l, int32_t r);
int64_t compareSequence(Locale& l, vg::Slice<int32_t> seq, int64_t vego_index);
Tup_u32_bool elementID(Locale& l, vg::Slice<int32_t> seq);
bool u32Contains(Locale& l, int64_t sec, int64_t first, int64_t count, uint32_t needle);
CollProfile collationProfileRow(Locale& l, int64_t vego_index);
bool isContraction(Locale& l, uint32_t element);
Tup_u32_bool collatingElementID(Locale& l, vg::Slice<int32_t> seq);
bool localeIsCollatingElement(Locale& l, vg::Slice<int32_t> seq);
int64_t LocaleCollatingPrefix(Locale& l, vg::Slice<int32_t> seq);
Tup_u32_bool findPair(Locale& l, int64_t sec, int64_t first, int64_t count, uint32_t element);
uint64_t primaryToken(Locale& l, uint32_t element);
bool localePrimaryEqual(Locale& l, vg::Slice<int32_t> left, vg::Slice<int32_t> right);
int64_t localeMinEquivLength(Locale& l, vg::Slice<int32_t> seq);
int64_t minTokenLength(Locale& l, int64_t sec, int64_t first, int64_t count, uint64_t token, int64_t best);
bool localeSupportsRanges(Locale& l);
int64_t LocaleCount(Locale& l);
vg::Str LocaleName(Locale& l, int64_t vego_index);
decoded decodeWindow(vg::Arena& mem, vg::Str s, int64_t so, int64_t eo);
int64_t indexOfByte(vg::Str s, uint8_t c);
bool runesContain(vg::Slice<int32_t> runes, int32_t r);
bool charMatches(Regexp& re, int32_t ni, int32_t c);
bool anyMatches(Regexp& re, int32_t c);
bool atBOL(Regexp& re, decoded& d, int64_t i, uint32_t eflags);
bool atEOL(Regexp& re, decoded& d, int64_t i, uint32_t eflags);
void fillMatches(Regexp& re, decoded& d, vg::Slice<Match> caps, vg::Slice<Match> pmatch);
bool onePassAnalyze(vg::Arena& mem, vg::Slice<node> nodes, vg::Slice<bracketSet> brs, int32_t ni);
bool fixedLength(vg::Slice<node> nodes, int32_t ni);
bool disjointLengths(vg::Slice<node> nodes, int32_t ni);
Tup_si32_bool firstSet(vg::Arena& mem, vg::Slice<node> nodes, int32_t ni);
bool disjointFirsts(vg::Arena& mem, vg::Slice<node> nodes, int32_t ni);
bool onePassCaps(Regexp& re, decoded& d, int32_t ni, int64_t i, int64_t j, uint32_t eflags, vg::Slice<Match> caps);
int64_t buildScanFilter(vg::Arena& mem, program& pr, bool newlineMode);
int64_t instrEstimate(vg::Slice<node> nodes, int32_t ni);
void compileProgram(vg::Arena& mem, progBuilder& b, vg::Slice<node> nodes, int32_t root, bool multi, bool newlineMode);
bool consumingOp(uint8_t op);
Tup_u32_bool progEdge(program& pr, uint32_t pc, int64_t i);
int64_t progDepth(vg::Arena& mem, program& pr);
uint32_t addInstr(vg::Arena& mem, progBuilder& b, instr ins);
void patch(progBuilder& b, vg::Slice<patchSlot> slots, uint32_t target);
vg::Slice<patchSlot> singleOut(vg::Arena& mem, uint32_t idx, bool alt);
frag epsilonFrag(vg::Arena& mem, progBuilder& b);
vg::Slice<uint32_t> copyExtra(vg::Arena& mem, vg::Slice<uint32_t> extra);
frag consumeFrag(vg::Arena& mem, progBuilder& b, uint8_t op, uint32_t arg, uint64_t mask, vg::Slice<uint32_t> extra);
frag emit(vg::Arena& mem, progBuilder& b, vg::Slice<node> nodes, int32_t ni, uint64_t mask, vg::Slice<uint32_t> extra);
frag emitAlt(vg::Arena& mem, progBuilder& b, vg::Slice<node> nodes, int32_t ni, uint64_t mask, vg::Slice<uint32_t> extra);
bool fragAppend(progBuilder& b, frag& result, bool have, frag f);
frag emitRepeat(vg::Arena& mem, progBuilder& b, vg::Slice<node> nodes, int32_t ni, uint64_t mask, vg::Slice<uint32_t> extra);
frag emitStar(vg::Arena& mem, progBuilder& b, vg::Slice<node> nodes, int32_t child, uint64_t mask, vg::Slice<uint32_t> extra);
frag emitPlus(vg::Arena& mem, progBuilder& b, vg::Slice<node> nodes, int32_t child, uint64_t mask, vg::Slice<uint32_t> extra);
void compileScan(Regexp& re, int32_t ni);
void collectNested(vg::Arena& mem, Regexp& re, int32_t ni, groupStack& stack);
int64_t minMatchChars(vg::Slice<node> nodes, vg::Slice<bracketSet> brs, Locale& loc, int32_t ni);
Tup_t526567657870x_t4572726f72x Compile(vg::Arena& mem, vg::Str pattern, Locale loc, uint32_t flags);
int64_t NumSub(Regexp& re);
bool trivialNullMatch(Regexp& re, vg::Slice<Match> pmatch);
Tup_bool_t4572726f72x Exec(vg::Arena& mem, Regexp& re, vg::Str subject, vg::Slice<Match> pmatch, uint32_t eflags);
Tup_t4d6174636849746572x_t4572726f72x MatchIterInit(Regexp& re, int64_t limit);
Tup_bool_t4572726f72x MatchIterNext(vg::Arena& mem, Regexp& re, MatchIter& it, vg::Str subject, uint32_t eflags, vg::Slice<Match> pmatch);
Tup_st7265706c50617274x_t4572726f72x parseReplacement(vg::Arena& mem, vg::Str replacement, int64_t nsub);
Tup_Str_t4572726f72x ReplaceAll(vg::Arena& mem, Regexp& re, vg::Str subject, vg::Str replacement, int64_t limit, uint32_t eflags);
int32_t fail(parser& p, int32_t code, int64_t pos);
int32_t addNode(vg::Arena& mem, parser& p, uint8_t op);
bool eof(parser& p);
uint8_t peekByte(parser& p);
uint8_t peekByteAt(parser& p, int64_t ahead);
int32_t nextRune(parser& p);
int32_t parse(vg::Arena& mem, parser& p, Locale& loc, vg::Str pattern, uint32_t flags);
int32_t parseAlt(vg::Arena& mem, parser& p, Locale& loc, bool inGroup);
int32_t parseBranch(vg::Arena& mem, parser& p, Locale& loc, bool inGroup);
bool isDupByte(uint8_t c);
int32_t parseExpr(vg::Arena& mem, parser& p, Locale& loc);
int32_t charNode(vg::Arena& mem, parser& p, Locale& loc, int32_t r);
vg::Slice<int32_t> appendUnique(vg::Arena& mem, vg::Slice<int32_t> runes, int32_t r);
int32_t parseDup(vg::Arena& mem, parser& p, int32_t operand);
Tup_t696e74657276616cx_bool parseInterval(parser& p);
void intervalError(parser& p, int64_t start);
Tup_i64_bool parseCount(parser& p);
int64_t satAdd(int64_t a, int64_t b);
int64_t satMul(int64_t a, int64_t b);
void computeLengths(vg::Arena& mem, vg::Slice<node> nodes, Locale& loc, vg::Slice<bracketSet> brackets, int32_t ni);
bool utf8Cont(uint8_t c);
Tup_i32_i64 decodeRuneAt(vg::Str s, int64_t at);
int64_t runeCount(vg::Str s);
uint8_t utf8LeadByte(int32_t r);

} // namespace revera::engine
