// Code generated by vegoc from the Vego JSON form. DO NOT EDIT.

#include "probe_engine.h"

int64_t probe_bump(vg_arena *mem, probe_Counter *c, int32_t tag) {
    c->n += 1LL;
    c->log = probe_slice_i32_append(mem, c->log, tag);
    return ((int64_t)(tag));
}

int64_t probe_logCode(probe_Counter *c) {
    int64_t v = 0LL;
    {
        int64_t i = 0LL;
        for (; (i < (c->log).len); i += 1LL) {
            v = ((v * 10LL) + ((int64_t)((*probe_slice_i32_at(c->log, i)))));
        }
    }
    return ((v * 100LL) + ((int64_t)(c->n)));
}

probe_Tup_i64_i64 probe_DivMod(int64_t a, int64_t b) {
    return (probe_Tup_i64_i64){vg_sdiv_i64(a, b), vg_srem_i64(a, b)};
}

probe_Tup_i32_i32 probe_DivMod32(int32_t a, int32_t b) {
    return (probe_Tup_i32_i32){vg_sdiv_i32(a, b), vg_srem_i32(a, b)};
}

int64_t probe_BytesProbe(vg_arena *mem, vg_str s) {
    probe_slice_u8 b = probe_bytes_from_str(mem, s);
    if (((b).len > 0LL)) {
        (*probe_slice_u8_at(b, 0LL)) = 88;
    }
    int64_t t = 0LL;
    {
        int64_t i = 0LL;
        for (; (i < (b).len); i += 1LL) {
            t = ((t * 31LL) + ((int64_t)((*probe_slice_u8_at(b, i)))));
        }
    }
    return t;
}

probe_slice_i32 probe_sliceFrom(vg_arena *mem, probe_Counter *c, int64_t n) {
    c->n += 1LL;
    probe_slice_i32 out = probe_slice_i32_make(mem, n);
    {
        int64_t i = 0LL;
        for (; (i < n); i += 1LL) {
            (*probe_slice_i32_at(out, i)) = ((int32_t)((i + 1LL)));
        }
    }
    return out;
}

int64_t probe_RangeProbe(vg_arena *mem, probe_Counter *c) {
    int64_t t = 0LL;
    {
        probe_slice_i32 _t1 = probe_sliceFrom(mem, c, 4LL);
        for (int64_t _t2 = 0; _t2 < _t1.len; _t2++) {
            int64_t i = _t2;
            int32_t v = (*probe_slice_i32_at(_t1, _t2));
            t += (((int64_t)(i)) * ((int64_t)(v)));
            i = 100LL;
        }
    }
    return ((t * 10LL) + ((int64_t)(c->n)));
}

int64_t probe_RangeValProbe(probe_slice_i32 xs) {
    int64_t t = 0LL;
    {
        probe_slice_i32 _t1 = xs;
        for (int64_t _t2 = 0; _t2 < _t1.len; _t2++) {
            int32_t v = (*probe_slice_i32_at(_t1, _t2));
            v = ((int32_t)(v + 1));
            t += ((int64_t)(v));
        }
    }
    {
        int64_t i = 0LL;
        for (; (i < (xs).len); i += 1LL) {
            t += (((int64_t)((*probe_slice_i32_at(xs, i)))) * 100LL);
        }
    }
    return t;
}

int64_t probe_RangeIntProbe(int64_t n) {
    int64_t t = 0LL;
    {
        int64_t _t1 = n;
        for (int64_t _t2 = 0; _t2 < _t1; _t2++) {
            int64_t i = _t2;
            t = ((t * 2LL) + ((int64_t)(i)));
        }
    }
    return t;
}

int64_t probe_PartialArray(void) {
    probe_arr_i64_5 a = ((probe_arr_i64_5){.v = {7LL, 9LL}});
    probe_arr_Str_3 names = ((probe_arr_Str_3){.v = {vg_lit("a")}});
    int64_t t = 0LL;
    {
        int64_t i = 0LL;
        for (; (i < 5LL); i += 1LL) {
            t = ((t * 10LL) + a.v[i]);
        }
    }
    return (((t * 10LL) + ((int64_t)((names.v[1LL]).len))) + ((int64_t)((names.v[0LL]).len)));
}

bool probe_TaggedEq(probe_Tagged a, probe_Tagged b) {
    return (probe_Tagged_eq(a, b));
}

int64_t probe_three(int64_t a, int64_t b, int64_t x) {
    return (((a * 100LL) + (b * 10LL)) + x);
}

int64_t probe_OrderArgs(vg_arena *mem, probe_Counter *c) {
    int64_t _t1 = probe_bump(mem, c, 1);
    int64_t _t2 = probe_bump(mem, c, 2);
    int64_t _t3 = probe_bump(mem, c, 3);
    int64_t _t4 = probe_three(_t1, _t2, _t3);
    int64_t _t5 = probe_logCode(c);
    return (_t4 + _t5);
}

int64_t probe_OrderBinary(vg_arena *mem, probe_Counter *c) {
    int64_t _t1 = probe_bump(mem, c, 4);
    int64_t _t2 = (2LL * probe_bump(mem, c, 5));
    int64_t v = (_t1 - _t2);
    int64_t _t3 = (v * 10000LL);
    int64_t _t4 = probe_logCode(c);
    return (_t3 + _t4);
}

int64_t probe_OrderIndex(vg_arena *mem, probe_Counter *c) {
    probe_slice_i32 s = probe_sliceFrom(mem, c, 6LL);
    probe_slice_i32 _t1 = s;
    int64_t _t2 = probe_bump(mem, c, 2);
    int64_t v = ((int64_t)((*probe_slice_i32_at(_t1, _t2))));
    int64_t _t3 = (v * 10000LL);
    int64_t _t4 = probe_logCode(c);
    return (_t3 + _t4);
}

int64_t probe_SpareProbe(vg_arena *mem) {
    probe_slice_i64 s = probe_slice_i64_make_cap(mem, 0LL, 4LL);
    s = probe_slice_i64_append(mem, s, 5LL);
    s = probe_slice_i64_head(s, 4LL);
    int64_t t = 0LL;
    {
        int64_t i = 0LL;
        for (; (i < (s).len); i += 1LL) {
            t = (((t * 10LL) + (*probe_slice_i64_at(s, i))) + 1LL);
        }
    }
    probe_slice_i64 g = probe_slice_i64_make_cap(mem, 0LL, 2LL);
    g = probe_slice_i64_append(mem, g, 1LL);
    g = probe_slice_i64_append(mem, g, 2LL);
    g = probe_slice_i64_append(mem, g, 3LL);
    if (((g).cap >= 4LL)) {
        g = probe_slice_i64_head(g, 4LL);
    }
    {
        int64_t i_2 = 0LL;
        for (; (i_2 < 4LL); i_2 += 1LL) {
            t = (((t * 10LL) + (*probe_slice_i64_at(g, i_2))) + 1LL);
        }
    }
    return t;
}

int64_t probe_NilProbe(vg_arena *mem) {
    probe_slice_i32 s = {0};
    int64_t t = 0LL;
    if (((s).p == NULL)) {
        t += 1LL;
    }
    probe_slice_i32 s2 = probe_slice_i32_make(mem, 0LL);
    if (((s2).p != NULL)) {
        t += 2LL;
    }
    s = probe_slice_i32_append(mem, s, 5);
    if (((s).p != NULL)) {
        t += 4LL;
    }
    return t;
}

int64_t probe_WrapProbe(int64_t a, int64_t b) {
    return (((a * b) + a) - b);
}

int32_t probe_Narrow32(int32_t a, int32_t b) {
    return ((int32_t)(((int32_t)(((int32_t)(a * b)) - vg_sdiv_i32(a, b))) + vg_srem_i32(a, b)));
}

uint8_t probe_WrapU8(uint8_t a, uint8_t b) {
    return ((uint8_t)(((uint8_t)(a - b)) * 3));
}

uint32_t probe_AndNotProbe(uint32_t a, uint32_t b) {
    uint32_t a_v = a;
    a_v &= ~(b);
    return ((uint32_t)(a_v & ~(((uint32_t)(b >> 1LL)))));
}

uint64_t probe_ShiftProbe(uint64_t x, int64_t n) {
    return ((x << n) >> vg_sdiv_i64(n, 2LL));
}

uint64_t probe_ConvProbe(int64_t x) {
    return (((uint64_t)(((uint8_t)(x)))) + (((uint64_t)(((uint32_t)(((int32_t)(x)))))) * 1000ULL));
}

int64_t probe_SubWrite(vg_arena *mem, int64_t n) {
    probe_slice_i64 s = probe_slice_i64_make(mem, n);
    (*probe_slice_i64_at(probe_slice_i64_tail(s, 1LL), 0LL)) = 7LL;
    (*probe_slice_i64_at(probe_slice_i64_tail(probe_slice_i64_tail(s, 1LL), 1LL), 0LL)) = 9LL;
    int64_t t = 0LL;
    {
        int64_t i = 0LL;
        for (; (i < (s).len); i += 1LL) {
            t = ((t * 10LL) + (*probe_slice_i64_at(s, i)));
        }
    }
    return t;
}

int64_t probe_AndNotOrder(vg_arena *mem, probe_Counter *c) {
    probe_slice_u64 s = probe_slice_u64_make(mem, 8LL);
    (*probe_slice_u64_at(s, 3LL)) = 255ULL;
    probe_slice_u64 _t1 = s;
    int64_t _t2 = (probe_bump(mem, c, 1) + 2LL);
    uint64_t *_t3 = &((*probe_slice_u64_at(_t1, _t2)));
    (*_t3) &= ~((((uint64_t)(probe_bump(mem, c, 2))) + 15ULL));
    int64_t _t4 = (((int64_t)((*probe_slice_u64_at(s, 3LL)))) * 100000LL);
    int64_t _t5 = probe_logCode(c);
    return (_t4 + _t5);
}

int64_t probe_ZeroArray(void) {
    probe_arr_i32_0 a = {0};
    int64_t t = 0LL;
    if (((probe_arr_i32_0_slice(&(a), 0, 0)).p != NULL)) {
        t += 1LL;
    }
    t = ((t * 10LL) + ((int64_t)((probe_arr_i32_0_slice(&(a), 0, 0)).len)));
    return t;
}

int64_t probe_MakeU64(vg_arena *mem, uint64_t n) {
    probe_slice_i32 s = probe_slice_i32_make(mem, n);
    return ((int64_t)((s).len));
}

probe_arr_i64_3 probe_mkTriple(int64_t x) {
    probe_arr_i64_3 a = {0};
    a.v[0LL] = x;
    a.v[1LL] = (x + 1LL);
    a.v[2LL] = (x + 2LL);
    return a;
}

int64_t probe_PickArray(vg_arena *mem, probe_Counter *c) {
    probe_arr_i64_3 _t1 = probe_mkTriple(40LL);
    int64_t _t2 = probe_bump(mem, c, 2);
    int64_t v = _t1.v[_t2];
    int64_t _t3 = (v * 10000LL);
    int64_t _t4 = probe_logCode(c);
    return (_t3 + _t4);
}

