// Code generated by vegoc from the Vego JSON form. DO NOT EDIT.

#ifndef PROBE_PROBE_ENGINE_H
#define PROBE_PROBE_ENGINE_H

#include "vg.h"

#define probe_minI64 ((int64_t)(((int64_t)(0ULL - (uint64_t)(((int64_t)9223372036854775808ULL))))))

typedef struct probe_Counter probe_Counter;
typedef struct probe_Tagged probe_Tagged;
typedef struct probe_arr_Str_2 probe_arr_Str_2;
typedef struct probe_arr_i64_5 probe_arr_i64_5;
typedef struct probe_arr_Str_3 probe_arr_Str_3;
typedef struct probe_arr_i32_0 probe_arr_i32_0;
typedef struct probe_arr_i64_3 probe_arr_i64_3;

typedef struct {
    int32_t *p;
    int64_t len;
    int64_t cap;
} probe_slice_i32;

typedef struct {
    uint8_t *p;
    int64_t len;
    int64_t cap;
} probe_slice_u8;

typedef struct {
    int64_t *p;
    int64_t len;
    int64_t cap;
} probe_slice_i64;

typedef struct {
    uint64_t *p;
    int64_t len;
    int64_t cap;
} probe_slice_u64;

struct probe_Counter {
    int64_t n;
    probe_slice_i32 log;
};

struct probe_arr_Str_2 {
    vg_str v[2];
};

struct probe_Tagged {
    probe_arr_Str_2 Tags;
    int32_t N;
};

struct probe_arr_i64_5 {
    int64_t v[5];
};

struct probe_arr_Str_3 {
    vg_str v[3];
};

struct probe_arr_i32_0 {
    int32_t v[1];
};

struct probe_arr_i64_3 {
    int64_t v[3];
};

typedef struct {
    int32_t r0;
    int32_t r1;
} probe_Tup_i32_i32;

typedef struct {
    int64_t r0;
    int64_t r1;
} probe_Tup_i64_i64;

static inline bool probe_Tagged_eq(probe_Tagged a, probe_Tagged b);
static inline bool probe_arr_Str_2_eq(probe_arr_Str_2 a, probe_arr_Str_2 b);
static inline bool probe_arr_i64_5_eq(probe_arr_i64_5 a, probe_arr_i64_5 b);
static inline bool probe_arr_Str_3_eq(probe_arr_Str_3 a, probe_arr_Str_3 b);
static inline bool probe_arr_i32_0_eq(probe_arr_i32_0 a, probe_arr_i32_0 b);
static inline bool probe_arr_i64_3_eq(probe_arr_i64_3 a, probe_arr_i64_3 b);

static inline bool probe_Tagged_eq(probe_Tagged a, probe_Tagged b) {
    return probe_arr_Str_2_eq(a.Tags, b.Tags) && a.N == b.N;
}

static inline bool probe_arr_Str_2_eq(probe_arr_Str_2 a, probe_arr_Str_2 b) {
    for (int64_t i = 0; i < 2; i++) {
        if (!(vg_streq(a.v[i], b.v[i]))) {
            return false;
        }
    }
    return true;
}

static inline bool probe_arr_i64_5_eq(probe_arr_i64_5 a, probe_arr_i64_5 b) {
    for (int64_t i = 0; i < 5; i++) {
        if (!(a.v[i] == b.v[i])) {
            return false;
        }
    }
    return true;
}

static inline bool probe_arr_Str_3_eq(probe_arr_Str_3 a, probe_arr_Str_3 b) {
    for (int64_t i = 0; i < 3; i++) {
        if (!(vg_streq(a.v[i], b.v[i]))) {
            return false;
        }
    }
    return true;
}

static inline bool probe_arr_i32_0_eq(probe_arr_i32_0 a, probe_arr_i32_0 b) {
    (void)a;
    (void)b;
    return true;
}

static inline bool probe_arr_i64_3_eq(probe_arr_i64_3 a, probe_arr_i64_3 b) {
    for (int64_t i = 0; i < 3; i++) {
        if (!(a.v[i] == b.v[i])) {
            return false;
        }
    }
    return true;
}

static inline probe_slice_i32 probe_slice_i32_make_cap(vg_arena *mem, int64_t n, int64_t c) {
    assert(0 <= n && n <= c);
    int32_t *p = (int32_t *)vg_arena_alloc(mem, (size_t)(c < 1 ? 1 : c) * sizeof(int32_t));
    memset(p, 0, (size_t)c * sizeof(int32_t));
    return (probe_slice_i32){p, n, c};
}

static inline probe_slice_i32 probe_slice_i32_make(vg_arena *mem, int64_t n) {
    return probe_slice_i32_make_cap(mem, n, n);
}

static inline probe_slice_i32 probe_slice_i32_grow(vg_arena *mem, probe_slice_i32 s, int64_t need) {
    int64_t newcap = s.cap * 2 < 8 ? 8 : s.cap * 2;
    if (newcap < need) {
        newcap = need;
    }
    int32_t *p = (int32_t *)vg_arena_alloc(mem, (size_t)newcap * sizeof(int32_t));
    memset(p + s.len, 0, (size_t)(newcap - s.len) * sizeof(int32_t));
    if (s.p != NULL && s.len > 0) {
        memcpy(p, s.p, (size_t)s.len * sizeof(int32_t));
    }
    return (probe_slice_i32){p, s.len, newcap};
}

static inline probe_slice_i32 probe_slice_i32_append(vg_arena *mem, probe_slice_i32 s, int32_t v) {
    if (s.len == s.cap) {
        s = probe_slice_i32_grow(mem, s, s.len + 1);
    }
    s.p[s.len] = v;
    s.len++;
    return s;
}

static inline probe_slice_i32 probe_slice_i32_append_slice(vg_arena *mem, probe_slice_i32 s, probe_slice_i32 more) {
    if (s.len + more.len > s.cap) {
        s = probe_slice_i32_grow(mem, s, s.len + more.len);
    }
    if (more.len > 0) {
        memmove(s.p + s.len, more.p, (size_t)more.len * sizeof(int32_t));
    }
    s.len += more.len;
    return s;
}

static inline probe_slice_i32 probe_slice_i32_sub(probe_slice_i32 s, int64_t lo, int64_t hi) {
    assert(0 <= lo && lo <= hi && hi <= s.cap);
    if (s.p == NULL) {
        return (probe_slice_i32){0};
    }
    return (probe_slice_i32){s.p + lo, hi - lo, s.cap - lo};
}

static inline probe_slice_i32 probe_slice_i32_tail(probe_slice_i32 s, int64_t lo) {
    return probe_slice_i32_sub(s, lo, s.len);
}

static inline probe_slice_i32 probe_slice_i32_head(probe_slice_i32 s, int64_t hi) {
    return probe_slice_i32_sub(s, 0, hi);
}

static inline int32_t *probe_slice_i32_at(probe_slice_i32 s, int64_t i) {
    assert(i >= 0 && i < s.len);
    return &s.p[i];
}

static inline int64_t probe_slice_i32_copy(probe_slice_i32 dst, probe_slice_i32 src) {
    int64_t n = dst.len < src.len ? dst.len : src.len;
    if (n > 0) {
        memmove(dst.p, src.p, (size_t)n * sizeof(int32_t));
    }
    return n;
}

static inline probe_slice_i32 probe_slice_i32_of(vg_arena *mem, const int32_t *elems, int64_t n) {
    probe_slice_i32 out = probe_slice_i32_make(mem, n);
    if (n > 0) {
        memcpy(out.p, elems, (size_t)n * sizeof(int32_t));
    }
    return out;
}

static inline probe_slice_u8 probe_slice_u8_make_cap(vg_arena *mem, int64_t n, int64_t c) {
    assert(0 <= n && n <= c);
    uint8_t *p = (uint8_t *)vg_arena_alloc(mem, (size_t)(c < 1 ? 1 : c) * sizeof(uint8_t));
    memset(p, 0, (size_t)c * sizeof(uint8_t));
    return (probe_slice_u8){p, n, c};
}

static inline probe_slice_u8 probe_slice_u8_make(vg_arena *mem, int64_t n) {
    return probe_slice_u8_make_cap(mem, n, n);
}

static inline probe_slice_u8 probe_slice_u8_grow(vg_arena *mem, probe_slice_u8 s, int64_t need) {
    int64_t newcap = s.cap * 2 < 8 ? 8 : s.cap * 2;
    if (newcap < need) {
        newcap = need;
    }
    uint8_t *p = (uint8_t *)vg_arena_alloc(mem, (size_t)newcap * sizeof(uint8_t));
    memset(p + s.len, 0, (size_t)(newcap - s.len) * sizeof(uint8_t));
    if (s.p != NULL && s.len > 0) {
        memcpy(p, s.p, (size_t)s.len * sizeof(uint8_t));
    }
    return (probe_slice_u8){p, s.len, newcap};
}

static inline probe_slice_u8 probe_slice_u8_append(vg_arena *mem, probe_slice_u8 s, uint8_t v) {
    if (s.len == s.cap) {
        s = probe_slice_u8_grow(mem, s, s.len + 1);
    }
    s.p[s.len] = v;
    s.len++;
    return s;
}

static inline probe_slice_u8 probe_slice_u8_append_slice(vg_arena *mem, probe_slice_u8 s, probe_slice_u8 more) {
    if (s.len + more.len > s.cap) {
        s = probe_slice_u8_grow(mem, s, s.len + more.len);
    }
    if (more.len > 0) {
        memmove(s.p + s.len, more.p, (size_t)more.len * sizeof(uint8_t));
    }
    s.len += more.len;
    return s;
}

static inline probe_slice_u8 probe_slice_u8_sub(probe_slice_u8 s, int64_t lo, int64_t hi) {
    assert(0 <= lo && lo <= hi && hi <= s.cap);
    if (s.p == NULL) {
        return (probe_slice_u8){0};
    }
    return (probe_slice_u8){s.p + lo, hi - lo, s.cap - lo};
}

static inline probe_slice_u8 probe_slice_u8_tail(probe_slice_u8 s, int64_t lo) {
    return probe_slice_u8_sub(s, lo, s.len);
}

static inline probe_slice_u8 probe_slice_u8_head(probe_slice_u8 s, int64_t hi) {
    return probe_slice_u8_sub(s, 0, hi);
}

static inline uint8_t *probe_slice_u8_at(probe_slice_u8 s, int64_t i) {
    assert(i >= 0 && i < s.len);
    return &s.p[i];
}

static inline int64_t probe_slice_u8_copy(probe_slice_u8 dst, probe_slice_u8 src) {
    int64_t n = dst.len < src.len ? dst.len : src.len;
    if (n > 0) {
        memmove(dst.p, src.p, (size_t)n * sizeof(uint8_t));
    }
    return n;
}

static inline probe_slice_u8 probe_slice_u8_of(vg_arena *mem, const uint8_t *elems, int64_t n) {
    probe_slice_u8 out = probe_slice_u8_make(mem, n);
    if (n > 0) {
        memcpy(out.p, elems, (size_t)n * sizeof(uint8_t));
    }
    return out;
}

static inline probe_slice_u8 probe_bytes_from_str(vg_arena *mem, vg_str v) {
    probe_slice_u8 out = probe_slice_u8_make(mem, v.len);
    if (v.len > 0) {
        memcpy(out.p, v.p, (size_t)v.len);
    }
    return out;
}

static inline vg_str probe_str_from_bytes(vg_arena *mem, probe_slice_u8 b) {
    char *p = (char *)vg_arena_alloc(mem, (size_t)(b.len < 1 ? 1 : b.len));
    if (b.len > 0) {
        memcpy(p, b.p, (size_t)b.len);
    }
    return (vg_str){p, b.len};
}

static inline probe_slice_u8 probe_slice_u8_append_str(vg_arena *mem, probe_slice_u8 s, vg_str more) {
    if (s.len + more.len > s.cap) {
        s = probe_slice_u8_grow(mem, s, s.len + more.len);
    }
    if (more.len > 0) {
        memmove(s.p + s.len, more.p, (size_t)more.len);
    }
    s.len += more.len;
    return s;
}

static inline int64_t probe_slice_u8_copy_str(probe_slice_u8 dst, vg_str src) {
    int64_t n = dst.len < src.len ? dst.len : src.len;
    if (n > 0) {
        memmove(dst.p, src.p, (size_t)n);
    }
    return n;
}

static inline probe_slice_i64 probe_slice_i64_make_cap(vg_arena *mem, int64_t n, int64_t c) {
    assert(0 <= n && n <= c);
    int64_t *p = (int64_t *)vg_arena_alloc(mem, (size_t)(c < 1 ? 1 : c) * sizeof(int64_t));
    memset(p, 0, (size_t)c * sizeof(int64_t));
    return (probe_slice_i64){p, n, c};
}

static inline probe_slice_i64 probe_slice_i64_make(vg_arena *mem, int64_t n) {
    return probe_slice_i64_make_cap(mem, n, n);
}

static inline probe_slice_i64 probe_slice_i64_grow(vg_arena *mem, probe_slice_i64 s, int64_t need) {
    int64_t newcap = s.cap * 2 < 8 ? 8 : s.cap * 2;
    if (newcap < need) {
        newcap = need;
    }
    int64_t *p = (int64_t *)vg_arena_alloc(mem, (size_t)newcap * sizeof(int64_t));
    memset(p + s.len, 0, (size_t)(newcap - s.len) * sizeof(int64_t));
    if (s.p != NULL && s.len > 0) {
        memcpy(p, s.p, (size_t)s.len * sizeof(int64_t));
    }
    return (probe_slice_i64){p, s.len, newcap};
}

static inline probe_slice_i64 probe_slice_i64_append(vg_arena *mem, probe_slice_i64 s, int64_t v) {
    if (s.len == s.cap) {
        s = probe_slice_i64_grow(mem, s, s.len + 1);
    }
    s.p[s.len] = v;
    s.len++;
    return s;
}

static inline probe_slice_i64 probe_slice_i64_append_slice(vg_arena *mem, probe_slice_i64 s, probe_slice_i64 more) {
    if (s.len + more.len > s.cap) {
        s = probe_slice_i64_grow(mem, s, s.len + more.len);
    }
    if (more.len > 0) {
        memmove(s.p + s.len, more.p, (size_t)more.len * sizeof(int64_t));
    }
    s.len += more.len;
    return s;
}

static inline probe_slice_i64 probe_slice_i64_sub(probe_slice_i64 s, int64_t lo, int64_t hi) {
    assert(0 <= lo && lo <= hi && hi <= s.cap);
    if (s.p == NULL) {
        return (probe_slice_i64){0};
    }
    return (probe_slice_i64){s.p + lo, hi - lo, s.cap - lo};
}

static inline probe_slice_i64 probe_slice_i64_tail(probe_slice_i64 s, int64_t lo) {
    return probe_slice_i64_sub(s, lo, s.len);
}

static inline probe_slice_i64 probe_slice_i64_head(probe_slice_i64 s, int64_t hi) {
    return probe_slice_i64_sub(s, 0, hi);
}

static inline int64_t *probe_slice_i64_at(probe_slice_i64 s, int64_t i) {
    assert(i >= 0 && i < s.len);
    return &s.p[i];
}

static inline int64_t probe_slice_i64_copy(probe_slice_i64 dst, probe_slice_i64 src) {
    int64_t n = dst.len < src.len ? dst.len : src.len;
    if (n > 0) {
        memmove(dst.p, src.p, (size_t)n * sizeof(int64_t));
    }
    return n;
}

static inline probe_slice_i64 probe_slice_i64_of(vg_arena *mem, const int64_t *elems, int64_t n) {
    probe_slice_i64 out = probe_slice_i64_make(mem, n);
    if (n > 0) {
        memcpy(out.p, elems, (size_t)n * sizeof(int64_t));
    }
    return out;
}

static inline probe_slice_u64 probe_slice_u64_make_cap(vg_arena *mem, int64_t n, int64_t c) {
    assert(0 <= n && n <= c);
    uint64_t *p = (uint64_t *)vg_arena_alloc(mem, (size_t)(c < 1 ? 1 : c) * sizeof(uint64_t));
    memset(p, 0, (size_t)c * sizeof(uint64_t));
    return (probe_slice_u64){p, n, c};
}

static inline probe_slice_u64 probe_slice_u64_make(vg_arena *mem, int64_t n) {
    return probe_slice_u64_make_cap(mem, n, n);
}

static inline probe_slice_u64 probe_slice_u64_grow(vg_arena *mem, probe_slice_u64 s, int64_t need) {
    int64_t newcap = s.cap * 2 < 8 ? 8 : s.cap * 2;
    if (newcap < need) {
        newcap = need;
    }
    uint64_t *p = (uint64_t *)vg_arena_alloc(mem, (size_t)newcap * sizeof(uint64_t));
    memset(p + s.len, 0, (size_t)(newcap - s.len) * sizeof(uint64_t));
    if (s.p != NULL && s.len > 0) {
        memcpy(p, s.p, (size_t)s.len * sizeof(uint64_t));
    }
    return (probe_slice_u64){p, s.len, newcap};
}

static inline probe_slice_u64 probe_slice_u64_append(vg_arena *mem, probe_slice_u64 s, uint64_t v) {
    if (s.len == s.cap) {
        s = probe_slice_u64_grow(mem, s, s.len + 1);
    }
    s.p[s.len] = v;
    s.len++;
    return s;
}

static inline probe_slice_u64 probe_slice_u64_append_slice(vg_arena *mem, probe_slice_u64 s, probe_slice_u64 more) {
    if (s.len + more.len > s.cap) {
        s = probe_slice_u64_grow(mem, s, s.len + more.len);
    }
    if (more.len > 0) {
        memmove(s.p + s.len, more.p, (size_t)more.len * sizeof(uint64_t));
    }
    s.len += more.len;
    return s;
}

static inline probe_slice_u64 probe_slice_u64_sub(probe_slice_u64 s, int64_t lo, int64_t hi) {
    assert(0 <= lo && lo <= hi && hi <= s.cap);
    if (s.p == NULL) {
        return (probe_slice_u64){0};
    }
    return (probe_slice_u64){s.p + lo, hi - lo, s.cap - lo};
}

static inline probe_slice_u64 probe_slice_u64_tail(probe_slice_u64 s, int64_t lo) {
    return probe_slice_u64_sub(s, lo, s.len);
}

static inline probe_slice_u64 probe_slice_u64_head(probe_slice_u64 s, int64_t hi) {
    return probe_slice_u64_sub(s, 0, hi);
}

static inline uint64_t *probe_slice_u64_at(probe_slice_u64 s, int64_t i) {
    assert(i >= 0 && i < s.len);
    return &s.p[i];
}

static inline int64_t probe_slice_u64_copy(probe_slice_u64 dst, probe_slice_u64 src) {
    int64_t n = dst.len < src.len ? dst.len : src.len;
    if (n > 0) {
        memmove(dst.p, src.p, (size_t)n * sizeof(uint64_t));
    }
    return n;
}

static inline probe_slice_u64 probe_slice_u64_of(vg_arena *mem, const uint64_t *elems, int64_t n) {
    probe_slice_u64 out = probe_slice_u64_make(mem, n);
    if (n > 0) {
        memcpy(out.p, elems, (size_t)n * sizeof(uint64_t));
    }
    return out;
}

static inline probe_slice_i64 probe_arr_i64_5_slice(probe_arr_i64_5 *a, int64_t lo, int64_t hi) {
    assert(0 <= lo && lo <= hi && hi <= 5);
    return (probe_slice_i64){a->v + lo, hi - lo, 5 - lo};
}

static inline probe_slice_i32 probe_arr_i32_0_slice(probe_arr_i32_0 *a, int64_t lo, int64_t hi) {
    assert(0 <= lo && lo <= hi && hi <= 0);
    return (probe_slice_i32){(int32_t *)(void *)a, 0, 0};
}

static inline probe_slice_i64 probe_arr_i64_3_slice(probe_arr_i64_3 *a, int64_t lo, int64_t hi) {
    assert(0 <= lo && lo <= hi && hi <= 3);
    return (probe_slice_i64){a->v + lo, hi - lo, 3 - lo};
}

int64_t probe_bump(vg_arena *mem, probe_Counter *c, int32_t tag);
int64_t probe_logCode(probe_Counter *c);
probe_Tup_i64_i64 probe_DivMod(int64_t a, int64_t b);
probe_Tup_i32_i32 probe_DivMod32(int32_t a, int32_t b);
int64_t probe_BytesProbe(vg_arena *mem, vg_str s);
probe_slice_i32 probe_sliceFrom(vg_arena *mem, probe_Counter *c, int64_t n);
int64_t probe_RangeProbe(vg_arena *mem, probe_Counter *c);
int64_t probe_RangeValProbe(probe_slice_i32 xs);
int64_t probe_RangeIntProbe(int64_t n);
int64_t probe_PartialArray(void);
bool probe_TaggedEq(probe_Tagged a, probe_Tagged b);
int64_t probe_three(int64_t a, int64_t b, int64_t x);
int64_t probe_OrderArgs(vg_arena *mem, probe_Counter *c);
int64_t probe_OrderBinary(vg_arena *mem, probe_Counter *c);
int64_t probe_OrderIndex(vg_arena *mem, probe_Counter *c);
int64_t probe_SpareProbe(vg_arena *mem);
int64_t probe_NilProbe(vg_arena *mem);
int64_t probe_WrapProbe(int64_t a, int64_t b);
int32_t probe_Narrow32(int32_t a, int32_t b);
uint8_t probe_WrapU8(uint8_t a, uint8_t b);
uint32_t probe_AndNotProbe(uint32_t a, uint32_t b);
uint64_t probe_ShiftProbe(uint64_t x, int64_t n);
uint64_t probe_ConvProbe(int64_t x);
int64_t probe_SubWrite(vg_arena *mem, int64_t n);
int64_t probe_AndNotOrder(vg_arena *mem, probe_Counter *c);
int64_t probe_ZeroArray(void);
int64_t probe_MakeU64(vg_arena *mem, uint64_t n);
probe_arr_i64_3 probe_mkTriple(int64_t x);
int64_t probe_PickArray(vg_arena *mem, probe_Counter *c);

#endif
