// Code generated by json2cpp from the Vego JSON form. DO NOT EDIT.

#include "probe_engine.hpp"

namespace probe {

int64_t bump(Counter& c, int32_t tag) {
    c.n += 1LL;
    c.log = vg::append(c.log, tag);
    return int64_t(tag);
}

int64_t logCode(Counter& c) {
    int64_t v = int64_t(0LL);
    for (int64_t i = 0LL; (i < vg::len(c.log)); i += 1LL) {
        v = ((v * 10LL) + int64_t(c.log[i]));
    }
    return ((v * 100LL) + int64_t(c.n));
}

Tup_i64_i64 DivMod(int64_t a, int64_t b) {
    return Tup_i64_i64{vg::sdiv<int64_t>(a, b), vg::srem<int64_t>(a, b)};
}

Tup_i32_i32 DivMod32(int32_t a, int32_t b) {
    return Tup_i32_i32{vg::sdiv<int32_t>(a, b), vg::srem<int32_t>(a, b)};
}

int64_t BytesProbe(vg::Str s) {
    vg::Slice<uint8_t> b = vg::bytes_from_str(s);
    if ((vg::len(b) > 0LL)) {
        b[0LL] = 88;
    }
    int64_t t = int64_t(0LL);
    for (int64_t i = 0LL; (i < vg::len(b)); i += 1LL) {
        t = ((t * 31LL) + int64_t(b[i]));
    }
    return t;
}

vg::Slice<int32_t> sliceFrom(Counter& c, int64_t n) {
    c.n += 1LL;
    vg::Slice<int32_t> out = vg::make<int32_t>(n);
    for (int64_t i = 0LL; (i < n); i += 1LL) {
        out[i] = int32_t((i + 1LL));
    }
    return out;
}

int64_t RangeProbe(Counter& c) {
    int64_t t = int64_t(0LL);
    {
        auto _t1 = sliceFrom(c, 4LL);
        for (int64_t _t2 = 0; _t2 < _t1.len; _t2++) {
            int64_t i = _t2;
            int32_t v = _t1[_t2];
            t += (int64_t(i) * int64_t(v));
            i = 100LL;
        }
    }
    return ((t * 10LL) + int64_t(c.n));
}

int64_t RangeValProbe(vg::Slice<int32_t> xs) {
    int64_t t = int64_t(0LL);
    {
        auto _t1 = xs;
        for (int64_t _t2 = 0; _t2 < _t1.len; _t2++) {
            int32_t v = _t1[_t2];
            v = int32_t(v + 1);
            t += int64_t(v);
        }
    }
    for (int64_t i = 0LL; (i < vg::len(xs)); i += 1LL) {
        t += (int64_t(xs[i]) * 100LL);
    }
    return t;
}

int64_t RangeIntProbe(int64_t n) {
    int64_t t = int64_t(0LL);
    {
        auto _t1 = n;
        for (int64_t _t2 = 0; _t2 < _t1; _t2++) {
            int64_t i = _t2;
            t = ((t * 2LL) + int64_t(i));
        }
    }
    return t;
}

int64_t PartialArray() {
    std::array<int64_t, 5> a = std::array<int64_t, 5>{7LL, 9LL};
    std::array<vg::Str, 3> names = std::array<vg::Str, 3>{vg::lit("a")};
    int64_t t = int64_t(0LL);
    for (int64_t i = 0LL; (i < 5LL); i += 1LL) {
        t = ((t * 10LL) + a[size_t(i)]);
    }
    return (((t * 10LL) + int64_t(vg::len(names[size_t(1LL)]))) + int64_t(vg::len(names[size_t(0LL)])));
}

bool TaggedEq(Tagged a, Tagged b) {
    return (a == b);
}

int64_t three(int64_t a, int64_t b, int64_t x) {
    return (((a * 100LL) + (b * 10LL)) + x);
}

int64_t OrderArgs(Counter& c) {
    return ([&]{ auto _t1 = ([&]{ auto _t3 = bump(c, 1); auto _t4 = bump(c, 2); auto _t5 = bump(c, 3); return three(_t3, _t4, _t5); }()); auto _t2 = logCode(c); return (_t1 + _t2); }());
}

int64_t OrderBinary(Counter& c) {
    int64_t v = ([&]{ auto _t1 = bump(c, 4); auto _t2 = (2LL * bump(c, 5)); return (_t1 - _t2); }());
    return ([&]{ auto _t3 = (v * 10000LL); auto _t4 = logCode(c); return (_t3 + _t4); }());
}

int64_t OrderIndex(Counter& c) {
    vg::Slice<int32_t> s = sliceFrom(c, 6LL);
    int64_t v = int64_t(([&]() -> decltype(auto) { auto&& _t1 = s; auto _t2 = bump(c, 2); return _t1[_t2]; }()));
    return ([&]{ auto _t3 = (v * 10000LL); auto _t4 = logCode(c); return (_t3 + _t4); }());
}

int64_t SpareProbe() {
    vg::Slice<int64_t> s = vg::make_cap<int64_t>(0LL, 4LL);
    s = vg::append(s, 5LL);
    s = s.head(4LL);
    int64_t t = int64_t(0LL);
    for (int64_t i = 0LL; (i < vg::len(s)); i += 1LL) {
        t = (((t * 10LL) + s[i]) + 1LL);
    }
    vg::Slice<int64_t> g = vg::make_cap<int64_t>(0LL, 2LL);
    g = vg::append(g, 1LL);
    g = vg::append(g, 2LL);
    g = vg::append(g, 3LL);
    if ((g.cap >= 4LL)) {
        g = g.head(4LL);
    }
    for (int64_t i_2 = 0LL; (i_2 < 4LL); i_2 += 1LL) {
        t = (((t * 10LL) + g[i_2]) + 1LL);
    }
    return t;
}

int64_t NilProbe() {
    vg::Slice<int32_t> s{};
    int64_t t = int64_t(0LL);
    if ((s.p == nullptr)) {
        t += 1LL;
    }
    vg::Slice<int32_t> s2 = vg::make<int32_t>(0LL);
    if ((s2.p != nullptr)) {
        t += 2LL;
    }
    s = vg::append(s, 5);
    if ((s.p != nullptr)) {
        t += 4LL;
    }
    return t;
}

int64_t WrapProbe(int64_t a, int64_t b) {
    return (((a * b) + a) - b);
}

int32_t Narrow32(int32_t a, int32_t b) {
    return int32_t(int32_t(int32_t(a * b) - vg::sdiv<int32_t>(a, b)) + vg::srem<int32_t>(a, b));
}

uint8_t WrapU8(uint8_t a, uint8_t b) {
    return uint8_t(uint8_t(a - b) * 3);
}

uint32_t AndNotProbe(uint32_t a, uint32_t b) {
    uint32_t a_v = a;
    a_v &= ~(b);
    return uint32_t(a_v & ~(uint32_t(b >> 1LL)));
}

uint64_t ShiftProbe(uint64_t x, int64_t n) {
    return ((x << n) >> vg::sdiv<int64_t>(n, 2LL));
}

uint64_t ConvProbe(int64_t x) {
    return (uint64_t(uint8_t(x)) + (uint64_t(uint32_t(int32_t(x))) * 1000ULL));
}

int64_t SubWrite(int64_t n) {
    vg::Slice<int64_t> s = vg::make<int64_t>(n);
    s.tail(1LL)[0LL] = 7LL;
    s.tail(1LL).tail(1LL)[0LL] = 9LL;
    int64_t t = int64_t(0LL);
    for (int64_t i = 0LL; (i < vg::len(s)); i += 1LL) {
        t = ((t * 10LL) + s[i]);
    }
    return t;
}

int64_t AndNotOrder(Counter& c) {
    vg::Slice<uint64_t> s = vg::make<uint64_t>(8LL);
    s[3LL] = 255ULL;
    { auto&& _p = ([&]() -> decltype(auto) { auto&& _t1 = s; auto _t2 = (bump(c, 1) + 2LL); return _t1[_t2]; }()); _p &= ~((uint64_t(bump(c, 2)) + 15ULL)); }
    return ([&]{ auto _t3 = (int64_t(s[3LL]) * 100000LL); auto _t4 = logCode(c); return (_t3 + _t4); }());
}

int64_t ZeroArray() {
    std::array<int32_t, 0> a{};
    int64_t t = int64_t(0LL);
    if ((vg::arr_slice(a, 0, 0).p != nullptr)) {
        t += 1LL;
    }
    t = ((t * 10LL) + int64_t(vg::len(vg::arr_slice(a, 0, 0))));
    return t;
}

int64_t MakeU64(uint64_t n) {
    vg::Slice<int32_t> s = vg::make<int32_t>(n);
    return int64_t(vg::len(s));
}

std::array<int64_t, 3> mkTriple(int64_t x) {
    std::array<int64_t, 3> a{};
    a[size_t(0LL)] = x;
    a[size_t(1LL)] = (x + 1LL);
    a[size_t(2LL)] = (x + 2LL);
    return a;
}

int64_t PickArray(Counter& c) {
    int64_t v = ([&]() { auto&& _t1 = mkTriple(40LL); auto _t2 = bump(c, 2); return _t1[size_t(_t2)]; }());
    return ([&]{ auto _t3 = (v * 10000LL); auto _t4 = logCode(c); return (_t3 + _t4); }());
}

} // namespace probe
