// Command json2go converts a Vego JSON object back into one Go source file.
// It is the reference converter, because the same recipe with a different printer produces the C++, Rust or Zig instantiation.
// It also closes the verification loop.
// The engine rebuilds from revera.vego.json, and the test suite runs against the result.
// Success shows that the JSON carries the whole program.
//
// Usage:
//
//	json2go [-o output.go] input.json
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
)

type object = map[string]any

func fatal(args ...any) {
	fmt.Fprintln(os.Stderr, args...)
	os.Exit(1)
}

func main() {
	out := flag.String("o", "", "output file (default stdout)")
	flag.Parse()
	if flag.NArg() != 1 {
		fatal("usage: json2go [-o output.go] input.json")
	}
	blob, err := os.ReadFile(flag.Arg(0))
	if err != nil {
		fatal(err)
	}
	src, err := render(blob)
	if err != nil {
		fatal(err)
	}
	if *out == "" {
		os.Stdout.WriteString(src)
		return
	}
	if err := os.WriteFile(*out, []byte(src), 0o644); err != nil {
		fatal(err)
	}
}

func render(blob []byte) (src string, err error) {
	defer func() {
		if r := recover(); r != nil {
			src = ""
			err = fmt.Errorf("invalid Vego JSON: %v", r)
		}
	}()
	var doc object
	if err := json.Unmarshal(blob, &doc); err != nil {
		return "", err
	}
	if err := validateDocument(doc); err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("// Code generated by json2go from the Vego JSON form. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", doc["package"].(string))
	for _, d := range doc["consts"].([]any) {
		emitValueDecl(&b, "const", d.(object))
	}
	for _, d := range doc["vars"].([]any) {
		emitValueDecl(&b, "var", d.(object))
	}
	for _, d := range doc["types"].([]any) {
		emitType(&b, d.(object))
	}
	for _, d := range doc["funcs"].([]any) {
		emitFunc(&b, d.(object))
	}
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("format generated Go: %w", err)
	}
	return string(formatted), nil
}

func validateDocument(doc object) error {
	version, ok := doc["vego"].(float64)
	if !ok {
		return fmt.Errorf("invalid Vego JSON version")
	}
	if version != 1 {
		return fmt.Errorf("unsupported Vego JSON version %v", version)
	}
	if packageName, ok := doc["package"].(string); !ok || packageName == "" {
		return fmt.Errorf("invalid Vego JSON package")
	}
	for _, name := range []string{"consts", "vars", "types", "funcs"} {
		if _, ok := doc[name].([]any); !ok {
			return fmt.Errorf("invalid Vego JSON %s list", name)
		}
	}
	return nil
}

func typeRef(t any) string {
	o := t.(object)
	switch o["k"].(string) {
	case "named", "struct_ref":
		return o["name"].(string)
	case "slice":
		return "[]" + typeRef(o["elem"])
	case "array":
		return "[" + expr(o["len"]) + "]" + typeRef(o["elem"])
	case "ptr":
		return "*" + o["name"].(string)
	}
	fatal("unknown type kind", o["k"])
	return ""
}

func emitValueDecl(b *strings.Builder, kw string, d object) {
	if d["type"] != nil {
		fmt.Fprintf(b, "%s %s %s = %s\n\n", kw, d["name"], typeRef(d["type"]),
			expr(d["value"]))
		return
	}
	fmt.Fprintf(b, "%s %s = %s\n\n", kw, d["name"], expr(d["value"]))
}

func emitType(b *strings.Builder, d object) {
	fmt.Fprintf(b, "type %s struct {\n", d["name"])
	for _, f := range d["fields"].([]any) {
		field := f.(object)
		fmt.Fprintf(b, "\t%s %s\n", field["name"], typeRef(field["type"]))
	}
	b.WriteString("}\n\n")
}

func emitFunc(b *strings.Builder, d object) {
	var params []string
	for _, p := range d["params"].([]any) {
		po := p.(object)
		params = append(params, po["name"].(string)+" "+typeRef(po["type"]))
	}
	var results []string
	for _, r := range d["results"].([]any) {
		results = append(results, typeRef(r))
	}
	sig := fmt.Sprintf("func %s(%s)", d["name"], strings.Join(params, ", "))
	switch len(results) {
	case 0:
	case 1:
		sig += " " + results[0]
	default:
		sig += " (" + strings.Join(results, ", ") + ")"
	}
	b.WriteString(sig + " {\n")
	emitBody(b, d["body"].([]any), 1)
	b.WriteString("}\n\n")
}

func indent(b *strings.Builder, depth int) {
	for i := 0; i < depth; i++ {
		b.WriteByte('\t')
	}
}

func emitBody(b *strings.Builder, body []any, depth int) {
	for _, s := range body {
		indent(b, depth)
		emitStmt(b, s.(object), depth)
		b.WriteByte('\n')
	}
}

// inlineStmt renders a statement without indentation or newline, for loop init and post positions.
func inlineStmt(s object) string {
	var b strings.Builder
	emitStmt(&b, s, 0)
	return b.String()
}

func emitStmt(b *strings.Builder, s object, depth int) {
	switch s["k"].(string) {
	case "var_decl":
		if s["type"] != nil && s["value"] != nil {
			fmt.Fprintf(b, "var %s %s = %s", s["name"], typeRef(s["type"]),
				expr(s["value"]))
		} else if s["type"] != nil {
			fmt.Fprintf(b, "var %s %s", s["name"], typeRef(s["type"]))
		} else {
			fmt.Fprintf(b, "var %s = %s", s["name"], expr(s["value"]))
		}
	case "define":
		var names []string
		for _, n := range s["names"].([]any) {
			names = append(names, n.(string))
		}
		fmt.Fprintf(b, "%s := %s", strings.Join(names, ", "), expr(s["value"]))
	case "assign":
		var lhs []string
		for _, l := range s["lhs"].([]any) {
			lhs = append(lhs, expr(l))
		}
		fmt.Fprintf(b, "%s = %s", strings.Join(lhs, ", "), expr(s["value"]))
	case "op_assign":
		fmt.Fprintf(b, "%s %s %s", expr(s["lhs"]), s["op"], expr(s["value"]))
	case "incdec":
		fmt.Fprintf(b, "%s%s", expr(s["lhs"]), s["op"])
	case "if":
		fmt.Fprintf(b, "if %s {\n", expr(s["cond"]))
		emitBody(b, s["then"].([]any), depth+1)
		indent(b, depth)
		b.WriteString("}")
		if s["else"] != nil {
			b.WriteString(" else {\n")
			emitBody(b, s["else"].([]any), depth+1)
			indent(b, depth)
			b.WriteString("}")
		}
	case "for":
		b.WriteString("for ")
		if s["init"] != nil || s["post"] != nil {
			if s["init"] != nil {
				b.WriteString(inlineStmt(s["init"].(object)))
			}
			b.WriteString("; ")
			if s["cond"] != nil {
				b.WriteString(expr(s["cond"]))
			}
			b.WriteString("; ")
			if s["post"] != nil {
				b.WriteString(inlineStmt(s["post"].(object)))
			}
		} else if s["cond"] != nil {
			b.WriteString(expr(s["cond"]))
		}
		b.WriteString(" {\n")
		emitBody(b, s["body"].([]any), depth+1)
		indent(b, depth)
		b.WriteString("}")
	case "range":
		b.WriteString("for ")
		switch {
		case s["idx"] != nil && s["val"] != nil:
			fmt.Fprintf(b, "%s, %s := range %s", s["idx"], s["val"], expr(s["over"]))
		case s["idx"] != nil:
			fmt.Fprintf(b, "%s := range %s", s["idx"], expr(s["over"]))
		default:
			fmt.Fprintf(b, "range %s", expr(s["over"]))
		}
		b.WriteString(" {\n")
		emitBody(b, s["body"].([]any), depth+1)
		indent(b, depth)
		b.WriteString("}")
	case "switch":
		fmt.Fprintf(b, "switch %s {\n", expr(s["tag"]))
		for _, raw := range s["cases"].([]any) {
			cl := raw.(object)
			var values []string
			for _, v := range cl["values"].([]any) {
				values = append(values, expr(v))
			}
			indent(b, depth)
			fmt.Fprintf(b, "case %s:\n", strings.Join(values, ", "))
			emitBody(b, cl["body"].([]any), depth+1)
		}
		if s["default"] != nil {
			indent(b, depth)
			b.WriteString("default:\n")
			emitBody(b, s["default"].([]any), depth+1)
		}
		indent(b, depth)
		b.WriteString("}")
	case "break":
		b.WriteString("break")
	case "continue":
		b.WriteString("continue")
	case "return":
		values := s["values"].([]any)
		if len(values) == 0 {
			b.WriteString("return")
			break
		}
		var out []string
		for _, v := range values {
			out = append(out, expr(v))
		}
		b.WriteString("return " + strings.Join(out, ", "))
	case "expr_stmt":
		b.WriteString(expr(s["value"]))
	case "block":
		b.WriteString("{\n")
		emitBody(b, s["body"].([]any), depth+1)
		indent(b, depth)
		b.WriteString("}")
	default:
		fatal("unknown statement kind", s["k"])
	}
}

func expr(e any) string {
	o := e.(object)
	switch o["k"].(string) {
	case "int", "char":
		return o["value"].(string)
	case "str":
		return strconv.Quote(o["value"].(string))
	case "bool":
		if o["value"].(bool) {
			return "true"
		}
		return "false"
	case "ident":
		return o["name"].(string)
	case "field":
		return expr(o["x"]) + "." + o["name"].(string)
	case "index":
		return expr(o["x"]) + "[" + expr(o["index"]) + "]"
	case "slice_expr":
		lo := ""
		hi := ""
		if o["lo"] != nil {
			lo = expr(o["lo"])
		}
		if o["hi"] != nil {
			hi = expr(o["hi"])
		}
		return expr(o["x"]) + "[" + lo + ":" + hi + "]"
	case "call":
		var args []string
		for _, a := range o["args"].([]any) {
			args = append(args, expr(a))
		}
		return o["fn"].(string) + "(" + strings.Join(args, ", ") + ")"
	case "builtin":
		var args []string
		if o["fn"] == "make" {
			args = append(args, typeRef(o["type"]))
		}
		for _, a := range o["args"].([]any) {
			args = append(args, expr(a))
		}
		suffix := ""
		if o["spread"].(bool) {
			suffix = "..."
		}
		return o["fn"].(string) + "(" + strings.Join(args, ", ") + suffix + ")"
	case "conv":
		t := typeRef(o["type"])
		// A composite type name needs parentheses to parse as the conversion operand, as in ([]uint8)(x).
		// The choice looks at the JSON kind, so a future ptr or array conversion lands here too.
		kind := o["type"].(object)["k"].(string)
		if kind != "named" && kind != "struct_ref" {
			t = "(" + t + ")"
		}
		return t + "(" + expr(o["x"]) + ")"
	case "unary":
		op := o["op"].(string)
		if op == "&" {
			return op + expr(o["x"])
		}
		return "(" + op + expr(o["x"]) + ")"
	case "binary":
		return "(" + expr(o["x"]) + " " + o["op"].(string) + " " + expr(o["y"]) + ")"
	case "composite":
		t := typeRef(o["type"])
		if fields, ok := o["fields"]; ok && fields != nil {
			var parts []string
			for _, f := range fields.([]any) {
				fo := f.(object)
				parts = append(parts, fo["name"].(string)+": "+expr(fo["value"]))
			}
			return t + "{" + strings.Join(parts, ", ") + "}"
		}
		var parts []string
		for _, el := range o["elems"].([]any) {
			parts = append(parts, expr(el))
		}
		return t + "{" + strings.Join(parts, ", ") + "}"
	}
	fatal("unknown expression kind", o["k"])
	return ""
}
