// Code generated by vegoc from the Vego JSON form. DO NOT EDIT.

import * as vg from "./vg.ts";

const _s1: vg.Str = vg.lit("a");

export const minI64: number = (-9223372036854775808);


export class Counter {
    n: number;
    log: vg.Slice<number>;

    constructor(n: number = 0, log: vg.Slice<number> = vg.NIL) {
        this.n = n;
        this.log = log;
    }

    clone(): Counter {
        return new Counter(this.n, this.log);
    }

    static readonly elem: vg.Elem<Counter> = vg.structElem(() => new Counter(), 40);
}

export class Tagged {
    Tags: vg.Str[];
    N: number;

    constructor(Tags: vg.Str[] = vg.makeArr(2, () => vg.EMPTY), N: number = 0) {
        this.Tags = Tags;
        this.N = N;
    }

    clone(): Tagged {
        return new Tagged(this.Tags.slice(), this.N);
    }

    static eq(a: Tagged, b: Tagged): boolean {
        return vg.arrEq(a.Tags, b.Tags, (x, y) => vg.streq(x, y)) && a.N === b.N;
    }

    static readonly elem: vg.Elem<Tagged> = vg.structElem(() => new Tagged(), 36);
}

export function bump(c: Counter, tag: number): bigint {
    c.n = vg.chk(c.n + 1);
    c.log = vg.append(vg.I32, c.log, tag);
    return BigInt(tag);
}

export function logCode(c: Counter): bigint {
    let _t2!: vg.Slice<number>;
    let v: bigint = 0n;
    for (let i: number = 0; (i < c.log.len); i = vg.chk(i + 1)) {
        v = BigInt.asIntN(64, BigInt.asIntN(64, v * 10n) + BigInt((_t2 = c.log, _t2.buf[_t2.off + vg.ix(i, _t2.len)])));
    }
    return BigInt.asIntN(64, BigInt.asIntN(64, v * 100n) + BigInt(c.n));
}

export function DivMod(a: bigint, b: bigint): [bigint, bigint] {
    return [BigInt.asIntN(64, vg.divBig(a, b)), vg.remBig(a, b)];
}

export function DivMod32(a: number, b: number): [number, number] {
    return [(vg.div(a, b) | 0), vg.rem(a, b)];
}

export function BytesProbe(s: vg.Str): bigint {
    const b: vg.Slice<number> = vg.bytesFromStr(s);
    if ((b.len > 0)) {
        b.buf[b.off + vg.ix(0, b.len)] = 88;
    }
    let t: bigint = 0n;
    for (let i: number = 0; (i < b.len); i = vg.chk(i + 1)) {
        t = BigInt.asIntN(64, BigInt.asIntN(64, t * 31n) + BigInt(b.buf[b.off + vg.ix(i, b.len)]));
    }
    return t;
}

export function sliceFrom(c: Counter, n: number): vg.Slice<number> {
    c.n = vg.chk(c.n + 1);
    const out: vg.Slice<number> = vg.make(vg.I32, n);
    for (let i: number = 0; (i < n); i = vg.chk(i + 1)) {
        out.buf[out.off + vg.ix(i, out.len)] = (vg.chk(i + 1) | 0);
    }
    return out;
}

export function RangeProbe(c: Counter): bigint {
    let t: bigint = 0n;
    {
        const _t1 = sliceFrom(c, 4);
        for (let _t2 = 0; _t2 < _t1.len; _t2++) {
            let i: number = _t2;
            const v: number = _t1.buf[_t1.off + vg.ix(_t2, _t1.len)];
            t = BigInt.asIntN(64, t + BigInt.asIntN(64, BigInt(i) * BigInt(v)));
            i = 100;
        }
    }
    return BigInt.asIntN(64, BigInt.asIntN(64, t * 10n) + BigInt(c.n));
}

export function RangeValProbe(xs: vg.Slice<number>): bigint {
    let t: bigint = 0n;
    {
        const _t1 = xs;
        for (let _t2 = 0; _t2 < _t1.len; _t2++) {
            let v: number = _t1.buf[_t1.off + vg.ix(_t2, _t1.len)];
            v = ((v + 1) | 0);
            t = BigInt.asIntN(64, t + BigInt(v));
        }
    }
    for (let i: number = 0; (i < xs.len); i = vg.chk(i + 1)) {
        t = BigInt.asIntN(64, t + BigInt.asIntN(64, BigInt(xs.buf[xs.off + vg.ix(i, xs.len)]) * 100n));
    }
    return t;
}

export function RangeIntProbe(n: number): bigint {
    let t: bigint = 0n;
    {
        const _t1 = n;
        for (let _t2 = 0; _t2 < _t1; _t2++) {
            const i: number = _t2;
            t = BigInt.asIntN(64, BigInt.asIntN(64, t * 2n) + BigInt(i));
        }
    }
    return t;
}

export function PartialArray(): bigint {
    const a: BigInt64Array = new BigInt64Array([7n, 9n, 0n, 0n, 0n]);
    const names: vg.Str[] = [_s1, vg.EMPTY, vg.EMPTY];
    let t: bigint = 0n;
    for (let i: number = 0; (i < 5); i = vg.chk(i + 1)) {
        t = BigInt.asIntN(64, BigInt.asIntN(64, t * 10n) + a[vg.ix(i, 5)]);
    }
    return BigInt.asIntN(64, BigInt.asIntN(64, BigInt.asIntN(64, t * 10n) + BigInt(names[1].length)) + BigInt(names[0].length));
}

export function TaggedEq(a: Tagged, b: Tagged): boolean {
    return Tagged.eq(a, b);
}

export function three(a: bigint, b: bigint, x: bigint): bigint {
    return BigInt.asIntN(64, BigInt.asIntN(64, BigInt.asIntN(64, a * 100n) + BigInt.asIntN(64, b * 10n)) + x);
}

export function OrderArgs(c: Counter): bigint {
    return BigInt.asIntN(64, three(bump(c, 1), bump(c, 2), bump(c, 3)) + logCode(c));
}

export function OrderBinary(c: Counter): bigint {
    const v: bigint = BigInt.asIntN(64, bump(c, 4) - BigInt.asIntN(64, 2n * bump(c, 5)));
    return BigInt.asIntN(64, BigInt.asIntN(64, v * 10000n) + logCode(c));
}

export function OrderIndex(c: Counter): bigint {
    let _t1!: vg.Slice<number>;
    const s: vg.Slice<number> = sliceFrom(c, 6);
    const v: bigint = BigInt((_t1 = s, _t1.buf[_t1.off + vg.ix(vg.intOf(bump(c, 2)), _t1.len)]));
    return BigInt.asIntN(64, BigInt.asIntN(64, v * 10000n) + logCode(c));
}

export function SpareProbe(): bigint {
    let s: vg.Slice<bigint> = vg.make(vg.I64, 0, 4);
    s = vg.append(vg.I64, s, 5n);
    s = vg.head(s, 4);
    let t: bigint = 0n;
    for (let i: number = 0; (i < s.len); i = vg.chk(i + 1)) {
        t = BigInt.asIntN(64, BigInt.asIntN(64, BigInt.asIntN(64, t * 10n) + s.buf[s.off + vg.ix(i, s.len)]) + 1n);
    }
    let g: vg.Slice<bigint> = vg.make(vg.I64, 0, 2);
    g = vg.append(vg.I64, g, 1n);
    g = vg.append(vg.I64, g, 2n);
    g = vg.append(vg.I64, g, 3n);
    if ((g.cap >= 4)) {
        g = vg.head(g, 4);
    }
    for (let i_2: number = 0; (i_2 < 4); i_2 = vg.chk(i_2 + 1)) {
        t = BigInt.asIntN(64, BigInt.asIntN(64, BigInt.asIntN(64, t * 10n) + g.buf[g.off + vg.ix(i_2, g.len)]) + 1n);
    }
    return t;
}

export function NilProbe(): bigint {
    let s: vg.Slice<number> = vg.NIL;
    let t: bigint = 0n;
    if ((s.buf === null)) {
        t = BigInt.asIntN(64, t + 1n);
    }
    const s2: vg.Slice<number> = vg.make(vg.I32, 0);
    if ((s2.buf !== null)) {
        t = BigInt.asIntN(64, t + 2n);
    }
    s = vg.append(vg.I32, s, 5);
    if ((s.buf !== null)) {
        t = BigInt.asIntN(64, t + 4n);
    }
    return t;
}

export function WrapProbe(a: bigint, b: bigint): bigint {
    return BigInt.asIntN(64, BigInt.asIntN(64, BigInt.asIntN(64, a * b) + a) - b);
}

export function Narrow32(a: number, b: number): number {
    return ((((Math.imul(a, b) - (vg.div(a, b) | 0)) | 0) + vg.rem(a, b)) | 0);
}

export function WrapU8(a: number, b: number): number {
    return ((((a - b) & 0xff) * 3) & 0xff);
}

export function AndNotProbe(a: number, b: number): number {
    let a_v: number = a;
    a_v = ((a_v & ~b) >>> 0);
    return ((a_v & ~(b >>> 1)) >>> 0);
}

export function ShiftProbe(x: bigint, n: number): bigint {
    return (BigInt.asUintN(64, x << vg.shiftCount(n)) >> vg.shiftCount(vg.div(n, 2)));
}

export function ConvProbe(x: bigint): bigint {
    return BigInt.asUintN(64, BigInt(Number(BigInt.asUintN(8, x))) + BigInt.asUintN(64, BigInt((Number(BigInt.asIntN(32, x)) >>> 0)) * 1000n));
}

export function SubWrite(n: number): bigint {
    let _t1!: vg.Slice<bigint>;
    let _t2!: number;
    let _t3!: vg.Slice<bigint>;
    let _t4!: number;
    const s: vg.Slice<bigint> = vg.make(vg.I64, n);
    (_t1 = vg.tail(s, 1), _t2 = vg.ix(0, _t1.len), _t1.buf[_t1.off + _t2] = 7n);
    (_t3 = vg.tail(vg.tail(s, 1), 1), _t4 = vg.ix(0, _t3.len), _t3.buf[_t3.off + _t4] = 9n);
    let t: bigint = 0n;
    for (let i: number = 0; (i < s.len); i = vg.chk(i + 1)) {
        t = BigInt.asIntN(64, BigInt.asIntN(64, t * 10n) + s.buf[s.off + vg.ix(i, s.len)]);
    }
    return t;
}

export function AndNotOrder(c: Counter): bigint {
    let _t1!: vg.Slice<bigint>;
    let _t2!: number;
    const s: vg.Slice<bigint> = vg.make(vg.U64, 8);
    s.buf[s.off + vg.ix(3, s.len)] = 255n;
    (_t1 = s, _t2 = vg.ix(vg.intOf(BigInt.asIntN(64, bump(c, 1) + 2n)), _t1.len), _t1.buf[_t1.off + _t2] = BigInt.asUintN(64, _t1.buf[_t1.off + _t2] & ~BigInt.asUintN(64, BigInt.asUintN(64, bump(c, 2)) + 15n)));
    return BigInt.asIntN(64, BigInt.asIntN(64, BigInt.asIntN(64, s.buf[s.off + vg.ix(3, s.len)]) * 100000n) + logCode(c));
}

export function ZeroArray(): bigint {
    let a: Int32Array = new Int32Array(0);
    let t: bigint = 0n;
    if ((vg.arrSlice(a, 0, 0).buf !== null)) {
        t = BigInt.asIntN(64, t + 1n);
    }
    t = BigInt.asIntN(64, BigInt.asIntN(64, t * 10n) + BigInt(vg.arrSlice(a, 0, 0).len));
    return t;
}

export function MakeU64(n: bigint): bigint {
    const s: vg.Slice<number> = vg.make(vg.I32, vg.intOf(n));
    return BigInt(s.len);
}

export function mkTriple(x: bigint): BigInt64Array {
    let a: BigInt64Array = new BigInt64Array(3);
    a[0] = x;
    a[1] = BigInt.asIntN(64, x + 1n);
    a[2] = BigInt.asIntN(64, x + 2n);
    return a;
}

export function PickArray(c: Counter): bigint {
    let _t1!: BigInt64Array;
    const v: bigint = (_t1 = mkTriple(40n), _t1[vg.ix(vg.intOf(bump(c, 2)), 3)]);
    return BigInt.asIntN(64, BigInt.asIntN(64, v * 10000n) + logCode(c));
}

